# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($map__float_float_float_float_float, $blendOverlay__float_float, $blendSoftLight__float_float, $cloak__vec2, $hsv2rgb__vec3, $rgb2hsv__vec3, $blend__vec4_vec4_int_float, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_tex = $ctx->texture_binding('tex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_blendMode = exists $U->{'blendMode'} ? $U->{'blendMode'} : 0;
    my $_u_mixAmt = exists $U->{'mixAmt'} ? $U->{'mixAmt'} : $rt->f(0.0);
    my $_u_refractAAmt = exists $U->{'refractAAmt'} ? $U->{'refractAAmt'} : $rt->f(0.0);
    my $_u_refractBAmt = exists $U->{'refractBAmt'} ? $U->{'refractBAmt'} : $rt->f(0.0);
    my $_u_refractADir = exists $U->{'refractADir'} ? $U->{'refractADir'} : $rt->f(0.0);
    my $_u_refractBDir = exists $U->{'refractBDir'} ? $U->{'refractBDir'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $map__float_float_float_float_float = sub {
        my ($value, $inMin, $inMax, $outMin, $outMax) = @_;
        return $rt->binary('+', $outMin, $rt->binary('/', $rt->binary('*', $rt->binary('-', $outMax, $outMin, 1, 'float'), $rt->binary('-', $value, $inMin, 1, 'float'), 1, 'float'), $rt->binary('-', $inMax, $inMin, 1, 'float'), 1, 'float'), 1, 'float');
    };
    $blendOverlay__float_float = sub {
        my ($a, $b) = @_;
        return (($rt->binary('<', $a, $rt->f(0.5))) ? ($rt->binary('*', $rt->binary('*', $rt->f(2), $a, 1, 'float'), $b, 1, 'float')) : ($rt->binary('-', $rt->f(1), $rt->binary('*', $rt->binary('*', $rt->f(2), $rt->binary('-', $rt->f(1), $a, 1, 'float'), 1, 'float'), $rt->binary('-', $rt->f(1), $b, 1, 'float'), 1, 'float'), 1, 'float')));
    };
    $blendSoftLight__float_float = sub {
        my ($base, $blend) = @_;
        return (($rt->binary('<', $blend, $rt->f(0.5))) ? ($rt->binary('+', $rt->binary('*', $rt->binary('*', $rt->f(2), $base, 1, 'float'), $blend, 1, 'float'), $rt->binary('*', $rt->binary('*', $base, $base, 1, 'float'), $rt->binary('-', $rt->f(1), $rt->binary('*', $rt->f(2), $blend, 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->component_wise('sqrt', $base), $rt->binary('-', $rt->binary('*', $rt->f(2), $blend, 1, 'float'), $rt->f(1), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $rt->f(2), $base, 1, 'float'), $rt->binary('-', $rt->f(1), $blend, 1, 'float'), 1, 'float'), 1, 'float')));
    };
    $cloak__vec2 = sub {
        my ($st) = @_;
        $st = $rt->copy($st, 'float');
        my ($left, $leftColor, $leftLen, $leftLocalUV, $leftReflected, $leftRefracted, $leftUV, $m, $ra, $rb, $right, $rightColor, $rightLen, $rightLocalUV, $rightReflected, $rightRefracted, $rightUV);
        $m = $map__float_float_float_float_float->($_u_mixAmt, $rt->unary('-', $rt->f(100)), $rt->f(100), $rt->f(0), $rt->f(1));
        $ra = $map__float_float_float_float_float->($_u_refractAAmt, $rt->f(0), $rt->f(100), $rt->f(0), $rt->f(0.125));
        $rb = $map__float_float_float_float_float->($_u_refractBAmt, $rt->f(0), $rt->f(100), $rt->f(0), $rt->f(0.125));
        $leftColor = $rt->texture($_u_inputTex, $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($_u_inputTex)), 2, 'float'));
        $rightColor = $rt->texture($_u_tex, $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($_u_tex)), 2, 'float'));
        $leftUV = $rt->construct(2, $st);
        $rightLen = $rt->length($rt->swizzle($rightColor, 'rgb'));
        $leftUV = $rt->assign_swizzle($leftUV, 'x', $rt->binary('+', $rt->swizzle($leftUV, 'x'), $rt->binary('*', $rt->component_wise('cos', $rt->binary('*', $rightLen, $rt->f(6.2831853071800001), 1, 'float')), $ra, 1, 'float'), 1, 'float'));
        $leftUV = $rt->assign_swizzle($leftUV, 'y', $rt->binary('+', $rt->swizzle($leftUV, 'y'), $rt->binary('*', $rt->component_wise('sin', $rt->binary('*', $rightLen, $rt->f(6.2831853071800001), 1, 'float')), $ra, 1, 'float'), 1, 'float'));
        $leftLocalUV = $rt->binary('/', $rt->binary('-', $rt->binary('*', $leftUV, $_u_fullResolution, 2, 'float'), $_u_tileOffset, 2, 'float'), $rt->construct(2, $rt->texture_size($_u_inputTex)), 2, 'float');
        $leftRefracted = $rt->texture($_u_inputTex, $rt->component_wise('fract', $leftLocalUV));
        $rightUV = $rt->construct(2, $st);
        $leftLen = $rt->length($rt->swizzle($leftColor, 'rgb'));
        $rightUV = $rt->assign_swizzle($rightUV, 'x', $rt->binary('+', $rt->swizzle($rightUV, 'x'), $rt->binary('*', $rt->component_wise('cos', $rt->binary('*', $leftLen, $rt->f(6.2831853071800001), 1, 'float')), $rb, 1, 'float'), 1, 'float'));
        $rightUV = $rt->assign_swizzle($rightUV, 'y', $rt->binary('+', $rt->swizzle($rightUV, 'y'), $rt->binary('*', $rt->component_wise('sin', $rt->binary('*', $leftLen, $rt->f(6.2831853071800001), 1, 'float')), $rb, 1, 'float'), 1, 'float'));
        $rightLocalUV = $rt->binary('/', $rt->binary('-', $rt->binary('*', $rightUV, $_u_fullResolution, 2, 'float'), $_u_tileOffset, 2, 'float'), $rt->construct(2, $rt->texture_size($_u_tex)), 2, 'float');
        $rightRefracted = $rt->texture($_u_tex, $rt->component_wise('fract', $rightLocalUV));
        $leftReflected = $rt->component_wise('min', $rt->binary('/', $rt->binary('*', $rightRefracted, $rightColor, 4, 'float'), $rt->binary('-', $rt->f(1), $rt->binary('*', $leftRefracted, $leftColor, 4, 'float'), 4, 'float'), 4, 'float'), $rt->construct(4, $rt->f(1)));
        $rightReflected = $rt->component_wise('min', $rt->binary('/', $rt->binary('*', $leftRefracted, $leftColor, 4, 'float'), $rt->binary('-', $rt->f(1), $rt->binary('*', $rightRefracted, $rightColor, 4, 'float'), 4, 'float'), 4, 'float'), $rt->construct(4, $rt->f(1)));
        $left = $rt->construct(4, $rt->f(1));
        $right = $rt->construct(4, $rt->f(1));
        if ($rt->binary('<', $_u_mixAmt, $rt->f(0))) {
            @{$left} = map { $rt->f32($_) } @{($rt->component_wise('mix', $leftRefracted, $leftReflected, $map__float_float_float_float_float->($_u_mixAmt, $rt->unary('-', $rt->f(100)), $rt->f(0), $rt->f(0), $rt->f(1))))};
            @{$right} = map { $rt->f32($_) } @{($rightReflected)};
        } else {
            @{$left} = map { $rt->f32($_) } @{($leftReflected)};
            @{$right} = map { $rt->f32($_) } @{($rt->component_wise('mix', $rightRefracted, $rightRefracted, $map__float_float_float_float_float->($_u_mixAmt, $rt->f(0), $rt->f(100), $rt->f(0), $rt->f(1))))};
        }
        return $rt->component_wise('mix', $left, $right, $m);
    };
    $hsv2rgb__vec3 = sub {
        my ($hsv) = @_;
        $hsv = $rt->copy($hsv, 'float');
        my ($c, $h, $m, $rgb, $s, $v, $x);
        $h = $rt->component_wise('fract', $rt->swizzle($hsv, 'x'));
        $s = $rt->swizzle($hsv, 'y');
        $v = $rt->swizzle($hsv, 'z');
        $c = $rt->binary('*', $v, $s, 1, 'float');
        $x = $rt->binary('*', $c, $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->component_wise('mod', $rt->binary('*', $h, $rt->f(6), 1, 'float'), $rt->f(2)), $rt->f(1), 1, 'float')), 1, 'float'), 1, 'float');
        $m = $rt->binary('-', $v, $c, 1, 'float');
        $rgb = $rt->construct(3, 0.0);
        if ((($rt->binary('<=', $rt->f(0), $h)) && ($rt->binary('<', $h, $rt->binary('/', $rt->f(1), $rt->f(6), 1, 'float'))) ? 1 : 0)) {
            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $x, $rt->f(0)))};
        } else {
            if ((($rt->binary('<=', $rt->binary('/', $rt->f(1), $rt->f(6), 1, 'float'), $h)) && ($rt->binary('<', $h, $rt->binary('/', $rt->f(2), $rt->f(6), 1, 'float'))) ? 1 : 0)) {
                @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $c, $rt->f(0)))};
            } else {
                if ((($rt->binary('<=', $rt->binary('/', $rt->f(2), $rt->f(6), 1, 'float'), $h)) && ($rt->binary('<', $h, $rt->binary('/', $rt->f(3), $rt->f(6), 1, 'float'))) ? 1 : 0)) {
                    @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $c, $x))};
                } else {
                    if ((($rt->binary('<=', $rt->binary('/', $rt->f(3), $rt->f(6), 1, 'float'), $h)) && ($rt->binary('<', $h, $rt->binary('/', $rt->f(4), $rt->f(6), 1, 'float'))) ? 1 : 0)) {
                        @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $x, $c))};
                    } else {
                        if ((($rt->binary('<=', $rt->binary('/', $rt->f(4), $rt->f(6), 1, 'float'), $h)) && ($rt->binary('<', $h, $rt->binary('/', $rt->f(5), $rt->f(6), 1, 'float'))) ? 1 : 0)) {
                            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $rt->f(0), $c))};
                        } else {
                            if ((($rt->binary('<=', $rt->binary('/', $rt->f(5), $rt->f(6), 1, 'float'), $h)) && ($rt->binary('<', $h, $rt->f(1))) ? 1 : 0)) {
                                @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $rt->f(0), $x))};
                            } else {
                                @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $rt->f(0), $rt->f(0)))};
                            }
                        }
                    }
                }
            }
        }
        return $rt->binary('+', $rgb, $rt->construct(3, $m, $m, $m), 3, 'float');
    };
    $rgb2hsv__vec3 = sub {
        my ($rgb) = @_;
        $rgb = $rt->copy($rgb, 'float');
        my ($_g, $b, $delta, $h, $max, $min, $r, $s, $v);
        $r = $rt->swizzle($rgb, 'r');
        $_g = $rt->swizzle($rgb, 'g');
        $b = $rt->swizzle($rgb, 'b');
        $max = $rt->component_wise('max', $r, $rt->component_wise('max', $_g, $b));
        $min = $rt->component_wise('min', $r, $rt->component_wise('min', $_g, $b));
        $delta = $rt->binary('-', $max, $min, 1, 'float');
        $h = $rt->f(0);
        if ($rt->binary('!=', $delta, $rt->f(0))) {
            if ($rt->binary('==', $max, $r)) {
                $h = $rt->binary('/', $rt->component_wise('mod', $rt->binary('/', $rt->binary('-', $_g, $b, 1, 'float'), $delta, 1, 'float'), $rt->f(6)), $rt->f(6), 1, 'float');
            } else {
                if ($rt->binary('==', $max, $_g)) {
                    $h = $rt->binary('/', $rt->binary('+', $rt->binary('/', $rt->binary('-', $b, $r, 1, 'float'), $delta, 1, 'float'), $rt->f(2), 1, 'float'), $rt->f(6), 1, 'float');
                } else {
                    if ($rt->binary('==', $max, $b)) {
                        $h = $rt->binary('/', $rt->binary('+', $rt->binary('/', $rt->binary('-', $r, $_g, 1, 'float'), $delta, 1, 'float'), $rt->f(4), 1, 'float'), $rt->f(6), 1, 'float');
                    }
                }
            }
        }
        $s = (($rt->binary('==', $max, $rt->f(0))) ? ($rt->f(0)) : ($rt->binary('/', $delta, $max, 1, 'float')));
        $v = $max;
        return $rt->construct(3, $h, $s, $v);
    };
    $blend__vec4_vec4_int_float = sub {
        my ($color1, $color2, $mode, $factor) = @_;
        $color1 = $rt->copy($color1, 'float');
        $color2 = $rt->copy($color2, 'float');
        my ($a, $amt, $b, $color, $middle);
        $color = $rt->construct(4, 0.0);
        $middle = $rt->construct(4, 0.0);
        $amt = $map__float_float_float_float_float->($_u_mixAmt, $rt->unary('-', $rt->f(100)), $rt->f(100), $rt->f(0), $rt->f(1));
        $a = $rt->construct(4, $rt->f(1));
        $b = $rt->construct(4, $rt->f(1));
        if ($rt->binary('>=', $mode, $rt->i(1000))) {
            $a = $rt->assign_swizzle($a, 'rgb', $rgb2hsv__vec3->($rt->swizzle($color1, 'rgb')));
            $b = $rt->assign_swizzle($b, 'rgb', $rgb2hsv__vec3->($rt->swizzle($color2, 'rgb')));
        }
        if ($rt->binary('==', $mode, $rt->i(0))) {
            @{$middle} = map { $rt->f32($_) } @{($rt->component_wise('min', $rt->binary('+', $color1, $color2, 4, 'float'), $rt->f(1)))};
        } else {
            if ($rt->binary('==', $mode, $rt->i(1))) {
                if ($rt->binary('<', $_u_mixAmt, $rt->f(0))) {
                    return $rt->swizzle($rt->component_wise('mix', $color1, $rt->binary('+', $rt->binary('*', $color2, $rt->construct(4, $rt->binary('-', $rt->f(1), $rt->swizzle($color1, 'a'), 1, 'float')), 4, 'float'), $rt->binary('*', $color1, $rt->construct(4, $rt->swizzle($color1, 'a')), 4, 'float'), 4, 'float'), $map__float_float_float_float_float->($_u_mixAmt, $rt->unary('-', $rt->f(100)), $rt->f(0), $rt->f(0), $rt->f(1))), 'rgb');
                } else {
                    return $rt->swizzle($rt->component_wise('mix', $rt->binary('+', $rt->binary('*', $color1, $rt->construct(4, $rt->binary('-', $rt->f(1), $rt->swizzle($color2, 'a'), 1, 'float')), 4, 'float'), $rt->binary('*', $color2, $rt->construct(4, $rt->swizzle($color2, 'a')), 4, 'float'), 4, 'float'), $color2, $map__float_float_float_float_float->($_u_mixAmt, $rt->f(0), $rt->f(100), $rt->f(0), $rt->f(1))), 'rgb');
                }
            } else {
                if ($rt->binary('==', $mode, $rt->i(2))) {
                    @{$middle} = map { $rt->f32($_) } @{((($rt->binary('==', $color2, $rt->construct(4, $rt->f(0)))) ? ($color2) : ($rt->component_wise('max', $rt->binary('-', $rt->f(1), $rt->binary('/', $rt->binary('-', $rt->f(1), $color1, 4, 'float'), $color2, 4, 'float'), 4, 'float'), $rt->construct(4, $rt->f(0))))))};
                } else {
                    if ($rt->binary('==', $mode, $rt->i(3))) {
                        @{$middle} = map { $rt->f32($_) } @{((($rt->binary('==', $color2, $rt->construct(4, $rt->f(1)))) ? ($color2) : ($rt->component_wise('min', $rt->binary('/', $color1, $rt->binary('-', $rt->f(1), $color2, 4, 'float'), 4, 'float'), $rt->construct(4, $rt->f(1))))))};
                    } else {
                        if ($rt->binary('==', $mode, $rt->i(4))) {
                            @{$middle} = map { $rt->f32($_) } @{($rt->component_wise('min', $color1, $color2))};
                        } else {
                            if ($rt->binary('==', $mode, $rt->i(5))) {
                                @{$middle} = map { $rt->f32($_) } @{($rt->component_wise('abs', $rt->binary('-', $color1, $color2, 4, 'float')))};
                            } else {
                                if ($rt->binary('==', $mode, $rt->i(6))) {
                                    @{$middle} = map { $rt->f32($_) } @{($rt->binary('-', $rt->binary('+', $color1, $color2, 4, 'float'), $rt->binary('*', $rt->binary('*', $rt->f(2), $color1, 4, 'float'), $color2, 4, 'float'), 4, 'float'))};
                                } else {
                                    if ($rt->binary('==', $mode, $rt->i(7))) {
                                        @{$middle} = map { $rt->f32($_) } @{((($rt->binary('==', $color2, $rt->construct(4, $rt->f(1)))) ? ($color2) : ($rt->component_wise('min', $rt->binary('/', $rt->binary('*', $color1, $color1, 4, 'float'), $rt->binary('-', $rt->f(1), $color2, 4, 'float'), 4, 'float'), $rt->construct(4, $rt->f(1))))))};
                                    } else {
                                        if ($rt->binary('==', $mode, $rt->i(8))) {
                                            @{$middle} = map { $rt->f32($_) } @{($rt->construct(4, $blendOverlay__float_float->($rt->swizzle($color2, 'r'), $rt->swizzle($color1, 'r')), $blendOverlay__float_float->($rt->swizzle($color2, 'g'), $rt->swizzle($color1, 'g')), $blendOverlay__float_float->($rt->swizzle($color2, 'b'), $rt->swizzle($color1, 'b')), $rt->component_wise('mix', $rt->swizzle($color1, 'a'), $rt->swizzle($color2, 'a'), $rt->f(0.5))))};
                                        } else {
                                            if ($rt->binary('==', $mode, $rt->i(9))) {
                                                @{$middle} = map { $rt->f32($_) } @{($rt->component_wise('max', $color1, $color2))};
                                            } else {
                                                if ($rt->binary('==', $mode, $rt->i(10))) {
                                                    @{$middle} = map { $rt->f32($_) } @{($rt->component_wise('mix', $color1, $color2, $rt->f(0.5)))};
                                                } else {
                                                    if ($rt->binary('==', $mode, $rt->i(11))) {
                                                        @{$middle} = map { $rt->f32($_) } @{($rt->binary('*', $color1, $color2, 4, 'float'))};
                                                    } else {
                                                        if ($rt->binary('==', $mode, $rt->i(12))) {
                                                            @{$middle} = map { $rt->f32($_) } @{($rt->binary('-', $rt->construct(4, $rt->f(1)), $rt->component_wise('abs', $rt->binary('-', $rt->binary('-', $rt->construct(4, $rt->f(1)), $color1, 4, 'float'), $color2, 4, 'float')), 4, 'float'))};
                                                        } else {
                                                            if ($rt->binary('==', $mode, $rt->i(13))) {
                                                                @{$middle} = map { $rt->f32($_) } @{($rt->construct(4, $blendOverlay__float_float->($rt->swizzle($color1, 'r'), $rt->swizzle($color2, 'r')), $blendOverlay__float_float->($rt->swizzle($color1, 'g'), $rt->swizzle($color2, 'g')), $blendOverlay__float_float->($rt->swizzle($color1, 'b'), $rt->swizzle($color2, 'b')), $rt->component_wise('mix', $rt->swizzle($color1, 'a'), $rt->swizzle($color2, 'a'), $rt->f(0.5))))};
                                                            } else {
                                                                if ($rt->binary('==', $mode, $rt->i(14))) {
                                                                    @{$middle} = map { $rt->f32($_) } @{($rt->binary('+', $rt->binary('-', $rt->component_wise('min', $color1, $color2), $rt->component_wise('max', $color1, $color2), 4, 'float'), $rt->construct(4, $rt->f(1)), 4, 'float'))};
                                                                } else {
                                                                    if ($rt->binary('==', $mode, $rt->i(15))) {
                                                                        @{$middle} = map { $rt->f32($_) } @{((($rt->binary('==', $color1, $rt->construct(4, $rt->f(1)))) ? ($color1) : ($rt->component_wise('min', $rt->binary('/', $rt->binary('*', $color2, $color2, 4, 'float'), $rt->binary('-', $rt->f(1), $color1, 4, 'float'), 4, 'float'), $rt->construct(4, $rt->f(1))))))};
                                                                    } else {
                                                                        if ($rt->binary('==', $mode, $rt->i(16))) {
                                                                            @{$middle} = map { $rt->f32($_) } @{($rt->binary('-', $rt->f(1), $rt->binary('*', $rt->binary('-', $rt->f(1), $color1, 4, 'float'), $rt->binary('-', $rt->f(1), $color2, 4, 'float'), 4, 'float'), 4, 'float'))};
                                                                        } else {
                                                                            if ($rt->binary('==', $mode, $rt->i(17))) {
                                                                                @{$middle} = map { $rt->f32($_) } @{($rt->construct(4, $blendSoftLight__float_float->($rt->swizzle($color1, 'r'), $rt->swizzle($color2, 'r')), $blendSoftLight__float_float->($rt->swizzle($color1, 'g'), $rt->swizzle($color2, 'g')), $blendSoftLight__float_float->($rt->swizzle($color1, 'b'), $rt->swizzle($color2, 'b')), $rt->component_wise('mix', $rt->swizzle($color1, 'a'), $rt->swizzle($color2, 'a'), $rt->f(0.5))))};
                                                                            } else {
                                                                                if ($rt->binary('==', $mode, $rt->i(18))) {
                                                                                    @{$middle} = map { $rt->f32($_) } @{($rt->component_wise('max', $rt->binary('-', $rt->binary('+', $color1, $color2, 4, 'float'), $rt->f(1), 4, 'float'), $rt->f(0)))};
                                                                                } else {
                                                                                    if ($rt->binary('==', $mode, $rt->i(1000))) {
                                                                                        $middle = $rt->assign_swizzle($middle, 'rgb', $hsv2rgb__vec3->($rt->construct(3, $rt->swizzle($b, 'r'), $rt->swizzle($a, 'g'), $rt->swizzle($a, 'b'))));
                                                                                    } else {
                                                                                        if ($rt->binary('==', $mode, $rt->i(1001))) {
                                                                                            $middle = $rt->assign_swizzle($middle, 'rgb', $hsv2rgb__vec3->($rt->construct(3, $rt->swizzle($a, 'r'), $rt->swizzle($b, 'g'), $rt->swizzle($b, 'b'))));
                                                                                        } else {
                                                                                            if ($rt->binary('==', $mode, $rt->i(1002))) {
                                                                                                $middle = $rt->assign_swizzle($middle, 'rgb', $hsv2rgb__vec3->($rt->construct(3, $rt->swizzle($a, 'r'), $rt->swizzle($b, 'g'), $rt->swizzle($a, 'b'))));
                                                                                            } else {
                                                                                                if ($rt->binary('==', $mode, $rt->i(1003))) {
                                                                                                    $middle = $rt->assign_swizzle($middle, 'rgb', $hsv2rgb__vec3->($rt->construct(3, $rt->swizzle($b, 'r'), $rt->swizzle($a, 'g'), $rt->swizzle($b, 'b'))));
                                                                                                } else {
                                                                                                    if ($rt->binary('==', $mode, $rt->i(1004))) {
                                                                                                        $middle = $rt->assign_swizzle($middle, 'rgb', $hsv2rgb__vec3->($rt->construct(3, $rt->swizzle($a, 'r'), $rt->swizzle($a, 'g'), $rt->swizzle($b, 'b'))));
                                                                                                    } else {
                                                                                                        if ($rt->binary('==', $mode, $rt->i(1005))) {
                                                                                                            $middle = $rt->assign_swizzle($middle, 'rgb', $hsv2rgb__vec3->($rt->construct(3, $rt->swizzle($b, 'r'), $rt->swizzle($b, 'g'), $rt->swizzle($a, 'b'))));
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if ($rt->binary('>=', $mode, $rt->i(1000))) {
            $middle = $rt->assign_swizzle($middle, 'a', $rt->component_wise('mix', $rt->swizzle($color1, 'a'), $rt->swizzle($color2, 'a'), $rt->f(0.5)));
        }
        if ($rt->binary('==', $factor, $rt->f(0.5))) {
            @{$color} = map { $rt->f32($_) } @{($middle)};
        } else {
            if ($rt->binary('<', $factor, $rt->f(0.5))) {
                $factor = $map__float_float_float_float_float->($amt, $rt->f(0), $rt->f(0.5), $rt->f(0), $rt->f(1));
                @{$color} = map { $rt->f32($_) } @{($rt->component_wise('mix', $color1, $middle, $factor))};
            } else {
                if ($rt->binary('>', $factor, $rt->f(0.5))) {
                    $factor = $map__float_float_float_float_float->($amt, $rt->f(0.5), $rt->f(1), $rt->f(0), $rt->f(1));
                    @{$color} = map { $rt->f32($_) } @{($rt->component_wise('mix', $middle, $color2, $factor))};
                }
            }
        }
        return $rt->swizzle($color, 'rgb');
    };
    $main__void = sub {
        my ($color, $color1, $color2, $globalCoord, $leftColor, $leftLen, $leftLocalUV, $leftUV, $ra, $rb, $rightColor, $rightLen, $rightLocalUV, $rightUV, $st);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $color = $rt->construct(4, $rt->f(0), $rt->f(0), $rt->f(1), $rt->f(1));
        $st = $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float');
        $color1 = $rt->construct(4, 0.0);
        $color2 = $rt->construct(4, 0.0);
        $leftColor = $rt->construct(4, 0.0);
        $leftLen = $rt->f(0.0);
        $leftLocalUV = $rt->construct(2, 0.0);
        $leftUV = $rt->construct(2, 0.0);
        $ra = $rt->f(0.0);
        $rb = $rt->f(0.0);
        $rightColor = $rt->construct(4, 0.0);
        $rightLen = $rt->f(0.0);
        $rightLocalUV = $rt->construct(2, 0.0);
        $rightUV = $rt->construct(2, 0.0);
        if ($rt->binary('==', $_u_blendMode, $rt->i(100))) {
            @{$color} = map { $rt->f32($_) } @{($cloak__vec2->($st))};
        } else {
            $ra = $map__float_float_float_float_float->($_u_refractAAmt, $rt->f(0), $rt->f(100), $rt->f(0), $rt->f(0.125));
            $rb = $map__float_float_float_float_float->($_u_refractBAmt, $rt->f(0), $rt->f(100), $rt->f(0), $rt->f(0.125));
            $leftColor = $rt->texture($_u_inputTex, $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($_u_inputTex)), 2, 'float'));
            $rightColor = $rt->texture($_u_tex, $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($_u_tex)), 2, 'float'));
            $leftUV = $rt->construct(2, $st);
            $rightLen = $rt->binary('+', $rt->length($rt->swizzle($rightColor, 'rgb')), $rt->binary('/', $_u_refractADir, $rt->f(360), 1, 'float'), 1, 'float');
            $leftUV = $rt->assign_swizzle($leftUV, 'x', $rt->binary('+', $rt->swizzle($leftUV, 'x'), $rt->binary('*', $rt->component_wise('cos', $rt->binary('*', $rightLen, $rt->f(6.2831853071800001), 1, 'float')), $ra, 1, 'float'), 1, 'float'));
            $leftUV = $rt->assign_swizzle($leftUV, 'y', $rt->binary('+', $rt->swizzle($leftUV, 'y'), $rt->binary('*', $rt->component_wise('sin', $rt->binary('*', $rightLen, $rt->f(6.2831853071800001), 1, 'float')), $ra, 1, 'float'), 1, 'float'));
            $leftLocalUV = $rt->binary('/', $rt->binary('-', $rt->binary('*', $leftUV, $_u_fullResolution, 2, 'float'), $_u_tileOffset, 2, 'float'), $rt->construct(2, $rt->texture_size($_u_inputTex)), 2, 'float');
            $color1 = $rt->texture($_u_inputTex, $rt->component_wise('fract', $leftLocalUV));
            $rightUV = $rt->construct(2, $st);
            $leftLen = $rt->binary('+', $rt->length($rt->swizzle($leftColor, 'rgb')), $rt->binary('/', $_u_refractBDir, $rt->f(360), 1, 'float'), 1, 'float');
            $rightUV = $rt->assign_swizzle($rightUV, 'x', $rt->binary('+', $rt->swizzle($rightUV, 'x'), $rt->binary('*', $rt->component_wise('cos', $rt->binary('*', $leftLen, $rt->f(6.2831853071800001), 1, 'float')), $rb, 1, 'float'), 1, 'float'));
            $rightUV = $rt->assign_swizzle($rightUV, 'y', $rt->binary('+', $rt->swizzle($rightUV, 'y'), $rt->binary('*', $rt->component_wise('sin', $rt->binary('*', $leftLen, $rt->f(6.2831853071800001), 1, 'float')), $rb, 1, 'float'), 1, 'float'));
            $rightLocalUV = $rt->binary('/', $rt->binary('-', $rt->binary('*', $rightUV, $_u_fullResolution, 2, 'float'), $_u_tileOffset, 2, 'float'), $rt->construct(2, $rt->texture_size($_u_tex)), 2, 'float');
            $color2 = $rt->texture($_u_tex, $rt->component_wise('fract', $rightLocalUV));
            $color = $rt->assign_swizzle($color, 'rgb', $blend__vec4_vec4_int_float->($color1, $color2, $_u_blendMode, $_u_mixAmt));
            $color = $rt->assign_swizzle($color, 'a', $rt->component_wise('max', $rt->swizzle($color1, 'a'), $rt->swizzle($color2, 'a')));
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
