# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($flareAxis__vec2_vec2_float_float, $coreGlow__float, $anamorphicStreak__vec2, $sixPointStar__vec2_float, $haloRainbow__float, $haloBand__float, $circleGhost__float_float, $softCircleGhost__float_float, $ringGhost__float_float, $hexDist__vec2, $hexGhost__vec2_float, $main__void);
    my $_retc;
    my $_u_LENS_TYPE = exists $U->{'LENS_TYPE'} ? $U->{'LENS_TYPE'} : 0;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_brightness = exists $U->{'brightness'} ? $U->{'brightness'} : $rt->f(0.0);
    my $_u_centerX = exists $U->{'centerX'} ? $U->{'centerX'} : $rt->f(0.0);
    my $_u_centerY = exists $U->{'centerY'} ? $U->{'centerY'} : $rt->f(0.0);
    my $_u_tint = exists $U->{'tint'} ? $U->{'tint'} : $rt->construct(3, 0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $flareAxis__vec2_vec2_float_float = sub {
        my ($flarePos, $mirrorPos, $t, $aspectRatio) = @_;
        $flarePos = $rt->copy($flarePos, 'float');
        $mirrorPos = $rt->copy($mirrorPos, 'float');
        my ($a);
        $a = $rt->component_wise('mix', $flarePos, $mirrorPos, $t);
        $a = $rt->assign_swizzle($a, 'x', $rt->binary('*', $rt->swizzle($a, 'x'), $aspectRatio, 1, 'float'));
        return $a;
    };
    $coreGlow__float = sub {
        my ($d) = @_;
        return $rt->binary('+', $rt->binary('*', $rt->component_wise('exp', $rt->binary('*', $rt->binary('*', $rt->unary('-', $d), $d, 1, 'float'), $rt->f(900), 1, 'float')), $rt->f(1.2), 1, 'float'), $rt->binary('*', $rt->component_wise('exp', $rt->binary('*', $rt->unary('-', $d), $rt->f(8), 1, 'float')), $rt->f(0.40000000000000002), 1, 'float'), 1, 'float');
    };
    $anamorphicStreak__vec2 = sub {
        my ($delta) = @_;
        $delta = $rt->copy($delta, 'float');
        return $rt->component_wise('exp', $rt->unary('-', $rt->binary('+', $rt->binary('*', $rt->binary('*', $rt->swizzle($delta, 'y'), $rt->swizzle($delta, 'y'), 1, 'float'), $rt->f(4000), 1, 'float'), $rt->binary('*', $rt->binary('*', $rt->swizzle($delta, 'x'), $rt->swizzle($delta, 'x'), 1, 'float'), $rt->f(18), 1, 'float'), 1, 'float')));
    };
    $sixPointStar__vec2_float = sub {
        my ($delta, $d) = @_;
        $delta = $rt->copy($delta, 'float');
        my ($phi);
        $phi = $rt->component_wise('atan', $rt->swizzle($delta, 'y'), $rt->swizzle($delta, 'x'));
        return $rt->binary('*', $rt->binary('*', $rt->component_wise('pow', $rt->component_wise('max', $rt->f(0), $rt->component_wise('cos', $rt->binary('*', $rt->f(6), $phi, 1, 'float'))), $rt->f(40)), $rt->component_wise('exp', $rt->binary('*', $rt->unary('-', $d), $rt->f(5), 1, 'float')), 1, 'float'), $rt->f(0.5), 1, 'float');
    };
    $haloRainbow__float = sub {
        my ($dc) = @_;
        return $rt->binary('+', $rt->f(0.5), $rt->binary('*', $rt->f(0.5), $rt->component_wise('cos', $rt->binary('*', $rt->f(6.2831853071795862), $rt->binary('+', $rt->binary('*', $dc, $rt->f(10), 1, 'float'), $rt->construct(3, $rt->f(0), $rt->f(0.3333333), $rt->f(0.66666669999999995)), 3, 'float'), 3, 'float')), 3, 'float'), 3, 'float');
    };
    $haloBand__float = sub {
        my ($dc) = @_;
        return $rt->binary('*', $rt->component_wise('exp', $rt->binary('*', $rt->unary('-', $rt->component_wise('abs', $rt->binary('-', $dc, $rt->f(0.28000000000000003), 1, 'float'))), $rt->f(60), 1, 'float')), $rt->f(0.25), 1, 'float');
    };
    $circleGhost__float_float = sub {
        my ($dist, $size) = @_;
        return $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('*', $size, $rt->f(0.59999999999999998), 1, 'float'), $size, $dist), 1, 'float');
    };
    $softCircleGhost__float_float = sub {
        my ($dist, $size) = @_;
        return $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('*', $size, $rt->f(0.29999999999999999), 1, 'float'), $size, $dist), 1, 'float');
    };
    $ringGhost__float_float = sub {
        my ($dist, $size) = @_;
        my ($inner, $outer);
        $outer = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('*', $size, $rt->f(0.59999999999999998), 1, 'float'), $size, $dist), 1, 'float');
        $inner = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('*', $size, $rt->f(0.29999999999999999), 1, 'float'), $rt->binary('*', $size, $rt->f(0.59999999999999998), 1, 'float'), $dist), 1, 'float');
        return $rt->binary('-', $outer, $inner, 1, 'float');
    };
    $hexDist__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($a0, $a1, $a2, $d0, $d1, $d2);
        $a0 = $rt->construct(2, $rt->f(1), $rt->f(0));
        $a1 = $rt->construct(2, $rt->f(0.5), $rt->f(0.86602540380000004));
        $a2 = $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(0.86602540380000004));
        $d0 = $rt->component_wise('abs', $rt->dot($p, $a0));
        $d1 = $rt->component_wise('abs', $rt->dot($p, $a1));
        $d2 = $rt->component_wise('abs', $rt->dot($p, $a2));
        return $rt->component_wise('max', $d0, $rt->component_wise('max', $d1, $d2));
    };
    $hexGhost__vec2_float = sub {
        my ($delta, $size) = @_;
        $delta = $rt->copy($delta, 'float');
        return $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('*', $size, $rt->f(0.59999999999999998), 1, 'float'), $size, $hexDist__vec2->($delta)), 1, 'float');
    };
    $main__void = sub {
        my ($_g, $aFlare, $aMirror, $aspectRatio, $d0, $dc, $delta0, $flare, $flarePos, $globalCoord, $localUV, $mirrorPos, $outFlare, $p, $src, $streakVal, $uv);
        $aspectRatio = $rt->binary('/', $rt->swizzle($_u_fullResolution, 'x'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float');
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $uv = $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float');
        $localUV = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        $src = $rt->texture($_u_inputTex, $localUV);
        $flarePos = $rt->construct(2, $_u_centerX, $_u_centerY);
        $mirrorPos = $rt->binary('-', $rt->construct(2, $rt->f(1)), $flarePos, 2, 'float');
        $p = $uv;
        $p = $rt->assign_swizzle($p, 'x', $rt->binary('*', $rt->swizzle($p, 'x'), $aspectRatio, 1, 'float'));
        $aFlare = $flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0), $aspectRatio);
        $delta0 = $rt->binary('-', $p, $aFlare, 2, 'float');
        $d0 = $rt->length($delta0);
        $flare = $rt->construct(3, $rt->f(0));
        @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->construct(3, $coreGlow__float->($d0)), 3, 'float'))};
        $streakVal = $anamorphicStreak__vec2->($delta0);
        if ($rt->binary('==', $_u_LENS_TYPE, $rt->i(3))) {
            $streakVal = $rt->binary('*', $streakVal, $rt->f(2), 1, 'float');
        }
        @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->construct(3, $streakVal), 3, 'float'))};
        if ((($rt->binary('==', $_u_LENS_TYPE, $rt->i(0))) || ($rt->binary('==', $_u_LENS_TYPE, $rt->i(3))) ? 1 : 0)) {
            @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->construct(3, $sixPointStar__vec2_float->($delta0, $d0)), 3, 'float'))};
        }
        $aMirror = $flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(1), $aspectRatio);
        $dc = $rt->length($rt->binary('-', $p, $aMirror, 2, 'float'));
        @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $haloRainbow__float->($dc), $haloBand__float->($dc), 3, 'float'), 3, 'float'))};
        $_g = $rt->construct(2, $rt->f(0));
        if ((($rt->binary('==', $_u_LENS_TYPE, $rt->i(0))) || ($rt->binary('==', $_u_LENS_TYPE, $rt->i(3))) ? 1 : 0)) {
            @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.25), $aspectRatio))};
            @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(1), $rt->f(0.84999999999999998), $rt->f(0.59999999999999998)), $circleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.059999999999999998)), 3, 'float'), $rt->f(0.34999999999999998), 3, 'float'), 3, 'float'))};
            @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.40000000000000002), $aspectRatio))};
            @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.40000000000000002), $rt->f(0.90000000000000002), $rt->f(0.84999999999999998)), $circleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.10000000000000001)), 3, 'float'), $rt->f(0.25), 3, 'float'), 3, 'float'))};
            @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.59999999999999998), $aspectRatio))};
            @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.65000000000000002), $rt->f(0.40000000000000002), $rt->f(0.94999999999999996)), $circleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.044999999999999998)), 3, 'float'), $rt->f(0.45000000000000001), 3, 'float'), 3, 'float'))};
            @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.84999999999999998), $aspectRatio))};
            @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.45000000000000001), $rt->f(0.90000000000000002), $rt->f(0.5)), $circleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.14000000000000001)), 3, 'float'), $rt->f(0.17999999999999999), 3, 'float'), 3, 'float'))};
            @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(1.2), $aspectRatio))};
            @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(1), $rt->f(0.55000000000000004), $rt->f(0.20000000000000001)), $circleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.080000000000000002)), 3, 'float'), $rt->f(0.29999999999999999), 3, 'float'), 3, 'float'))};
            @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(1.55), $aspectRatio))};
            @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.40000000000000002), $rt->f(0.55000000000000004), $rt->f(1)), $ringGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.20000000000000001)), 3, 'float'), $rt->f(0.12), 3, 'float'), 3, 'float'))};
        } else {
            if ($rt->binary('==', $_u_LENS_TYPE, $rt->i(1))) {
                @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.29999999999999999), $aspectRatio))};
                @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(1), $rt->f(0.80000000000000004), $rt->f(0.55000000000000004)), $hexGhost__vec2_float->($rt->binary('-', $p, $_g, 2, 'float'), $rt->f(0.040000000000000001)), 3, 'float'), $rt->f(0.34999999999999998), 3, 'float'), 3, 'float'))};
                @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.55000000000000004), $aspectRatio))};
                @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.84999999999999998), $rt->f(0.84999999999999998), $rt->f(0.92000000000000004)), $hexGhost__vec2_float->($rt->binary('-', $p, $_g, 2, 'float'), $rt->f(0.055)), 3, 'float'), $rt->f(0.29999999999999999), 3, 'float'), 3, 'float'))};
                @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.80000000000000004), $aspectRatio))};
                @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.94999999999999996), $rt->f(0.69999999999999996), $rt->f(0.5)), $hexGhost__vec2_float->($rt->binary('-', $p, $_g, 2, 'float'), $rt->f(0.065000000000000002)), 3, 'float'), $rt->f(0.25), 3, 'float'), 3, 'float'))};
                @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(1.3), $aspectRatio))};
                @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.80000000000000004), $rt->f(0.84999999999999998), $rt->f(0.94999999999999996)), $hexGhost__vec2_float->($rt->binary('-', $p, $_g, 2, 'float'), $rt->f(0.080000000000000002)), 3, 'float'), $rt->f(0.20000000000000001), 3, 'float'), 3, 'float'))};
            } else {
                @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.45000000000000001), $aspectRatio))};
                @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.92000000000000004), $rt->f(0.84999999999999998), $rt->f(0.78000000000000003)), $softCircleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.12)), 3, 'float'), $rt->f(0.25), 3, 'float'), 3, 'float'))};
                @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(0.90000000000000002), $aspectRatio))};
                @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.84999999999999998), $rt->f(0.88), $rt->f(0.94999999999999996)), $softCircleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.16)), 3, 'float'), $rt->f(0.20000000000000001), 3, 'float'), 3, 'float'))};
                @{$_g} = map { $rt->f32($_) } @{($flareAxis__vec2_vec2_float_float->($flarePos, $mirrorPos, $rt->f(1.5), $aspectRatio))};
                @{$flare} = map { $rt->f32($_) } @{($rt->binary('+', $flare, $rt->binary('*', $rt->binary('*', $rt->construct(3, $rt->f(0.94999999999999996), $rt->f(0.88), $rt->f(0.80000000000000004)), $softCircleGhost__float_float->($rt->length($rt->binary('-', $p, $_g, 2, 'float')), $rt->f(0.20000000000000001)), 3, 'float'), $rt->f(0.14999999999999999), 3, 'float'), 3, 'float'))};
            }
        }
        $outFlare = $rt->binary('*', $rt->binary('*', $flare, $_u_tint, 3, 'float'), $rt->binary('/', $_u_brightness, $rt->f(100), 1, 'float'), 3, 'float');
        if ($rt->binary('==', $_u_LENS_TYPE, $rt->i(3))) {
            @{$outFlare} = map { $rt->f32($_) } @{($rt->binary('*', $outFlare, $rt->construct(3, $rt->f(0.90000000000000002), $rt->f(0.94999999999999996), $rt->f(1.1000000000000001)), 3, 'float'))};
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->component_wise('clamp', $rt->binary('+', $rt->swizzle($src, 'rgb'), $outFlare, 3, 'float'), $rt->f(0), $rt->f(1)), $rt->swizzle($src, 'a')))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
