# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($polygonShape__vec2_int, $smod__vec2_float, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_shape = exists $U->{'shape'} ? $U->{'shape'} : 0;
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_rotation = exists $U->{'rotation'} ? $U->{'rotation'} : $rt->f(0.0);
    my $_u_scale = exists $U->{'scale'} ? $U->{'scale'} : $rt->f(0.0);
    my $_u_center = exists $U->{'center'} ? $U->{'center'} : $rt->f(0.0);
    my $_u_aspectLens = exists $U->{'aspectLens'} ? $U->{'aspectLens'} : 0;
    my $_u_antialias = exists $U->{'antialias'} ? $U->{'antialias'} : 0;
    $g->{fragColor} = $rt->construct(4, 0.0);
    $g->{PI} = $rt->f(3.1415926535900001);
    $g->{TAU} = $rt->f(6.2831853071800001);
    $polygonShape__vec2_int = sub {
        my ($uv, $sides) = @_;
        $uv = $rt->copy($uv, 'float');
        my ($a, $r);
        $a = $rt->binary('+', $rt->component_wise('atan', $rt->swizzle($uv, 'x'), $rt->swizzle($uv, 'y')), $g->{PI}, 1, 'float');
        $r = $rt->binary('/', $g->{TAU}, $rt->construct(1, $sides), 1, 'float');
        return $rt->binary('*', $rt->component_wise('cos', $rt->binary('-', $rt->binary('*', $rt->component_wise('floor', $rt->binary('+', $rt->f(0.5), $rt->binary('/', $a, $r, 1, 'float'), 1, 'float')), $r, 1, 'float'), $a, 1, 'float')), $rt->length($uv), 1, 'float');
    };
    $smod__vec2_float = sub {
        my ($v, $m) = @_;
        $v = $rt->copy($v, 'float');
        return $rt->binary('*', $m, $rt->binary('-', $rt->binary('-', $rt->f(0.75), $rt->component_wise('abs', $rt->binary('-', $rt->component_wise('fract', $v), $rt->f(0.5), 2, 'float')), 2, 'float'), $rt->f(0.25), 2, 'float'), 2, 'float');
    };
    $main__void = sub {
        my ($a, $amt, $aspectRatio, $centerMask, $centered, $color, $dx, $dy, $fullRes, $p, $r, $texSize, $tileDims, $tunnelCoords, $uv);
        $texSize = $rt->texture_size($_u_inputTex);
        $tileDims = $rt->construct(2, $texSize);
        $fullRes = (($rt->binary('>', $rt->swizzle($_u_fullResolution, 'x'), $rt->f(0))) ? ($_u_fullResolution) : ($tileDims));
        $uv = $rt->binary('/', $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float'), $fullRes, 2, 'float');
        $centered = $rt->binary('-', $uv, $rt->f(0.5), 2, 'float');
        $aspectRatio = $rt->binary('/', $rt->swizzle($fullRes, 'x'), $rt->swizzle($fullRes, 'y'), 1, 'float');
        if ($_u_aspectLens) {
            $centered = $rt->assign_swizzle($centered, 'x', $rt->binary('*', $rt->swizzle($centered, 'x'), $aspectRatio, 1, 'float'));
        }
        $a = $rt->component_wise('atan', $rt->swizzle($centered, 'y'), $rt->swizzle($centered, 'x'));
        $r = $rt->f(0.0);
        $p = $rt->construct(2, 0.0);
        if ($rt->binary('==', $_u_shape, $rt->i(0))) {
            $r = $rt->length($centered);
        } else {
            if ($rt->binary('==', $_u_shape, $rt->i(1))) {
                $r = $polygonShape__vec2_int->($rt->binary('*', $centered, $rt->f(2), 2, 'float'), $rt->i(3));
            } else {
                if ($rt->binary('==', $_u_shape, $rt->i(2))) {
                    $p = $rt->binary('*', $rt->binary('*', $rt->binary('*', $rt->binary('*', $rt->binary('*', $rt->binary('*', $rt->binary('*', $centered, $centered, 2, 'float'), $centered, 2, 'float'), $centered, 2, 'float'), $centered, 2, 'float'), $centered, 2, 'float'), $centered, 2, 'float'), $centered, 2, 'float');
                    $r = $rt->component_wise('pow', $rt->binary('+', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'y'), 1, 'float'), $rt->binary('/', $rt->f(1), $rt->f(8), 1, 'float'));
                } else {
                    if ($rt->binary('==', $_u_shape, $rt->i(3))) {
                        $r = $polygonShape__vec2_int->($rt->binary('*', $centered, $rt->f(2), 2, 'float'), $rt->i(4));
                    } else {
                        if ($rt->binary('==', $_u_shape, $rt->i(4))) {
                            $r = $polygonShape__vec2_int->($rt->binary('*', $centered, $rt->f(2), 2, 'float'), $rt->i(6));
                        } else {
                            $r = $polygonShape__vec2_int->($rt->binary('*', $centered, $rt->f(2), 2, 'float'), $rt->i(8));
                        }
                    }
                }
            }
        }
        $r = $rt->binary('-', $r, $rt->binary('*', $_u_scale, $rt->f(0.14999999999999999), 1, 'float'), 1, 'float');
        $tunnelCoords = $smod__vec2_float->($rt->construct(2, $rt->binary('+', $rt->binary('/', $rt->f(0.29999999999999999), $r, 1, 'float'), $rt->binary('*', $_u_time, $_u_speed, 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('/', $a, $g->{PI}, 1, 'float'), $rt->binary('*', $_u_time, $_u_rotation, 1, 'float'), 1, 'float')), $rt->f(1));
        $color = $rt->construct(4, 0.0);
        $dx = $rt->construct(2, 0.0);
        $dy = $rt->construct(2, 0.0);
        if ($_u_antialias) {
            $dx = $rt->dFdx($tunnelCoords);
            $dy = $rt->dFdy($tunnelCoords);
            @{$color} = map { $rt->f32($_) } @{($rt->construct(4, $rt->f(0)))};
            @{$color} = map { $rt->f32($_) } @{($rt->binary('+', $color, $rt->texture($_u_inputTex, $rt->binary('+', $rt->binary('+', $tunnelCoords, $rt->binary('*', $dx, $rt->unary('-', $rt->f(0.375)), 2, 'float'), 2, 'float'), $rt->binary('*', $dy, $rt->unary('-', $rt->f(0.125)), 2, 'float'), 2, 'float')), 4, 'float'))};
            @{$color} = map { $rt->f32($_) } @{($rt->binary('+', $color, $rt->texture($_u_inputTex, $rt->binary('+', $rt->binary('+', $tunnelCoords, $rt->binary('*', $dx, $rt->f(0.125), 2, 'float'), 2, 'float'), $rt->binary('*', $dy, $rt->unary('-', $rt->f(0.375)), 2, 'float'), 2, 'float')), 4, 'float'))};
            @{$color} = map { $rt->f32($_) } @{($rt->binary('+', $color, $rt->texture($_u_inputTex, $rt->binary('+', $rt->binary('+', $tunnelCoords, $rt->binary('*', $dx, $rt->f(0.375), 2, 'float'), 2, 'float'), $rt->binary('*', $dy, $rt->f(0.125), 2, 'float'), 2, 'float')), 4, 'float'))};
            @{$color} = map { $rt->f32($_) } @{($rt->binary('+', $color, $rt->texture($_u_inputTex, $rt->binary('+', $rt->binary('+', $tunnelCoords, $rt->binary('*', $dx, $rt->unary('-', $rt->f(0.125)), 2, 'float'), 2, 'float'), $rt->binary('*', $dy, $rt->f(0.375), 2, 'float'), 2, 'float')), 4, 'float'))};
            @{$color} = map { $rt->f32($_) } @{($rt->binary('*', $color, $rt->f(0.25), 4, 'float'))};
        } else {
            @{$color} = map { $rt->f32($_) } @{($rt->texture($_u_inputTex, $tunnelCoords))};
        }
        $amt = $rt->f(0.0);
        $centerMask = $rt->f(0.0);
        if ($rt->binary('!=', $_u_center, $rt->f(0))) {
            $centerMask = $rt->component_wise('smoothstep', $rt->f(0), $rt->f(0.5), $r);
            $amt = $rt->binary('/', $_u_center, $rt->f(100), 1, 'float');
            if ($rt->binary('<', $amt, $rt->f(0))) {
                $color = $rt->assign_swizzle($color, 'rgb', $rt->binary('*', $rt->swizzle($color, 'rgb'), $rt->component_wise('mix', $rt->f(1), $centerMask, $rt->unary('-', $amt)), 3, 'float'));
            } else {
                $color = $rt->assign_swizzle($color, 'rgb', $rt->component_wise('mix', $rt->swizzle($color, 'rgb'), $rt->construct(3, $rt->f(1)), $rt->binary('*', $rt->binary('-', $rt->f(1), $centerMask, 1, 'float'), $amt, 1, 'float')));
            }
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 1, output_names => ['fragColor'] };
