# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash12__vec2, $lum__vec3, $vnoise__vec2, $fbm__vec2, $lumGradient__vec2, $tonemap2__float_vec3_vec3, $rotate2D__vec2_float, $dirAngle__int, $strokeField__vec2_float_float, $main__void);
    my $_retc;
    my $_u_MODE = exists $U->{'MODE'} ? $U->{'MODE'} : 0;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_strokeLength = exists $U->{'strokeLength'} ? $U->{'strokeLength'} : $rt->f(0.0);
    my $_u_direction = exists $U->{'direction'} ? $U->{'direction'} : 0;
    my $_u_balance = exists $U->{'balance'} ? $U->{'balance'} : $rt->f(0.0);
    my $_u_pressure = exists $U->{'pressure'} ? $U->{'pressure'} : $rt->f(0.0);
    my $_u_inkColor = exists $U->{'inkColor'} ? $U->{'inkColor'} : $rt->construct(3, 0.0);
    my $_u_paperColor = exists $U->{'paperColor'} ? $U->{'paperColor'} : $rt->construct(3, 0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $hash12__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($p3);
        $p3 = $rt->component_wise('fract', $rt->binary('*', $rt->construct(3, $rt->swizzle($p, 'xyx')), $rt->f(0.1031), 3, 'float'));
        @{$p3} = map { $rt->f32($_) } @{($rt->binary('+', $p3, $rt->dot($p3, $rt->binary('+', $rt->swizzle($p3, 'yzx'), $rt->f(33.329999999999998), 3, 'float')), 3, 'float'))};
        return $rt->component_wise('fract', $rt->binary('*', $rt->binary('+', $rt->swizzle($p3, 'x'), $rt->swizzle($p3, 'y'), 1, 'float'), $rt->swizzle($p3, 'z'), 1, 'float'));
    };
    $lum__vec3 = sub {
        my ($c) = @_;
        $c = $rt->copy($c, 'float');
        return $rt->dot($c, $rt->construct(3, $rt->f(0.21260000000000001), $rt->f(0.71519999999999995), $rt->f(0.0722)));
    };
    $vnoise__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($f, $i, $u);
        $i = $rt->component_wise('floor', $p);
        $f = $rt->component_wise('fract', $p);
        $u = $rt->binary('*', $rt->binary('*', $f, $f, 2, 'float'), $rt->binary('-', $rt->f(3), $rt->binary('*', $rt->f(2), $f, 2, 'float'), 2, 'float'), 2, 'float');
        return $rt->component_wise('mix', $rt->component_wise('mix', $hash12__vec2->($i), $hash12__vec2->($rt->binary('+', $i, $rt->construct(2, $rt->f(1), $rt->f(0)), 2, 'float')), $rt->swizzle($u, 'x')), $rt->component_wise('mix', $hash12__vec2->($rt->binary('+', $i, $rt->construct(2, $rt->f(0), $rt->f(1)), 2, 'float')), $hash12__vec2->($rt->binary('+', $i, $rt->construct(2, $rt->f(1), $rt->f(1)), 2, 'float')), $rt->swizzle($u, 'x')), $rt->swizzle($u, 'y'));
    };
    $fbm__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($_for0_first, $a, $i, $v);
        $v = $rt->f(0);
        $a = $rt->f(0.5);
        $i = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $i, $rt->i(5)))) {
                last;
            }
            $v = $rt->binary('+', $v, $rt->binary('*', $a, $vnoise__vec2->($p), 1, 'float'), 1, 'float');
            @{$p} = map { $rt->f32($_) } @{($rt->binary('*', $p, $rt->f(2.0299999999999998), 2, 'float'))};
            $a = $rt->binary('*', $a, $rt->f(0.5), 1, 'float');
        }
        return $v;
    };
    $lumGradient__vec2 = sub {
        my ($uv) = @_;
        $uv = $rt->copy($uv, 'float');
        my ($b, $bl, $br, $l, $px, $r, $t, $tl, $tr);
        $px = $rt->binary('/', $rt->f(1), $_u_resolution, 2, 'float');
        $tl = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->unary('-', $rt->f(1)), $rt->f(1)), 2, 'float'), 2, 'float')), 'rgb'));
        $l = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->unary('-', $rt->f(1)), $rt->f(0)), 2, 'float'), 2, 'float')), 'rgb'));
        $bl = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->unary('-', $rt->f(1)), $rt->unary('-', $rt->f(1))), 2, 'float'), 2, 'float')), 'rgb'));
        $tr = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->f(1), $rt->f(1)), 2, 'float'), 2, 'float')), 'rgb'));
        $r = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->f(1), $rt->f(0)), 2, 'float'), 2, 'float')), 'rgb'));
        $br = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->f(1), $rt->unary('-', $rt->f(1))), 2, 'float'), 2, 'float')), 'rgb'));
        $t = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->f(0), $rt->f(1)), 2, 'float'), 2, 'float')), 'rgb'));
        $b = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->binary('*', $px, $rt->construct(2, $rt->f(0), $rt->unary('-', $rt->f(1))), 2, 'float'), 2, 'float')), 'rgb'));
        return $rt->construct(2, $rt->binary('-', $rt->binary('-', $rt->binary('-', $rt->binary('+', $rt->binary('+', $tr, $rt->binary('*', $rt->f(2), $r, 1, 'float'), 1, 'float'), $br, 1, 'float'), $tl, 1, 'float'), $rt->binary('*', $rt->f(2), $l, 1, 'float'), 1, 'float'), $bl, 1, 'float'), $rt->binary('-', $rt->binary('-', $rt->binary('-', $rt->binary('+', $rt->binary('+', $tl, $rt->binary('*', $rt->f(2), $t, 1, 'float'), 1, 'float'), $tr, 1, 'float'), $bl, 1, 'float'), $rt->binary('*', $rt->f(2), $b, 1, 'float'), 1, 'float'), $br, 1, 'float'));
    };
    $tonemap2__float_vec3_vec3 = sub {
        my ($t, $ink, $paper) = @_;
        $ink = $rt->copy($ink, 'float');
        $paper = $rt->copy($paper, 'float');
        return $rt->component_wise('mix', $ink, $paper, $rt->component_wise('clamp', $t, $rt->f(0), $rt->f(1)));
    };
    $rotate2D__vec2_float = sub {
        my ($v, $angleDeg) = @_;
        $v = $rt->copy($v, 'float');
        my ($a, $co, $si);
        $a = $rt->component_wise('radians', $angleDeg);
        $co = $rt->component_wise('cos', $a);
        $si = $rt->component_wise('sin', $a);
        return $rt->matrix_mult($rt->construct(4, $co, $rt->unary('-', $si), $si, $co), $v, 2);
    };
    $dirAngle__int = sub {
        my ($d) = @_;
        if ($rt->binary('==', $d, $rt->i(1))) {
            return $rt->f(0);
        }
        if ($rt->binary('==', $d, $rt->i(2))) {
            return $rt->f(135);
        }
        if ($rt->binary('==', $d, $rt->i(3))) {
            return $rt->f(90);
        }
        return $rt->f(45);
    };
    $strokeField__vec2_float_float = sub {
        my ($gc, $angleDeg, $stretchAmt) = @_;
        $gc = $rt->copy($gc, 'float');
        my ($p);
        $p = $rt->binary('*', $rotate2D__vec2_float->($gc, $angleDeg), $rt->construct(2, $rt->binary('/', $rt->f(1), $stretchAmt, 1, 'float'), $rt->f(0.90000000000000002)), 2, 'float');
        return $vnoise__vec2->($p);
    };
    $main__void = sub {
        my ($aa, $band1, $band2, $band3, $bgGate, $bgMask, $coverage, $darkGain, $darkness, $edgeAngle, $edgeBoost, $f0, $f1, $f2, $fgGate, $fgMask, $gc, $grad, $gradMag, $inkC, $inkMask, $level, $midGray, $outColor, $pb, $rough, $s, $s2, $s45a, $s45b, $sBg, $sCombined, $sEdge, $shadow, $src, $stretchAmt, $strokeMask, $t, $texture2, $theta, $toneGate, $uv);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        $src = $rt->texture($_u_inputTex, $uv);
        $gc = $rt->binary('+', $rt->component_wise('floor', $rt->swizzle($ctx->{frag_coord}, 'xy')), $_u_tileOffset, 2, 'float');
        $theta = $dirAngle__int->($_u_direction);
        $stretchAmt = $rt->component_wise('mix', $rt->f(4), $rt->f(40), $rt->binary('/', $_u_strokeLength, $rt->f(100), 1, 'float'));
        $t = $rt->binary('+', $lum__vec3->($rt->swizzle($src, 'rgb')), $rt->binary('/', $rt->binary('-', $_u_balance, $rt->f(50), 1, 'float'), $rt->f(100), 1, 'float'), 1, 'float');
        $pb = $rt->binary('/', $rt->binary('-', $_u_pressure, $rt->f(50), 1, 'float'), $rt->f(100), 1, 'float');
        $s = $strokeField__vec2_float_float->($gc, $theta, $stretchAmt);
        $outColor = $rt->construct(3, 0.0);
        $aa = $rt->f(0.0);
        $band1 = $rt->f(0.0);
        $band2 = $rt->f(0.0);
        $band3 = $rt->f(0.0);
        $bgGate = $rt->f(0.0);
        $bgMask = $rt->f(0.0);
        $coverage = $rt->f(0.0);
        $darkGain = $rt->f(0.0);
        $darkness = $rt->f(0.0);
        $edgeAngle = $rt->f(0.0);
        $edgeBoost = $rt->f(0.0);
        $f0 = $rt->f(0.0);
        $f1 = $rt->f(0.0);
        $f2 = $rt->f(0.0);
        $fgGate = $rt->f(0.0);
        $fgMask = $rt->f(0.0);
        $grad = $rt->construct(2, 0.0);
        $gradMag = $rt->f(0.0);
        $inkC = $rt->construct(3, 0.0);
        $inkMask = $rt->f(0.0);
        $level = $rt->f(0.0);
        $midGray = $rt->construct(3, 0.0);
        $rough = $rt->f(0.0);
        $s2 = $rt->f(0.0);
        $s45a = $rt->f(0.0);
        $s45b = $rt->f(0.0);
        $sBg = $rt->f(0.0);
        $sCombined = $rt->f(0.0);
        $sEdge = $rt->f(0.0);
        $shadow = $rt->f(0.0);
        $strokeMask = $rt->f(0.0);
        $texture2 = $rt->f(0.0);
        $toneGate = $rt->f(0.0);
        if ($rt->binary('==', $_u_MODE, $rt->i(0))) {
            $inkMask = $rt->component_wise('step', $s, $rt->component_wise('clamp', $rt->binary('+', $rt->binary('-', $rt->f(1), $t, 1, 'float'), $rt->binary('*', $pb, $rt->f(0.29999999999999999), 1, 'float'), 1, 'float'), $rt->f(0), $rt->f(1)));
            @{$outColor} = map { $rt->f32($_) } @{($tonemap2__float_vec3_vec3->($rt->binary('-', $rt->f(1), $inkMask, 1, 'float'), $_u_inkColor, $_u_paperColor))};
        } else {
            if ($rt->binary('==', $_u_MODE, $rt->i(1))) {
                $s2 = $strokeField__vec2_float_float->($rt->binary('+', $rt->binary('*', $gc, $rt->f(2), 2, 'float'), $rt->f(91.700000000000003), 2, 'float'), $theta, $rt->binary('*', $stretchAmt, $rt->f(0.5), 1, 'float'));
                $rough = $rt->binary('+', $rt->binary('*', $s, $rt->f(0.59999999999999998), 1, 'float'), $rt->binary('*', $s2, $rt->f(0.40000000000000002), 1, 'float'), 1, 'float');
                $shadow = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->f(0.14999999999999999), $rt->f(0.55000000000000004), $t), 1, 'float');
                $coverage = $rt->component_wise('clamp', $rt->binary('+', $shadow, $rt->binary('*', $pb, $rt->f(0.5), 1, 'float'), 1, 'float'), $rt->f(0), $rt->f(1));
                $inkMask = $rt->component_wise('step', $rt->binary('-', $rt->f(1), $coverage, 1, 'float'), $rough);
                $darkness = $rt->component_wise('mix', $rt->f(0.55000000000000004), $rt->f(1), $rt->binary('/', $_u_pressure, $rt->f(100), 1, 'float'));
                $inkC = $rt->component_wise('mix', $_u_paperColor, $_u_inkColor, $darkness);
                @{$outColor} = map { $rt->f32($_) } @{($rt->component_wise('mix', $_u_paperColor, $inkC, $inkMask))};
            } else {
                if ($rt->binary('==', $_u_MODE, $rt->i(2))) {
                    $midGray = $rt->component_wise('mix', $_u_inkColor, $_u_paperColor, $rt->f(0.5));
                    $sBg = $strokeField__vec2_float_float->($gc, $rt->binary('+', $theta, $rt->f(90), 1, 'float'), $stretchAmt);
                    $aa = $rt->component_wise('mix', $rt->f(0.40000000000000002), $rt->f(0.040000000000000001), $rt->binary('/', $_u_pressure, $rt->f(100), 1, 'float'));
                    $fgGate = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('-', $rt->f(0.40000000000000002), $aa, 1, 'float'), $rt->binary('+', $rt->f(0.40000000000000002), $aa, 1, 'float'), $t), 1, 'float');
                    $fgMask = $rt->component_wise('step', $rt->binary('-', $rt->f(1), $fgGate, 1, 'float'), $s);
                    $bgGate = $rt->component_wise('smoothstep', $rt->binary('-', $rt->f(0.59999999999999998), $aa, 1, 'float'), $rt->binary('+', $rt->f(0.59999999999999998), $aa, 1, 'float'), $t);
                    $bgMask = $rt->component_wise('step', $rt->binary('-', $rt->f(1), $bgGate, 1, 'float'), $sBg);
                    @{$outColor} = map { $rt->f32($_) } @{($midGray)};
                    @{$outColor} = map { $rt->f32($_) } @{($rt->component_wise('mix', $outColor, $_u_inkColor, $fgMask))};
                    @{$outColor} = map { $rt->f32($_) } @{($rt->component_wise('mix', $outColor, $_u_paperColor, $bgMask))};
                } else {
                    if ($rt->binary('==', $_u_MODE, $rt->i(3))) {
                        $toneGate = $rt->component_wise('smoothstep', $rt->f(0.29999999999999999), $rt->f(0.69999999999999996), $t);
                        $texture2 = $rt->component_wise('mix', $s, $fbm__vec2->($rt->binary('+', $rt->binary('/', $gc, $rt->binary('*', $stretchAmt, $rt->f(0.59999999999999998), 1, 'float'), 2, 'float'), $rt->f(41), 2, 'float')), $rt->f(0.5));
                        $level = $rt->component_wise('mix', $texture2, $toneGate, $rt->component_wise('abs', $rt->binary('-', $rt->binary('*', $toneGate, $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float')));
                        $level = $rt->component_wise('clamp', $rt->binary('+', $level, $rt->binary('*', $pb, $rt->f(0.14999999999999999), 1, 'float'), 1, 'float'), $rt->f(0), $rt->f(1));
                        @{$outColor} = map { $rt->f32($_) } @{($tonemap2__float_vec3_vec3->($level, $_u_inkColor, $_u_paperColor))};
                    } else {
                        if ($rt->binary('==', $_u_MODE, $rt->i(4))) {
                            $s45a = $strokeField__vec2_float_float->($gc, $rt->binary('+', $theta, $rt->f(45), 1, 'float'), $stretchAmt);
                            $s45b = $strokeField__vec2_float_float->($gc, $rt->binary('-', $theta, $rt->f(45), 1, 'float'), $stretchAmt);
                            $band1 = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->f(0.65000000000000002), $rt->f(0.84999999999999998), $t), 1, 'float');
                            $band2 = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->f(0.34999999999999998), $rt->f(0.55000000000000004), $t), 1, 'float');
                            $band3 = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->f(0.050000000000000003), $rt->f(0.25), $t), 1, 'float');
                            $darkGain = $rt->component_wise('mix', $rt->f(0.25), $rt->f(1), $rt->binary('/', $_u_pressure, $rt->f(100), 1, 'float'));
                            $f0 = $rt->binary('-', $rt->f(1), $rt->binary('*', $rt->binary('*', $band1, $darkGain, 1, 'float'), $rt->binary('-', $rt->f(1), $s, 1, 'float'), 1, 'float'), 1, 'float');
                            $f1 = $rt->binary('-', $rt->f(1), $rt->binary('*', $rt->binary('*', $band2, $darkGain, 1, 'float'), $rt->binary('-', $rt->f(1), $s45a, 1, 'float'), 1, 'float'), 1, 'float');
                            $f2 = $rt->binary('-', $rt->f(1), $rt->binary('*', $rt->binary('*', $band3, $darkGain, 1, 'float'), $rt->binary('-', $rt->f(1), $s45b, 1, 'float'), 1, 'float'), 1, 'float');
                            @{$outColor} = map { $rt->f32($_) } @{($rt->component_wise('clamp', $rt->binary('*', $rt->binary('*', $rt->binary('*', $rt->swizzle($src, 'rgb'), $f0, 3, 'float'), $f1, 3, 'float'), $f2, 3, 'float'), $rt->f(0), $rt->f(1)))};
                        } else {
                            $grad = $lumGradient__vec2->($uv);
                            $gradMag = $rt->length($grad);
                            $edgeAngle = $rt->binary('+', $rt->component_wise('degrees', $rt->component_wise('atan', $rt->swizzle($grad, 'y'), $rt->swizzle($grad, 'x'))), $rt->f(90), 1, 'float');
                            $sEdge = $strokeField__vec2_float_float->($gc, $edgeAngle, $stretchAmt);
                            $edgeBoost = $rt->component_wise('clamp', $rt->binary('*', $gradMag, $rt->f(3), 1, 'float'), $rt->f(0), $rt->f(1));
                            $sCombined = $rt->component_wise('mix', $s, $sEdge, $edgeBoost);
                            $coverage = $rt->component_wise('clamp', $rt->binary('+', $rt->binary('-', $rt->f(1), $t, 1, 'float'), $rt->binary('*', $pb, $rt->f(0.40000000000000002), 1, 'float'), 1, 'float'), $rt->f(0), $rt->f(1));
                            $strokeMask = $rt->component_wise('step', $rt->binary('-', $rt->f(1), $coverage, 1, 'float'), $sCombined);
                            @{$outColor} = map { $rt->f32($_) } @{($rt->component_wise('mix', $_u_paperColor, $rt->swizzle($src, 'rgb'), $strokeMask))};
                        }
                    }
                }
            }
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->component_wise('clamp', $outColor, $rt->f(0), $rt->f(1)), $rt->swizzle($src, 'a')))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
