# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($srgbToLinear__float, $srgbToLinear__vec3, $cubeRoot__float, $oklabLComponent__vec3, $valueMapComponent__vec4, $main__void);
    my $_retc;
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    $g->{fragColor} = $rt->construct(4, 0.0);
    $srgbToLinear__float = sub {
        my ($value) = @_;
        return (($rt->binary('<=', $value, $rt->f(0.04045))) ? ($rt->binary('/', $value, $rt->f(12.92), 1, 'float')) : ($rt->component_wise('pow', $rt->binary('/', $rt->binary('+', $value, $rt->f(0.055), 1, 'float'), $rt->f(1.0549999999999999), 1, 'float'), $rt->f(2.3999999999999999))));
    };
    $srgbToLinear__vec3 = sub {
        my ($value) = @_;
        $value = $rt->copy($value, 'float');
        return $rt->construct(3, $srgbToLinear__float->($rt->swizzle($value, 'r')), $srgbToLinear__float->($rt->swizzle($value, 'g')), $srgbToLinear__float->($rt->swizzle($value, 'b')));
    };
    $cubeRoot__float = sub {
        my ($value) = @_;
        return (($rt->binary('<', $value, $rt->f(0))) ? ($rt->unary('-', $rt->component_wise('pow', $rt->unary('-', $value), $rt->binary('/', $rt->f(1), $rt->f(3), 1, 'float')))) : ($rt->component_wise('pow', $value, $rt->binary('/', $rt->f(1), $rt->f(3), 1, 'float'))));
    };
    $oklabLComponent__vec3 = sub {
        my ($rgb) = @_;
        $rgb = $rt->copy($rgb, 'float');
        my ($l, $lC, $linear, $m, $mC, $s, $sC);
        $linear = $srgbToLinear__vec3->($rt->component_wise('clamp', $rgb, $rt->construct(3, $rt->f(0)), $rt->construct(3, $rt->f(1))));
        $l = $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->f(0.41216561200000001), $rt->swizzle($linear, 'r'), 1, 'float'), $rt->binary('*', $rt->f(0.53627520799999995), $rt->swizzle($linear, 'g'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(0.051457565300000001), $rt->swizzle($linear, 'b'), 1, 'float'), 1, 'float');
        $m = $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->f(0.21185910699999999), $rt->swizzle($linear, 'r'), 1, 'float'), $rt->binary('*', $rt->f(0.68071895839999996), $rt->swizzle($linear, 'g'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(0.107406579), $rt->swizzle($linear, 'b'), 1, 'float'), 1, 'float');
        $s = $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->f(0.088309794699999999), $rt->swizzle($linear, 'r'), 1, 'float'), $rt->binary('*', $rt->f(0.28184741740000002), $rt->swizzle($linear, 'g'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(0.63026136160000001), $rt->swizzle($linear, 'b'), 1, 'float'), 1, 'float');
        $lC = $cubeRoot__float->($rt->component_wise('max', $l, $rt->f(1.0000000000000001e-09)));
        $mC = $cubeRoot__float->($rt->component_wise('max', $m, $rt->f(1.0000000000000001e-09)));
        $sC = $cubeRoot__float->($rt->component_wise('max', $s, $rt->f(1.0000000000000001e-09)));
        return $rt->component_wise('clamp', $rt->binary('-', $rt->binary('+', $rt->binary('*', $rt->f(0.2104542553), $lC, 1, 'float'), $rt->binary('*', $rt->f(0.79361778500000002), $mC, 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(0.0040720467999999996), $sC, 1, 'float'), 1, 'float'), $rt->f(0), $rt->f(1));
    };
    $valueMapComponent__vec4 = sub {
        my ($texel) = @_;
        $texel = $rt->copy($texel, 'float');
        my ($spread);
        $spread = $rt->component_wise('max', $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($texel, 'r'), $rt->swizzle($texel, 'g'), 1, 'float')), $rt->component_wise('max', $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($texel, 'r'), $rt->swizzle($texel, 'b'), 1, 'float')), $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($texel, 'g'), $rt->swizzle($texel, 'b'), 1, 'float'))));
        if ($rt->binary('<', $spread, $rt->f(1.0000000000000001e-05))) {
            return $rt->component_wise('clamp', $rt->swizzle($texel, 'r'), $rt->f(0), $rt->f(1));
        }
        return $oklabLComponent__vec3->($rt->swizzle($texel, 'rgb'));
    };
    $main__void = sub {
        my ($dimensions, $globalCoord, $texel, $uv, $value);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $dimensions = $rt->texture_size($_u_inputTex);
        $uv = $rt->binary('/', $rt->binary('-', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->f(0.5)), 2, 'float'), $rt->construct(2, $rt->component_wise('max', $rt->swizzle($dimensions, 'x'), $rt->i(1)), $rt->component_wise('max', $rt->swizzle($dimensions, 'y'), $rt->i(1))), 2, 'float');
        $texel = $rt->texture($_u_inputTex, $uv);
        $value = $valueMapComponent__vec4->($texel);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $value, $value, $value, $rt->swizzle($texel, 'a')))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
