# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($lum__vec3, $tonemap2__float_vec3_vec3, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_blurTex = $ctx->texture_binding('blurTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_darkness = exists $U->{'darkness'} ? $U->{'darkness'} : $rt->f(0.0);
    my $_u_inkColor = exists $U->{'inkColor'} ? $U->{'inkColor'} : $rt->construct(3, 0.0);
    my $_u_paperColor = exists $U->{'paperColor'} ? $U->{'paperColor'} : $rt->construct(3, 0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $lum__vec3 = sub {
        my ($c) = @_;
        $c = $rt->copy($c, 'float');
        return $rt->dot($c, $rt->construct(3, $rt->f(0.21260000000000001), $rt->f(0.71519999999999995), $rt->f(0.0722)));
    };
    $tonemap2__float_vec3_vec3 = sub {
        my ($t, $ink, $paper) = @_;
        $ink = $rt->copy($ink, 'float');
        $paper = $rt->copy($paper, 'float');
        return $rt->component_wise('mix', $ink, $paper, $rt->component_wise('clamp', $t, $rt->f(0), $rt->f(1)));
    };
    $main__void = sub {
        my ($band, $blur, $edgeGain, $edgeInk, $ink, $lumBlur, $lumSrc, $outColor, $src, $toneHi, $toneInk, $toneLo, $uv);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        $src = $rt->texture($_u_inputTex, $uv);
        $blur = $rt->texture($_u_blurTex, $uv);
        $lumSrc = $lum__vec3->($rt->swizzle($src, 'rgb'));
        $lumBlur = $lum__vec3->($rt->swizzle($blur, 'rgb'));
        $band = $rt->binary('-', $lumSrc, $lumBlur, 1, 'float');
        $edgeGain = $rt->component_wise('mix', $rt->f(4), $rt->f(18), $rt->binary('/', $_u_darkness, $rt->f(100), 1, 'float'));
        $edgeInk = $rt->component_wise('clamp', $rt->binary('*', $rt->component_wise('abs', $band), $edgeGain, 1, 'float'), $rt->f(0), $rt->f(1));
        $toneHi = $rt->component_wise('mix', $rt->f(0.34999999999999998), $rt->f(0.68000000000000005), $rt->binary('/', $_u_darkness, $rt->f(100), 1, 'float'));
        $toneLo = $rt->binary('-', $toneHi, $rt->f(0.26000000000000001), 1, 'float');
        $toneInk = $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $toneLo, $toneHi, $lumSrc), 1, 'float');
        $ink = $rt->component_wise('clamp', $rt->component_wise('max', $edgeInk, $toneInk), $rt->f(0), $rt->f(1));
        $outColor = $tonemap2__float_vec3_vec3->($rt->binary('-', $rt->f(1), $ink, 1, 'float'), $_u_inkColor, $_u_paperColor);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $outColor, $rt->swizzle($src, 'a')))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
