# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($_for0_first, $_for1_first, $baseCoord, $color, $dx, $dy, $globalCoord, $inSize, $maxVal, $minVal, $outCoord, $pixelMax, $pixelMin, $sampleCoord);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $outCoord = $rt->construct(2, $rt->swizzle($ctx->{frag_coord}, 'xy'), 'int');
        $inSize = $rt->texture_size($_u_inputTex);
        $baseCoord = $rt->binary('*', $outCoord, $rt->i(16), 2, 'int');
        $minVal = $rt->f(100000);
        $maxVal = $rt->unary('-', $rt->f(100000));
        $dy = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $dy = $rt->binary('+', $dy, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $dy, $rt->i(16)))) {
                last;
            }
            $dx = $rt->i(0);
            $_for1_first = 1;
            for my $_for1 (0 .. 1048575) {
                if (!$_for1_first) {
                    $dx = $rt->binary('+', $dx, $rt->i(1), 1, 'int');
                }
                $_for1_first = 0;
                if (!($rt->binary('<', $dx, $rt->i(16)))) {
                    last;
                }
                $sampleCoord = $rt->binary('+', $baseCoord, $rt->construct(2, $dx, $dy, 'int'), 2, 'int');
                if ((($rt->binary('>=', $rt->swizzle($sampleCoord, 'x'), $rt->swizzle($inSize, 'x'))) || ($rt->binary('>=', $rt->swizzle($sampleCoord, 'y'), $rt->swizzle($inSize, 'y'))) ? 1 : 0)) {
                    next;
                }
                $color = $rt->texel_fetch($_u_inputTex, $sampleCoord, $rt->i(0));
                $pixelMin = $rt->component_wise('min', $rt->component_wise('min', $rt->swizzle($color, 'r'), $rt->swizzle($color, 'g')), $rt->swizzle($color, 'b'));
                $pixelMax = $rt->component_wise('max', $rt->component_wise('max', $rt->swizzle($color, 'r'), $rt->swizzle($color, 'g')), $rt->swizzle($color, 'b'));
                $minVal = $rt->component_wise('min', $minVal, $pixelMin);
                $maxVal = $rt->component_wise('max', $maxVal, $pixelMax);
            }
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $minVal, $maxVal, $rt->f(0), $rt->f(1)))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
