# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($uv);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->texture($_u_inputTex, $uv))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
