# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_blurTex = $ctx->texture_binding('blurTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_amount = exists $U->{'amount'} ? $U->{'amount'} : $rt->f(0.0);
    my $_u_threshold = exists $U->{'threshold'} ? $U->{'threshold'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($blur, $diff, $gate, $mag, $outc, $src, $t, $uv);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        $src = $rt->texture($_u_inputTex, $uv);
        $blur = $rt->texture($_u_blurTex, $uv);
        $diff = $rt->binary('-', $rt->swizzle($src, 'rgb'), $rt->swizzle($blur, 'rgb'), 3, 'float');
        $t = $rt->binary('/', $_u_threshold, $rt->f(100), 1, 'float');
        $mag = $rt->component_wise('max', $rt->component_wise('max', $rt->component_wise('abs', $rt->swizzle($diff, 'r')), $rt->component_wise('abs', $rt->swizzle($diff, 'g'))), $rt->component_wise('abs', $rt->swizzle($diff, 'b')));
        $gate = $rt->component_wise('smoothstep', $t, $rt->binary('+', $t, $rt->f(0.02), 1, 'float'), $mag);
        $outc = $rt->binary('+', $rt->swizzle($src, 'rgb'), $rt->binary('*', $rt->binary('*', $diff, $rt->binary('/', $_u_amount, $rt->f(100), 1, 'float'), 3, 'float'), $gate, 3, 'float'), 3, 'float');
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->component_wise('clamp', $outc, $rt->f(0), $rt->f(1)), $rt->swizzle($src, 'a')))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
