# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($lessRecord__uvec2_uint_uvec2_uint, $packRecordMajor__vec4, $packRecordBlue__vec4, $unpackRecordRgb__uvec2_uint, $readRecord__ivec2_ivec2_int_int, $main__void);
    my $_retc;
    my $_u_RADIUS = exists $U->{'RADIUS'} ? $U->{'RADIUS'} : 0;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_threshold = exists $U->{'threshold'} ? $U->{'threshold'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $lessRecord__uvec2_uint_uvec2_uint = sub {
        my ($a, $blueA, $b, $blueB) = @_;
        $a = $rt->copy($a, 'uint');
        $b = $rt->copy($b, 'uint');
        if ($rt->binary('!=', $rt->swizzle($a, 'x'), $rt->swizzle($b, 'x'))) {
            return $rt->binary('<', $rt->swizzle($a, 'x'), $rt->swizzle($b, 'x'));
        }
        if ($rt->binary('!=', $rt->swizzle($a, 'y'), $rt->swizzle($b, 'y'))) {
            return $rt->binary('<', $rt->swizzle($a, 'y'), $rt->swizzle($b, 'y'));
        }
        return $rt->binary('<', $blueA, $blueB);
    };
    $packRecordMajor__vec4 = sub {
        my ($sampleColor) = @_;
        $sampleColor = $rt->copy($sampleColor, 'float');
        my ($brightness, $orderedRg, $packedRg);
        $brightness = $rt->dot($rt->swizzle($sampleColor, 'rgb'), $rt->construct(3, $rt->f(0.21260000000000001), $rt->f(0.71519999999999995), $rt->f(0.0722)));
        $packedRg = $rt->pack_half_2x16($rt->swizzle($sampleColor, 'rg'));
        $orderedRg = $rt->binary('|', $rt->binary('<<', $rt->binary('&', $packedRg, $rt->i(65535), 1, 'uint'), $rt->i(16), 1, 'uint'), $rt->binary('>>', $packedRg, $rt->i(16), 1, 'uint'), 1, 'uint');
        return $rt->construct(2, $rt->float_bits_to_uint($brightness), $orderedRg, 'uint');
    };
    $packRecordBlue__vec4 = sub {
        my ($sampleColor) = @_;
        $sampleColor = $rt->copy($sampleColor, 'float');
        return $rt->binary('&', $rt->pack_half_2x16($rt->construct(2, $rt->swizzle($sampleColor, 'b'), $rt->f(0))), $rt->i(65535), 1, 'uint');
    };
    $unpackRecordRgb__uvec2_uint = sub {
        my ($major, $blue) = @_;
        $major = $rt->copy($major, 'uint');
        my ($b, $packedRg, $rg);
        $packedRg = $rt->binary('|', $rt->binary('<<', $rt->swizzle($major, 'y'), $rt->i(16), 1, 'uint'), $rt->binary('>>', $rt->swizzle($major, 'y'), $rt->i(16), 1, 'uint'), 1, 'uint');
        $rg = $rt->unpack_half_2x16($packedRg);
        $b = $rt->swizzle($rt->unpack_half_2x16($blue), 'x');
        return $rt->construct(3, $rg, $b);
    };
    $readRecord__ivec2_ivec2_int_int = sub {
        my ($center, $dimensions, $x, $y) = @_;
        $center = $rt->copy($center, 'int');
        $dimensions = $rt->copy($dimensions, 'int');
        my ($coord);
        $coord = $rt->component_wise('clamp', $rt->binary('+', $center, $rt->construct(2, $x, $y, 'int'), 2, 'int'), $rt->construct(2, $rt->i(0), 'int'), $rt->binary('-', $dimensions, $rt->construct(2, $rt->i(1), 'int'), 2, 'int'));
        return $rt->texel_fetch($_u_inputTex, $coord, $rt->i(0));
    };
    $main__void = sub {
        my ($_for0_first, $_for1_first, $activeCount, $blueRecords, $center, $centerAlpha, $difference, $dimensions, $index, $left, $majorRecords, $maxDifference, $medianIndex, $medianRgb, $originalRgb, $pivotBlue, $pivotMajor, $replaceCenter, $right, $sampleColor, $scanLeft, $scanRight, $temporaryBlue, $temporaryMajor, $x, $y);
        $majorRecords = $rt->new_array($rt->i(49), 2);
        $blueRecords = $rt->new_array($rt->i(49), 1);
        $dimensions = $rt->texture_size($_u_inputTex);
        $center = $rt->construct(2, $rt->swizzle($ctx->{frag_coord}, 'xy'), 'int');
        $originalRgb = $rt->construct(3, $rt->f(0));
        $centerAlpha = $rt->f(1);
        $index = $rt->i(0);
        $y = $rt->unary('-', $_u_RADIUS);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $y = $rt->binary('+', $y, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<=', $y, $_u_RADIUS))) {
                last;
            }
            $x = $rt->unary('-', $_u_RADIUS);
            $_for1_first = 1;
            for my $_for1 (0 .. 1048575) {
                if (!$_for1_first) {
                    $x = $rt->binary('+', $x, $rt->i(1), 1, 'int');
                }
                $_for1_first = 0;
                if (!($rt->binary('<=', $x, $_u_RADIUS))) {
                    last;
                }
                $sampleColor = $readRecord__ivec2_ivec2_int_int->($center, $dimensions, $x, $y);
                $majorRecords->[int($index)] = $packRecordMajor__vec4->($sampleColor);
                $blueRecords->[int($index)] = $packRecordBlue__vec4->($sampleColor);
                if ((($rt->binary('==', $x, $rt->i(0))) && ($rt->binary('==', $y, $rt->i(0))) ? 1 : 0)) {
                    @{$originalRgb} = map { $rt->f32($_) } @{($rt->swizzle($sampleColor, 'rgb'))};
                    $centerAlpha = $rt->swizzle($sampleColor, 'a');
                }
                $index = $rt->binary('+', $index, $rt->i(1), 1, 'int');
            }
        }
        $activeCount = $rt->binary('*', $rt->binary('+', $rt->binary('*', $_u_RADIUS, $rt->i(2), 1, 'int'), $rt->i(1), 1, 'int'), $rt->binary('+', $rt->binary('*', $_u_RADIUS, $rt->i(2), 1, 'int'), $rt->i(1), 1, 'int'), 1, 'int');
        $medianIndex = $rt->binary('>>', $rt->binary('-', $activeCount, $rt->i(1), 1, 'int'), $rt->i(1), 1, 'int');
        $left = $rt->i(0);
        $right = $rt->binary('-', $activeCount, $rt->i(1), 1, 'int');
        for my $_wh2 (0 .. 1048575) {
            if (!($rt->binary('<', $left, $right))) {
                last;
            }
            $pivotMajor = $majorRecords->[int($medianIndex)];
            $pivotBlue = $blueRecords->[int($medianIndex)];
            $scanLeft = $left;
            $scanRight = $right;
            for my $_wh3 (0 .. 1048575) {
                if (!($rt->binary('<=', $scanLeft, $scanRight))) {
                    last;
                }
                for my $_wh4 (0 .. 1048575) {
                    if (!($lessRecord__uvec2_uint_uvec2_uint->($majorRecords->[int($scanLeft)], $blueRecords->[int($scanLeft)], $pivotMajor, $pivotBlue))) {
                        last;
                    }
                    $scanLeft = $rt->binary('+', $scanLeft, $rt->i(1), 1, 'int');
                }
                for my $_wh5 (0 .. 1048575) {
                    if (!($lessRecord__uvec2_uint_uvec2_uint->($pivotMajor, $pivotBlue, $majorRecords->[int($scanRight)], $blueRecords->[int($scanRight)]))) {
                        last;
                    }
                    $scanRight = $rt->binary('-', $scanRight, $rt->i(1), 1, 'int');
                }
                $temporaryBlue = 0;
                $temporaryMajor = $rt->construct(2, 0.0, 'uint');
                if ($rt->binary('<=', $scanLeft, $scanRight)) {
                    $temporaryMajor = $majorRecords->[int($scanLeft)];
                    $majorRecords->[int($scanLeft)] = $majorRecords->[int($scanRight)];
                    $majorRecords->[int($scanRight)] = $temporaryMajor;
                    $temporaryBlue = $blueRecords->[int($scanLeft)];
                    $blueRecords->[int($scanLeft)] = $blueRecords->[int($scanRight)];
                    $blueRecords->[int($scanRight)] = $temporaryBlue;
                    $scanLeft = $rt->binary('+', $scanLeft, $rt->i(1), 1, 'int');
                    $scanRight = $rt->binary('-', $scanRight, $rt->i(1), 1, 'int');
                }
            }
            if ($rt->binary('<', $scanRight, $medianIndex)) {
                $left = $scanLeft;
            }
            if ($rt->binary('<', $medianIndex, $scanLeft)) {
                $right = $scanRight;
            }
        }
        $medianRgb = $unpackRecordRgb__uvec2_uint->($majorRecords->[int($medianIndex)], $blueRecords->[int($medianIndex)]);
        $difference = $rt->component_wise('abs', $rt->binary('-', $originalRgb, $medianRgb, 3, 'float'));
        $maxDifference = $rt->component_wise('max', $rt->component_wise('max', $rt->swizzle($difference, 'r'), $rt->swizzle($difference, 'g')), $rt->swizzle($difference, 'b'));
        $replaceCenter = (($rt->binary('<=', $_u_threshold, $rt->f(0))) || ($rt->binary('>=', $maxDifference, $rt->binary('/', $_u_threshold, $rt->f(100), 1, 'float'))) ? 1 : 0);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, (($replaceCenter) ? ($medianRgb) : ($originalRgb)), $centerAlpha))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
