# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash12__vec2, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_angle = exists $U->{'angle'} ? $U->{'angle'} : $rt->f(0.0);
    my $_u_blurDistance = exists $U->{'blurDistance'} ? $U->{'blurDistance'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $g->{N} = $rt->i(32);
    $hash12__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($p3);
        $p3 = $rt->component_wise('fract', $rt->binary('*', $rt->construct(3, $rt->swizzle($p, 'xyx')), $rt->f(0.1031), 3, 'float'));
        @{$p3} = map { $rt->f32($_) } @{($rt->binary('+', $p3, $rt->dot($p3, $rt->binary('+', $rt->swizzle($p3, 'yzx'), $rt->f(33.329999999999998), 3, 'float')), 3, 'float'))};
        return $rt->component_wise('fract', $rt->binary('*', $rt->binary('+', $rt->swizzle($p3, 'x'), $rt->swizzle($p3, 'y'), 1, 'float'), $rt->swizzle($p3, 'z'), 1, 'float'));
    };
    $main__void = sub {
        my ($_for0_first, $dir, $i, $jitter, $offset, $sum, $t, $tapStep);
        $dir = $rt->construct(2, $rt->component_wise('cos', $rt->component_wise('radians', $_u_angle)), $rt->component_wise('sin', $rt->component_wise('radians', $_u_angle)));
        $tapStep = $rt->binary('/', $_u_blurDistance, $rt->construct(1, $rt->binary('-', $g->{N}, $rt->i(1), 1, 'int')), 1, 'float');
        $jitter = $rt->binary('*', $rt->binary('-', $hash12__vec2->($rt->swizzle($ctx->{frag_coord}, 'xy')), $rt->f(0.5), 1, 'float'), $tapStep, 1, 'float');
        $sum = $rt->construct(4, $rt->f(0));
        $i = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $i, $g->{N}))) {
                last;
            }
            $t = $rt->binary('+', $rt->binary('*', $rt->binary('-', $rt->binary('/', $rt->construct(1, $i), $rt->construct(1, $rt->binary('-', $g->{N}, $rt->i(1), 1, 'int')), 1, 'float'), $rt->f(0.5), 1, 'float'), $_u_blurDistance, 1, 'float'), $jitter, 1, 'float');
            $offset = $rt->binary('*', $dir, $t, 2, 'float');
            @{$sum} = map { $rt->f32($_) } @{($rt->binary('+', $sum, $rt->texture($_u_inputTex, $rt->binary('/', $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $offset, 2, 'float'), $_u_resolution, 2, 'float')), 4, 'float'))};
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->binary('/', $sum, $rt->construct(1, $g->{N}), 4, 'float'))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
