# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_statsTex = $ctx->texture_binding('statsTex');
    $g->{F32_MAX} = $rt->f(3.4028234660000002e+38);
    $g->{F32_MIN} = $rt->unary('-', $rt->f(3.4028234660000002e+38));
    $g->{TILE_SIZE} = $rt->i(8);
    $g->{MAX_TILE_DIM} = $rt->i(512);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($_for0_first, $_for1_first, $globalMax, $globalMin, $sampleCoord, $statsTexSize, $tileCount, $tileStats, $tx, $ty);
        if ((($rt->binary('!=', $rt->construct(1, $rt->swizzle($ctx->{frag_coord}, 'x'), 'int'), $rt->i(0))) || ($rt->binary('!=', $rt->construct(1, $rt->swizzle($ctx->{frag_coord}, 'y'), 'int'), $rt->i(0))) ? 1 : 0)) {
            @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->f(0)))};
            return;
        }
        $statsTexSize = $rt->texture_size($_u_statsTex);
        $tileCount = $rt->construct(2, $rt->binary('/', $rt->binary('-', $rt->binary('+', $rt->swizzle($statsTexSize, 'x'), $g->{TILE_SIZE}, 1, 'int'), $rt->i(1), 1, 'int'), $g->{TILE_SIZE}, 1, 'int'), $rt->binary('/', $rt->binary('-', $rt->binary('+', $rt->swizzle($statsTexSize, 'y'), $g->{TILE_SIZE}, 1, 'int'), $rt->i(1), 1, 'int'), $g->{TILE_SIZE}, 1, 'int'), 'int');
        $globalMin = $g->{F32_MAX};
        $globalMax = $g->{F32_MIN};
        $ty = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $ty = $rt->binary('+', $ty, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $ty, $g->{MAX_TILE_DIM}))) {
                last;
            }
            if ($rt->binary('>=', $ty, $rt->swizzle($tileCount, 'y'))) {
                last;
            }
            $tx = $rt->i(0);
            $_for1_first = 1;
            for my $_for1 (0 .. 1048575) {
                if (!$_for1_first) {
                    $tx = $rt->binary('+', $tx, $rt->i(1), 1, 'int');
                }
                $_for1_first = 0;
                if (!($rt->binary('<', $tx, $g->{MAX_TILE_DIM}))) {
                    last;
                }
                if ($rt->binary('>=', $tx, $rt->swizzle($tileCount, 'x'))) {
                    last;
                }
                $sampleCoord = $rt->construct(2, $rt->binary('*', $tx, $g->{TILE_SIZE}, 1, 'int'), $rt->binary('*', $ty, $g->{TILE_SIZE}, 1, 'int'), 'int');
                $tileStats = $rt->swizzle($rt->texel_fetch($_u_statsTex, $sampleCoord, $rt->i(0)), 'xy');
                $globalMin = $rt->component_wise('min', $globalMin, $rt->swizzle($tileStats, 'x'));
                $globalMax = $rt->component_wise('max', $globalMax, $rt->swizzle($tileStats, 'y'));
            }
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $globalMin, $globalMax, $rt->f(0), $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
