# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash12__vec2, $rotateAround__vec2_vec2_float_float, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_amount = exists $U->{'amount'} ? $U->{'amount'} : $rt->f(0.0);
    my $_u_centerX = exists $U->{'centerX'} ? $U->{'centerX'} : $rt->f(0.0);
    my $_u_centerY = exists $U->{'centerY'} ? $U->{'centerY'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $g->{N} = $rt->i(32);
    $hash12__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($p3);
        $p3 = $rt->component_wise('fract', $rt->binary('*', $rt->construct(3, $rt->swizzle($p, 'xyx')), $rt->f(0.1031), 3, 'float'));
        @{$p3} = map { $rt->f32($_) } @{($rt->binary('+', $p3, $rt->dot($p3, $rt->binary('+', $rt->swizzle($p3, 'yzx'), $rt->f(33.329999999999998), 3, 'float')), 3, 'float'))};
        return $rt->component_wise('fract', $rt->binary('*', $rt->binary('+', $rt->swizzle($p3, 'x'), $rt->swizzle($p3, 'y'), 1, 'float'), $rt->swizzle($p3, 'z'), 1, 'float'));
    };
    $rotateAround__vec2_vec2_float_float = sub {
        my ($uv, $center, $angle, $aspectRatio) = @_;
        $uv = $rt->copy($uv, 'float');
        $center = $rt->copy($center, 'float');
        my ($c, $co, $p, $s);
        $p = $uv;
        $p = $rt->assign_swizzle($p, 'x', $rt->binary('*', $rt->swizzle($p, 'x'), $aspectRatio, 1, 'float'));
        $c = $center;
        $c = $rt->assign_swizzle($c, 'x', $rt->binary('*', $rt->swizzle($c, 'x'), $aspectRatio, 1, 'float'));
        @{$p} = map { $rt->f32($_) } @{($rt->binary('-', $p, $c, 2, 'float'))};
        $s = $rt->component_wise('sin', $angle);
        $co = $rt->component_wise('cos', $angle);
        @{$p} = map { $rt->f32($_) } @{($rt->matrix_mult($rt->construct(4, $co, $rt->unary('-', $s), $s, $co), $p, 2))};
        @{$p} = map { $rt->f32($_) } @{($rt->binary('+', $p, $c, 2, 'float'))};
        $p = $rt->assign_swizzle($p, 'x', $rt->binary('/', $rt->swizzle($p, 'x'), $aspectRatio, 1, 'float'));
        return $p;
    };
    $main__void = sub {
        my ($_for0_first, $angularStep, $arc, $aspectRatio, $center, $distorted, $globalCoord, $i, $jitter, $jitterCoord, $sampleUV, $sum, $theta, $uv);
        $aspectRatio = $rt->binary('/', $rt->swizzle($_u_fullResolution, 'x'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float');
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $uv = $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float');
        $center = $rt->construct(2, $_u_centerX, $_u_centerY);
        $arc = $rt->component_wise('radians', $_u_amount);
        $angularStep = $rt->binary('/', $arc, $rt->construct(1, $rt->binary('-', $g->{N}, $rt->i(1), 1, 'int')), 1, 'float');
        $jitterCoord = $rt->construct(2, $rt->swizzle($globalCoord, 'x'), $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($globalCoord, 'y'), $rt->binary('*', $rt->swizzle($_u_fullResolution, 'y'), $rt->f(0.5), 1, 'float'), 1, 'float')));
        $jitter = $rt->binary('*', $rt->binary('-', $hash12__vec2->($jitterCoord), $rt->f(0.5), 1, 'float'), $angularStep, 1, 'float');
        $sum = $rt->construct(4, $rt->f(0));
        $i = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $i, $g->{N}))) {
                last;
            }
            $theta = $rt->binary('+', $rt->binary('*', $rt->binary('-', $rt->binary('/', $rt->construct(1, $i), $rt->construct(1, $rt->binary('-', $g->{N}, $rt->i(1), 1, 'int')), 1, 'float'), $rt->f(0.5), 1, 'float'), $arc, 1, 'float'), $jitter, 1, 'float');
            $distorted = $rt->component_wise('clamp', $rotateAround__vec2_vec2_float_float->($uv, $center, $theta, $aspectRatio), $rt->f(0), $rt->f(1));
            $sampleUV = $rt->component_wise('clamp', $rt->binary('/', $rt->binary('-', $rt->binary('*', $distorted, $_u_fullResolution, 2, 'float'), $_u_tileOffset, 2, 'float'), $_u_resolution, 2, 'float'), $rt->f(0), $rt->f(1));
            @{$sum} = map { $rt->f32($_) } @{($rt->binary('+', $sum, $rt->texture($_u_inputTex, $sampleUV), 4, 'float'))};
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->binary('/', $sum, $rt->construct(1, $g->{N}), 4, 'float'))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
