# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($map__float_float_float_float_float, $hsv2rgb__vec3, $rgb2hsv__vec3, $linear_srgb_from_oklab__vec3, $linearToSrgb__vec3, $main__void);
    my $_retc;
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_mode = exists $U->{'mode'} ? $U->{'mode'} : 0;
    my $_u_rotation = exists $U->{'rotation'} ? $U->{'rotation'} : $rt->f(0.0);
    my $_u_hueRange = exists $U->{'hueRange'} ? $U->{'hueRange'} : $rt->f(0.0);
    my $_u_saturation = exists $U->{'saturation'} ? $U->{'saturation'} : $rt->f(0.0);
    my $_u_brightness = exists $U->{'brightness'} ? $U->{'brightness'} : $rt->f(0.0);
    my $_u_contrast = exists $U->{'contrast'} ? $U->{'contrast'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $g->{TAU} = $rt->f(6.2831853071800001);
    $g->{fwdA} = $rt->construct(9, $rt->f(1), $rt->f(1), $rt->f(1), $rt->f(0.39633777739999998), $rt->unary('-', $rt->f(0.1055613458)), $rt->unary('-', $rt->f(0.089484177499999998)), $rt->f(0.21580375730000001), $rt->unary('-', $rt->f(0.063854172799999998)), $rt->unary('-', $rt->f(1.291485548)));
    $g->{fwdB} = $rt->construct(9, $rt->f(4.0767245292999998), $rt->unary('-', $rt->f(1.2681437731)), $rt->unary('-', $rt->f(0.0041119885000000002)), $rt->unary('-', $rt->f(3.3072168827000001)), $rt->f(2.6093323230999999), $rt->unary('-', $rt->f(0.70347630979999998)), $rt->f(0.2307590544), $rt->unary('-', $rt->f(0.34113442900000002)), $rt->f(1.7068625689000001));
    $map__float_float_float_float_float = sub {
        my ($value, $inMin, $inMax, $outMin, $outMax) = @_;
        return $rt->binary('+', $outMin, $rt->binary('/', $rt->binary('*', $rt->binary('-', $outMax, $outMin, 1, 'float'), $rt->binary('-', $value, $inMin, 1, 'float'), 1, 'float'), $rt->binary('-', $inMax, $inMin, 1, 'float'), 1, 'float'), 1, 'float');
    };
    $hsv2rgb__vec3 = sub {
        my ($hsv) = @_;
        $hsv = $rt->copy($hsv, 'float');
        my ($c, $h, $m, $rgb, $s, $v, $x);
        $h = $rt->component_wise('fract', $rt->swizzle($hsv, 'x'));
        $s = $rt->swizzle($hsv, 'y');
        $v = $rt->swizzle($hsv, 'z');
        $c = $rt->binary('*', $v, $s, 1, 'float');
        $x = $rt->binary('*', $c, $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->component_wise('mod', $rt->binary('*', $h, $rt->f(6), 1, 'float'), $rt->f(2)), $rt->f(1), 1, 'float')), 1, 'float'), 1, 'float');
        $m = $rt->binary('-', $v, $c, 1, 'float');
        $rgb = $rt->construct(3, 0.0);
        if ($rt->binary('<', $h, $rt->binary('/', $rt->f(1), $rt->f(6), 1, 'float'))) {
            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $x, $rt->f(0)))};
        } else {
            if ($rt->binary('<', $h, $rt->binary('/', $rt->f(2), $rt->f(6), 1, 'float'))) {
                @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $c, $rt->f(0)))};
            } else {
                if ($rt->binary('<', $h, $rt->binary('/', $rt->f(3), $rt->f(6), 1, 'float'))) {
                    @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $c, $x))};
                } else {
                    if ($rt->binary('<', $h, $rt->binary('/', $rt->f(4), $rt->f(6), 1, 'float'))) {
                        @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $x, $c))};
                    } else {
                        if ($rt->binary('<', $h, $rt->binary('/', $rt->f(5), $rt->f(6), 1, 'float'))) {
                            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $rt->f(0), $c))};
                        } else {
                            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $rt->f(0), $x))};
                        }
                    }
                }
            }
        }
        return $rt->binary('+', $rgb, $m, 3, 'float');
    };
    $rgb2hsv__vec3 = sub {
        my ($rgb) = @_;
        $rgb = $rt->copy($rgb, 'float');
        my ($_g, $b, $delta, $h, $maxC, $minC, $r, $s);
        $r = $rt->swizzle($rgb, 'r');
        $_g = $rt->swizzle($rgb, 'g');
        $b = $rt->swizzle($rgb, 'b');
        $maxC = $rt->component_wise('max', $r, $rt->component_wise('max', $_g, $b));
        $minC = $rt->component_wise('min', $r, $rt->component_wise('min', $_g, $b));
        $delta = $rt->binary('-', $maxC, $minC, 1, 'float');
        $h = $rt->f(0);
        if ($rt->binary('!=', $delta, $rt->f(0))) {
            if ($rt->binary('==', $maxC, $r)) {
                $h = $rt->binary('/', $rt->component_wise('mod', $rt->binary('/', $rt->binary('-', $_g, $b, 1, 'float'), $delta, 1, 'float'), $rt->f(6)), $rt->f(6), 1, 'float');
            } else {
                if ($rt->binary('==', $maxC, $_g)) {
                    $h = $rt->binary('/', $rt->binary('+', $rt->binary('/', $rt->binary('-', $b, $r, 1, 'float'), $delta, 1, 'float'), $rt->f(2), 1, 'float'), $rt->f(6), 1, 'float');
                } else {
                    $h = $rt->binary('/', $rt->binary('+', $rt->binary('/', $rt->binary('-', $r, $_g, 1, 'float'), $delta, 1, 'float'), $rt->f(4), 1, 'float'), $rt->f(6), 1, 'float');
                }
            }
        }
        $s = (($rt->binary('==', $maxC, $rt->f(0))) ? ($rt->f(0)) : ($rt->binary('/', $delta, $maxC, 1, 'float')));
        return $rt->construct(3, $h, $s, $maxC);
    };
    $linear_srgb_from_oklab__vec3 = sub {
        my ($c) = @_;
        $c = $rt->copy($c, 'float');
        my ($lms);
        $lms = $rt->matrix_mult($g->{fwdA}, $c, 3);
        return $rt->matrix_mult($g->{fwdB}, $rt->binary('*', $rt->binary('*', $lms, $lms, 3, 'float'), $lms, 3, 'float'), 3);
    };
    $linearToSrgb__vec3 = sub {
        my ($linear) = @_;
        $linear = $rt->copy($linear, 'float');
        my ($_for0_first, $i, $srgb);
        $srgb = $rt->construct(3, 0.0);
        $i = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $i, $rt->i(3)))) {
                last;
            }
            if ($rt->binary('<=', $linear->[int($i)], $rt->f(0.0031308))) {
                $srgb->[int($i)] = $rt->binary('*', $linear->[int($i)], $rt->f(12.92), 1, 'float');
            } else {
                $srgb->[int($i)] = $rt->binary('-', $rt->binary('*', $rt->f(1.0549999999999999), $rt->component_wise('pow', $linear->[int($i)], $rt->binary('/', $rt->f(1), $rt->f(2.3999999999999999), 1, 'float')), 1, 'float'), $rt->f(0.055), 1, 'float');
            }
        }
        return $srgb;
    };
    $main__void = sub {
        my ($C, $H, $L, $a, $b, $color, $contrastFactor, $globalCoord, $hsv, $texSize, $uv);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $texSize = $rt->texture_size($_u_inputTex);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $texSize), 2, 'float');
        $color = $rt->texture($_u_inputTex, $uv);
        $C = $rt->f(0.0);
        $H = $rt->f(0.0);
        $L = $rt->f(0.0);
        $a = $rt->f(0.0);
        $b = $rt->f(0.0);
        if ($rt->binary('==', $_u_mode, $rt->i(1))) {
            $color = $rt->assign_swizzle($color, 'rgb', $hsv2rgb__vec3->($rt->swizzle($color, 'rgb')));
        } else {
            if ($rt->binary('==', $_u_mode, $rt->i(2))) {
                $color = $rt->assign_swizzle($color, 'g', $rt->binary('+', $rt->binary('*', $rt->swizzle($color, 'g'), $rt->unary('-', $rt->f(0.50900000000000001)), 1, 'float'), $rt->f(0.27600000000000002), 1, 'float'));
                $color = $rt->assign_swizzle($color, 'b', $rt->binary('+', $rt->binary('*', $rt->swizzle($color, 'b'), $rt->unary('-', $rt->f(0.50900000000000001)), 1, 'float'), $rt->f(0.19800000000000001), 1, 'float'));
                $color = $rt->assign_swizzle($color, 'rgb', $linear_srgb_from_oklab__vec3->($rt->swizzle($color, 'rgb')));
                $color = $rt->assign_swizzle($color, 'rgb', $linearToSrgb__vec3->($rt->swizzle($color, 'rgb')));
            } else {
                if ($rt->binary('==', $_u_mode, $rt->i(3))) {
                    $L = $rt->swizzle($color, 'r');
                    $C = $rt->binary('*', $rt->swizzle($color, 'g'), $rt->f(0.40000000000000002), 1, 'float');
                    $H = $rt->binary('*', $rt->swizzle($color, 'b'), $g->{TAU}, 1, 'float');
                    $a = $rt->binary('*', $C, $rt->component_wise('cos', $H), 1, 'float');
                    $b = $rt->binary('*', $C, $rt->component_wise('sin', $H), 1, 'float');
                    $color = $rt->assign_swizzle($color, 'rgb', $linear_srgb_from_oklab__vec3->($rt->construct(3, $L, $a, $b)));
                    $color = $rt->assign_swizzle($color, 'rgb', $linearToSrgb__vec3->($rt->swizzle($color, 'rgb')));
                }
            }
        }
        $hsv = $rgb2hsv__vec3->($rt->swizzle($color, 'rgb'));
        $hsv = $rt->assign_swizzle($hsv, 'x', $rt->component_wise('fract', $rt->binary('+', $rt->binary('*', $rt->swizzle($hsv, 'x'), $map__float_float_float_float_float->($_u_hueRange, $rt->f(0), $rt->f(200), $rt->f(0), $rt->f(2)), 1, 'float'), $rt->binary('/', $_u_rotation, $rt->f(360), 1, 'float'), 1, 'float')));
        $hsv = $rt->assign_swizzle($hsv, 'y', $rt->binary('*', $rt->swizzle($hsv, 'y'), $_u_saturation, 1, 'float'));
        $color = $rt->assign_swizzle($color, 'rgb', $hsv2rgb__vec3->($hsv));
        $color = $rt->assign_swizzle($color, 'rgb', $rt->binary('*', $rt->swizzle($color, 'rgb'), $_u_brightness, 3, 'float'));
        $contrastFactor = $rt->binary('*', $_u_contrast, $rt->f(2), 1, 'float');
        $color = $rt->assign_swizzle($color, 'rgb', $rt->binary('+', $rt->binary('*', $rt->binary('-', $rt->swizzle($color, 'rgb'), $rt->f(0.5), 3, 'float'), $contrastFactor, 3, 'float'), $rt->f(0.5), 3, 'float'));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
