# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($normalized_sine__float, $main__void);
    my $_retc;
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_amount = exists $U->{'amount'} ? $U->{'amount'} : $rt->f(0.0);
    my $_u_colorMode = exists $U->{'colorMode'} ? $U->{'colorMode'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $normalized_sine__float = sub {
        my ($value) = @_;
        return $rt->binary('*', $rt->binary('+', $rt->component_wise('sin', $value), $rt->f(1), 1, 'float'), $rt->f(0.5), 1, 'float');
    };
    $main__void = sub {
        my ($color, $globalCoord, $lum, $result, $texSize, $use_rgb, $uv);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $texSize = $rt->texture_size($_u_inputTex);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $texSize), 2, 'float');
        $color = $rt->texture($_u_inputTex, $uv);
        $use_rgb = $rt->binary('>', $_u_colorMode, $rt->f(0.5));
        $lum = $rt->f(0.0);
        $result = $rt->f(0.0);
        if ($use_rgb) {
            $color = $rt->assign_swizzle($color, 'r', $normalized_sine__float->($rt->binary('*', $rt->swizzle($color, 'r'), $_u_amount, 1, 'float')));
            $color = $rt->assign_swizzle($color, 'g', $normalized_sine__float->($rt->binary('*', $rt->swizzle($color, 'g'), $_u_amount, 1, 'float')));
            $color = $rt->assign_swizzle($color, 'b', $normalized_sine__float->($rt->binary('*', $rt->swizzle($color, 'b'), $_u_amount, 1, 'float')));
        } else {
            $lum = $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->f(0.29899999999999999), $rt->swizzle($color, 'r'), 1, 'float'), $rt->binary('*', $rt->f(0.58699999999999997), $rt->swizzle($color, 'g'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(0.114), $rt->swizzle($color, 'b'), 1, 'float'), 1, 'float');
            $result = $normalized_sine__float->($rt->binary('*', $lum, $_u_amount, 1, 'float'));
            $color = $rt->assign_swizzle($color, 'rgb', $rt->construct(3, $result));
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
