# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_level = exists $U->{'level'} ? $U->{'level'} : $rt->f(0.0);
    my $_u_sharpness = exists $U->{'sharpness'} ? $U->{'sharpness'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($c, $e, $globalCoord, $l, $st);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $st = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($_u_inputTex)), 2, 'float');
        $c = $rt->texture($_u_inputTex, $st);
        $l = $rt->dot($rt->swizzle($c, 'rgb'), $rt->construct(3, $rt->f(0.29899999999999999), $rt->f(0.58699999999999997), $rt->f(0.114)));
        $e = $rt->component_wise('smoothstep', $rt->binary('-', $_u_level, $_u_sharpness, 1, 'float'), $rt->binary('+', $_u_level, $_u_sharpness, 1, 'float'), $l);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->construct(3, $e), $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
