# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($map__float_float_float_float_float, $rgb2hsv__vec3, $hsv2rgb__vec3, $main__void);
    my $_retc;
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_rotation = exists $U->{'rotation'} ? $U->{'rotation'} : $rt->f(0.0);
    my $_u_hueRange = exists $U->{'hueRange'} ? $U->{'hueRange'} : $rt->f(0.0);
    my $_u_saturation = exists $U->{'saturation'} ? $U->{'saturation'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $map__float_float_float_float_float = sub {
        my ($value, $inMin, $inMax, $outMin, $outMax) = @_;
        return $rt->binary('+', $outMin, $rt->binary('/', $rt->binary('*', $rt->binary('-', $outMax, $outMin, 1, 'float'), $rt->binary('-', $value, $inMin, 1, 'float'), 1, 'float'), $rt->binary('-', $inMax, $inMin, 1, 'float'), 1, 'float'), 1, 'float');
    };
    $rgb2hsv__vec3 = sub {
        my ($rgb) = @_;
        $rgb = $rt->copy($rgb, 'float');
        my ($_g, $b, $delta, $h, $maxC, $minC, $r, $s);
        $r = $rt->swizzle($rgb, 'r');
        $_g = $rt->swizzle($rgb, 'g');
        $b = $rt->swizzle($rgb, 'b');
        $maxC = $rt->component_wise('max', $r, $rt->component_wise('max', $_g, $b));
        $minC = $rt->component_wise('min', $r, $rt->component_wise('min', $_g, $b));
        $delta = $rt->binary('-', $maxC, $minC, 1, 'float');
        $h = $rt->f(0);
        if ($rt->binary('!=', $delta, $rt->f(0))) {
            if ($rt->binary('==', $maxC, $r)) {
                $h = $rt->binary('/', $rt->component_wise('mod', $rt->binary('/', $rt->binary('-', $_g, $b, 1, 'float'), $delta, 1, 'float'), $rt->f(6)), $rt->f(6), 1, 'float');
            } else {
                if ($rt->binary('==', $maxC, $_g)) {
                    $h = $rt->binary('/', $rt->binary('+', $rt->binary('/', $rt->binary('-', $b, $r, 1, 'float'), $delta, 1, 'float'), $rt->f(2), 1, 'float'), $rt->f(6), 1, 'float');
                } else {
                    $h = $rt->binary('/', $rt->binary('+', $rt->binary('/', $rt->binary('-', $r, $_g, 1, 'float'), $delta, 1, 'float'), $rt->f(4), 1, 'float'), $rt->f(6), 1, 'float');
                }
            }
        }
        $s = (($rt->binary('==', $maxC, $rt->f(0))) ? ($rt->f(0)) : ($rt->binary('/', $delta, $maxC, 1, 'float')));
        return $rt->construct(3, $h, $s, $maxC);
    };
    $hsv2rgb__vec3 = sub {
        my ($hsv) = @_;
        $hsv = $rt->copy($hsv, 'float');
        my ($c, $h, $m, $rgb, $s, $v, $x);
        $h = $rt->component_wise('fract', $rt->swizzle($hsv, 'x'));
        $s = $rt->swizzle($hsv, 'y');
        $v = $rt->swizzle($hsv, 'z');
        $c = $rt->binary('*', $v, $s, 1, 'float');
        $x = $rt->binary('*', $c, $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->component_wise('mod', $rt->binary('*', $h, $rt->f(6), 1, 'float'), $rt->f(2)), $rt->f(1), 1, 'float')), 1, 'float'), 1, 'float');
        $m = $rt->binary('-', $v, $c, 1, 'float');
        $rgb = $rt->construct(3, 0.0);
        if ($rt->binary('<', $h, $rt->binary('/', $rt->f(1), $rt->f(6), 1, 'float'))) {
            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $x, $rt->f(0)))};
        } else {
            if ($rt->binary('<', $h, $rt->binary('/', $rt->f(2), $rt->f(6), 1, 'float'))) {
                @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $c, $rt->f(0)))};
            } else {
                if ($rt->binary('<', $h, $rt->binary('/', $rt->f(3), $rt->f(6), 1, 'float'))) {
                    @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $c, $x))};
                } else {
                    if ($rt->binary('<', $h, $rt->binary('/', $rt->f(4), $rt->f(6), 1, 'float'))) {
                        @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $x, $c))};
                    } else {
                        if ($rt->binary('<', $h, $rt->binary('/', $rt->f(5), $rt->f(6), 1, 'float'))) {
                            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $rt->f(0), $c))};
                        } else {
                            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $rt->f(0), $x))};
                        }
                    }
                }
            }
        }
        return $rt->binary('+', $rgb, $m, 3, 'float');
    };
    $main__void = sub {
        my ($color, $globalCoord, $hsv, $texSize, $uv);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $texSize = $rt->texture_size($_u_inputTex);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $texSize), 2, 'float');
        $color = $rt->texture($_u_inputTex, $uv);
        $hsv = $rgb2hsv__vec3->($rt->swizzle($color, 'rgb'));
        $hsv = $rt->assign_swizzle($hsv, 'x', $rt->component_wise('fract', $rt->binary('+', $rt->binary('*', $rt->swizzle($hsv, 'x'), $map__float_float_float_float_float->($_u_hueRange, $rt->f(0), $rt->f(200), $rt->f(0), $rt->f(2)), 1, 'float'), $rt->binary('/', $_u_rotation, $rt->f(360), 1, 'float'), 1, 'float')));
        $hsv = $rt->assign_swizzle($hsv, 'y', $rt->binary('*', $rt->swizzle($hsv, 'y'), $_u_saturation, 1, 'float'));
        $color = $rt->assign_swizzle($color, 'rgb', $hsv2rgb__vec3->($hsv));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
