# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_x = exists $U->{'x'} ? $U->{'x'} : $rt->f(0.0);
    my $_u_y = exists $U->{'y'} ? $U->{'y'} : $rt->f(0.0);
    my $_u_wrap = exists $U->{'wrap'} ? $U->{'wrap'} : 0;
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($globalCoord, $texSize, $uv);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $texSize = $rt->texture_size($_u_inputTex);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $texSize), 2, 'float');
        $uv = $rt->assign_swizzle($uv, 'x', $rt->binary('-', $rt->swizzle($uv, 'x'), $_u_x, 1, 'float'));
        $uv = $rt->assign_swizzle($uv, 'y', $rt->binary('-', $rt->swizzle($uv, 'y'), $_u_y, 1, 'float'));
        if ($rt->binary('==', $_u_wrap, $rt->i(0))) {
            @{$uv} = map { $rt->f32($_) } @{($rt->component_wise('abs', $rt->binary('-', $rt->component_wise('mod', $rt->binary('+', $uv, $rt->f(1), 2, 'float'), $rt->f(2)), $rt->f(1), 2, 'float')))};
        } else {
            if ($rt->binary('==', $_u_wrap, $rt->i(1))) {
                @{$uv} = map { $rt->f32($_) } @{($rt->component_wise('fract', $uv))};
            } else {
                @{$uv} = map { $rt->f32($_) } @{($rt->component_wise('clamp', $uv, $rt->f(0), $rt->f(1)))};
            }
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->texture($_u_inputTex, $uv))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
