# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($pcg__uvec3, $hash31__vec3, $noise3d__vec3, $simplexRandom__float_float_vec3, $applyWrap__vec2, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_range = exists $U->{'range'} ? $U->{'range'} : $rt->f(0.0);
    my $_u_wrap = exists $U->{'wrap'} ? $U->{'wrap'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $g->{TAU} = $rt->f(6.2831853071795898);
    $g->{X_NOISE_SEED} = $rt->construct(3, $rt->f(17), $rt->f(29), $rt->f(11));
    $g->{Y_NOISE_SEED} = $rt->construct(3, $rt->f(41), $rt->f(23), $rt->f(7));
    $pcg__uvec3 = sub {
        my ($v) = @_;
        $v = $rt->copy($v, 'uint');
        @{$v} = @{($rt->binary('+', $rt->binary('*', $v, $rt->i(1664525), 3, 'uint'), $rt->i(1013904223), 3, 'uint'))};
        $v = $rt->assign_swizzle($v, 'x', $rt->binary('+', $rt->swizzle($v, 'x'), $rt->binary('*', $rt->swizzle($v, 'y'), $rt->swizzle($v, 'z'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'y', $rt->binary('+', $rt->swizzle($v, 'y'), $rt->binary('*', $rt->swizzle($v, 'z'), $rt->swizzle($v, 'x'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'z', $rt->binary('+', $rt->swizzle($v, 'z'), $rt->binary('*', $rt->swizzle($v, 'x'), $rt->swizzle($v, 'y'), 1, 'uint'), 1, 'uint'));
        @{$v} = @{($rt->binary('^', $v, $rt->binary('>>', $v, $rt->i(16), 3, 'uint'), 3, 'uint'))};
        $v = $rt->assign_swizzle($v, 'x', $rt->binary('+', $rt->swizzle($v, 'x'), $rt->binary('*', $rt->swizzle($v, 'y'), $rt->swizzle($v, 'z'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'y', $rt->binary('+', $rt->swizzle($v, 'y'), $rt->binary('*', $rt->swizzle($v, 'z'), $rt->swizzle($v, 'x'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'z', $rt->binary('+', $rt->swizzle($v, 'z'), $rt->binary('*', $rt->swizzle($v, 'x'), $rt->swizzle($v, 'y'), 1, 'uint'), 1, 'uint'));
        return $v;
    };
    $hash31__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($seed);
        $seed = $rt->construct(3, $rt->construct(1, (($rt->binary('>=', $rt->swizzle($p, 'x'), $rt->f(0))) ? ($rt->binary('*', $rt->swizzle($p, 'x'), $rt->f(2), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'x')), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float'))), 'uint'), $rt->construct(1, (($rt->binary('>=', $rt->swizzle($p, 'y'), $rt->f(0))) ? ($rt->binary('*', $rt->swizzle($p, 'y'), $rt->f(2), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'y')), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float'))), 'uint'), $rt->construct(1, (($rt->binary('>=', $rt->swizzle($p, 'z'), $rt->f(0))) ? ($rt->binary('*', $rt->swizzle($p, 'z'), $rt->f(2), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'z')), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float'))), 'uint'), 'uint');
        return $rt->binary('/', $rt->construct(1, $rt->swizzle($pcg__uvec3->($seed), 'x')), $rt->construct(1, $rt->i(4294967295)), 1, 'float');
    };
    $noise3d__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($f, $i, $n000, $n001, $n010, $n011, $n100, $n101, $n110, $n111, $x0, $x1, $x2, $x3, $y0, $y1);
        $i = $rt->component_wise('floor', $p);
        $f = $rt->component_wise('fract', $p);
        @{$f} = map { $rt->f32($_) } @{($rt->binary('*', $rt->binary('*', $f, $f, 3, 'float'), $rt->binary('-', $rt->f(3), $rt->binary('*', $rt->f(2), $f, 3, 'float'), 3, 'float'), 3, 'float'))};
        $n000 = $hash31__vec3->($i);
        $n100 = $hash31__vec3->($rt->binary('+', $i, $rt->construct(3, $rt->f(1), $rt->f(0), $rt->f(0)), 3, 'float'));
        $n010 = $hash31__vec3->($rt->binary('+', $i, $rt->construct(3, $rt->f(0), $rt->f(1), $rt->f(0)), 3, 'float'));
        $n110 = $hash31__vec3->($rt->binary('+', $i, $rt->construct(3, $rt->f(1), $rt->f(1), $rt->f(0)), 3, 'float'));
        $n001 = $hash31__vec3->($rt->binary('+', $i, $rt->construct(3, $rt->f(0), $rt->f(0), $rt->f(1)), 3, 'float'));
        $n101 = $hash31__vec3->($rt->binary('+', $i, $rt->construct(3, $rt->f(1), $rt->f(0), $rt->f(1)), 3, 'float'));
        $n011 = $hash31__vec3->($rt->binary('+', $i, $rt->construct(3, $rt->f(0), $rt->f(1), $rt->f(1)), 3, 'float'));
        $n111 = $hash31__vec3->($rt->binary('+', $i, $rt->construct(3, $rt->f(1), $rt->f(1), $rt->f(1)), 3, 'float'));
        $x0 = $rt->component_wise('mix', $n000, $n100, $rt->swizzle($f, 'x'));
        $x1 = $rt->component_wise('mix', $n010, $n110, $rt->swizzle($f, 'x'));
        $x2 = $rt->component_wise('mix', $n001, $n101, $rt->swizzle($f, 'x'));
        $x3 = $rt->component_wise('mix', $n011, $n111, $rt->swizzle($f, 'x'));
        $y0 = $rt->component_wise('mix', $x0, $x1, $rt->swizzle($f, 'y'));
        $y1 = $rt->component_wise('mix', $x2, $x3, $rt->swizzle($f, 'y'));
        return $rt->component_wise('mix', $y0, $y1, $rt->swizzle($f, 'z'));
    };
    $simplexRandom__float_float_vec3 = sub {
        my ($t, $spd, $seed) = @_;
        $seed = $rt->copy($seed, 'float');
        my ($angle, $n, $w, $z);
        $angle = $rt->binary('*', $t, $g->{TAU}, 1, 'float');
        $z = $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->component_wise('cos', $angle), $spd, 1, 'float'), $rt->swizzle($seed, 'x'), 1, 'float'), $rt->binary('*', $spd, $rt->f(0.317), 1, 'float'), 1, 'float');
        $w = $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->component_wise('sin', $angle), $spd, 1, 'float'), $rt->swizzle($seed, 'y'), 1, 'float'), $rt->binary('*', $spd, $rt->f(0.51900000000000002), 1, 'float'), 1, 'float');
        $n = $noise3d__vec3->($rt->construct(3, $z, $w, $rt->binary('+', $rt->swizzle($seed, 'z'), $rt->binary('*', $spd, $rt->f(0.10000000000000001), 1, 'float'), 1, 'float')));
        return $rt->component_wise('clamp', $n, $rt->f(0), $rt->f(1));
    };
    $applyWrap__vec2 = sub {
        my ($uv) = @_;
        $uv = $rt->copy($uv, 'float');
        my ($mode);
        $mode = $rt->construct(1, $_u_wrap, 'int');
        if ($rt->binary('==', $mode, $rt->i(0))) {
            return $rt->component_wise('abs', $rt->binary('-', $rt->component_wise('mod', $rt->binary('+', $uv, $rt->f(1), 2, 'float'), $rt->f(2)), $rt->f(1), 2, 'float'));
        } else {
            if ($rt->binary('==', $mode, $rt->i(1))) {
                return $rt->component_wise('fract', $uv);
            }
        }
        return $rt->component_wise('clamp', $uv, $rt->f(0), $rt->f(1));
    };
    $main__void = sub {
        my ($offset, $offsetScale, $r, $sampleCoord, $sampled, $spd, $xRandom, $yRandom);
        $spd = $rt->component_wise('max', $_u_speed, $rt->f(0.001));
        $r = $rt->component_wise('max', $_u_range, $rt->f(0));
        $xRandom = $simplexRandom__float_float_vec3->($rt->binary('+', $_u_time, $rt->binary('*', $_u_speed, $rt->f(0.10000000000000001), 1, 'float'), 1, 'float'), $spd, $g->{X_NOISE_SEED});
        $yRandom = $simplexRandom__float_float_vec3->($rt->binary('+', $_u_time, $rt->binary('*', $_u_speed, $rt->f(0.10000000000000001), 1, 'float'), 1, 'float'), $spd, $g->{Y_NOISE_SEED});
        $offsetScale = $rt->binary('*', $r, $rt->binary('+', $rt->f(0.01), $rt->binary('*', $_u_speed, $rt->f(0.02), 1, 'float'), 1, 'float'), 1, 'float');
        $offset = $rt->binary('*', $rt->binary('-', $rt->construct(2, $xRandom, $yRandom), $rt->f(0.5), 2, 'float'), $offsetScale, 2, 'float');
        $sampleCoord = $rt->binary('+', $ctx->{uv}, $offset, 2, 'float');
        @{$sampleCoord} = map { $rt->f32($_) } @{($applyWrap__vec2->($sampleCoord))};
        $sampled = $rt->texture($_u_inputTex, $sampleCoord);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($sampled)};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
