# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($clamp01__float, $blendOverlay__float_float, $blendSoftLight__float_float, $applyBlendMode__vec4_vec4_int, $distanceMetric__vec2_vec2_int, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_tex = $ctx->texture_binding('tex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_shape = exists $U->{'shape'} ? $U->{'shape'} : 0;
    my $_u_power = exists $U->{'power'} ? $U->{'power'} : $rt->f(0.0);
    my $_u_hardness = exists $U->{'hardness'} ? $U->{'hardness'} : $rt->f(0.0);
    my $_u_blendMode = exists $U->{'blendMode'} ? $U->{'blendMode'} : 0;
    $g->{fragColor} = $rt->construct(4, 0.0);
    $clamp01__float = sub {
        my ($x) = @_;
        return $rt->component_wise('clamp', $x, $rt->f(0), $rt->f(1));
    };
    $blendOverlay__float_float = sub {
        my ($a, $b) = @_;
        return (($rt->binary('<', $a, $rt->f(0.5))) ? ($rt->binary('*', $rt->binary('*', $rt->f(2), $a, 1, 'float'), $b, 1, 'float')) : ($rt->binary('-', $rt->f(1), $rt->binary('*', $rt->binary('*', $rt->f(2), $rt->binary('-', $rt->f(1), $a, 1, 'float'), 1, 'float'), $rt->binary('-', $rt->f(1), $b, 1, 'float'), 1, 'float'), 1, 'float')));
    };
    $blendSoftLight__float_float = sub {
        my ($base, $blend) = @_;
        return (($rt->binary('<', $blend, $rt->f(0.5))) ? ($rt->binary('+', $rt->binary('*', $rt->binary('*', $rt->f(2), $base, 1, 'float'), $blend, 1, 'float'), $rt->binary('*', $rt->binary('*', $base, $base, 1, 'float'), $rt->binary('-', $rt->f(1), $rt->binary('*', $rt->f(2), $blend, 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->component_wise('sqrt', $base), $rt->binary('-', $rt->binary('*', $rt->f(2), $blend, 1, 'float'), $rt->f(1), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $rt->f(2), $base, 1, 'float'), $rt->binary('-', $rt->f(1), $blend, 1, 'float'), 1, 'float'), 1, 'float')));
    };
    $applyBlendMode__vec4_vec4_int = sub {
        my ($color1, $color2, $m) = @_;
        $color1 = $rt->copy($color1, 'float');
        $color2 = $rt->copy($color2, 'float');
        if ($rt->binary('==', $m, $rt->i(0))) {
            return $rt->component_wise('min', $rt->binary('+', $color1, $color2, 4, 'float'), $rt->construct(4, $rt->f(1)));
        }
        if ($rt->binary('==', $m, $rt->i(1))) {
            return $rt->binary('-', $rt->f(1), $rt->component_wise('min', $rt->binary('/', $rt->binary('-', $rt->f(1), $color1, 4, 'float'), $rt->component_wise('max', $color2, $rt->construct(4, $rt->f(0.001))), 4, 'float'), $rt->construct(4, $rt->f(1))), 4, 'float');
        }
        if ($rt->binary('==', $m, $rt->i(2))) {
            return $rt->component_wise('min', $color1, $color2);
        }
        if ($rt->binary('==', $m, $rt->i(3))) {
            return $rt->component_wise('abs', $rt->binary('-', $color1, $color2, 4, 'float'));
        }
        if ($rt->binary('==', $m, $rt->i(4))) {
            return $rt->component_wise('min', $rt->binary('/', $color1, $rt->component_wise('max', $rt->binary('-', $rt->f(1), $color2, 4, 'float'), $rt->construct(4, $rt->f(0.001))), 4, 'float'), $rt->construct(4, $rt->f(1)));
        }
        if ($rt->binary('==', $m, $rt->i(5))) {
            return $rt->binary('-', $rt->binary('+', $color1, $color2, 4, 'float'), $rt->binary('*', $rt->binary('*', $rt->f(2), $color1, 4, 'float'), $color2, 4, 'float'), 4, 'float');
        }
        if ($rt->binary('==', $m, $rt->i(6))) {
            return $rt->construct(4, $blendOverlay__float_float->($rt->swizzle($color2, 'r'), $rt->swizzle($color1, 'r')), $blendOverlay__float_float->($rt->swizzle($color2, 'g'), $rt->swizzle($color1, 'g')), $blendOverlay__float_float->($rt->swizzle($color2, 'b'), $rt->swizzle($color1, 'b')), $rt->f(1));
        }
        if ($rt->binary('==', $m, $rt->i(7))) {
            return $rt->component_wise('max', $color1, $color2);
        }
        if ($rt->binary('==', $m, $rt->i(8))) {
            return $color2;
        }
        if ($rt->binary('==', $m, $rt->i(9))) {
            return $rt->binary('*', $color1, $color2, 4, 'float');
        }
        if ($rt->binary('==', $m, $rt->i(10))) {
            return $rt->binary('-', $rt->construct(4, $rt->f(1)), $rt->component_wise('abs', $rt->binary('-', $rt->binary('-', $rt->construct(4, $rt->f(1)), $color1, 4, 'float'), $color2, 4, 'float')), 4, 'float');
        }
        if ($rt->binary('==', $m, $rt->i(11))) {
            return $rt->construct(4, $blendOverlay__float_float->($rt->swizzle($color1, 'r'), $rt->swizzle($color2, 'r')), $blendOverlay__float_float->($rt->swizzle($color1, 'g'), $rt->swizzle($color2, 'g')), $blendOverlay__float_float->($rt->swizzle($color1, 'b'), $rt->swizzle($color2, 'b')), $rt->f(1));
        }
        if ($rt->binary('==', $m, $rt->i(12))) {
            return $rt->binary('+', $rt->binary('-', $rt->component_wise('min', $color1, $color2), $rt->component_wise('max', $color1, $color2), 4, 'float'), $rt->construct(4, $rt->f(1)), 4, 'float');
        }
        if ($rt->binary('==', $m, $rt->i(13))) {
            return $rt->binary('-', $rt->construct(4, $rt->f(1)), $rt->binary('*', $rt->binary('-', $rt->construct(4, $rt->f(1)), $color1, 4, 'float'), $rt->binary('-', $rt->construct(4, $rt->f(1)), $color2, 4, 'float'), 4, 'float'), 4, 'float');
        }
        if ($rt->binary('==', $m, $rt->i(14))) {
            return $rt->construct(4, $blendSoftLight__float_float->($rt->swizzle($color1, 'r'), $rt->swizzle($color2, 'r')), $blendSoftLight__float_float->($rt->swizzle($color1, 'g'), $rt->swizzle($color2, 'g')), $blendSoftLight__float_float->($rt->swizzle($color1, 'b'), $rt->swizzle($color2, 'b')), $rt->f(1));
        }
        return $rt->component_wise('max', $rt->binary('-', $color1, $color2, 4, 'float'), $rt->construct(4, $rt->f(0)));
    };
    $distanceMetric__vec2_vec2_int = sub {
        my ($p, $corner, $m) = @_;
        $p = $rt->copy($p, 'float');
        $corner = $rt->copy($corner, 'float');
        my ($ap, $d, $maxD, $mm);
        $mm = $rt->binary('%', $m, $rt->i(3), 1, 'int');
        if ($rt->binary('<', $mm, $rt->i(0))) {
            $mm = $rt->binary('+', $mm, $rt->i(3), 1, 'int');
        }
        $ap = $rt->component_wise('abs', $p);
        $d = $rt->f(0.0);
        $maxD = $rt->f(0.0);
        if ($rt->binary('==', $mm, $rt->i(0))) {
            $d = $rt->length($ap);
            $maxD = $rt->length($corner);
            return $rt->binary('/', $d, $maxD, 1, 'float');
        }
        if ($rt->binary('==', $mm, $rt->i(1))) {
            $d = $rt->binary('+', $rt->swizzle($ap, 'x'), $rt->swizzle($ap, 'y'), 1, 'float');
            $maxD = $rt->binary('+', $rt->swizzle($corner, 'x'), $rt->swizzle($corner, 'y'), 1, 'float');
            return $rt->binary('/', $d, $maxD, 1, 'float');
        }
        $d = $rt->component_wise('max', $rt->swizzle($ap, 'x'), $rt->swizzle($ap, 'y'));
        $maxD = $rt->component_wise('max', $rt->swizzle($corner, 'x'), $rt->swizzle($corner, 'y'));
        return $rt->binary('/', $d, $maxD, 1, 'float');
    };
    $main__void = sub {
        my ($blended, $centerColor, $color, $corner, $dist01, $edgeColor, $f_high, $f_low, $globalCoord, $h, $mask, $minRes, $p, $scaledPower, $st, $width);
        $st = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        $edgeColor = $rt->texture($_u_inputTex, $st);
        $centerColor = $rt->texture($_u_tex, $st);
        $minRes = $rt->component_wise('min', $rt->swizzle($_u_fullResolution, 'x'), $rt->swizzle($_u_fullResolution, 'y'));
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $p = $rt->binary('/', $rt->binary('-', $globalCoord, $rt->binary('*', $rt->f(0.5), $_u_fullResolution, 2, 'float'), 2, 'float'), $rt->binary('*', $rt->f(0.5), $minRes, 1, 'float'), 2, 'float');
        $corner = $rt->binary('/', $_u_fullResolution, $minRes, 2, 'float');
        $dist01 = $clamp01__float->($distanceMetric__vec2_vec2_int->($p, $corner, $_u_shape));
        $scaledPower = $rt->component_wise('mix', $rt->f(0.10000000000000001), $rt->f(25.050000000000001), $rt->binary('/', $rt->binary('+', $_u_power, $rt->f(100), 1, 'float'), $rt->f(200), 1, 'float'));
        $mask = $rt->component_wise('pow', $dist01, $scaledPower);
        $h = $rt->component_wise('clamp', $rt->binary('/', $_u_hardness, $rt->f(100), 1, 'float'), $rt->f(0), $rt->f(0.995));
        $width = $rt->binary('*', $rt->binary('-', $rt->f(1), $h, 1, 'float'), $rt->f(0.5), 1, 'float');
        $mask = $rt->component_wise('smoothstep', $rt->binary('-', $rt->f(0.5), $width, 1, 'float'), $rt->binary('+', $rt->f(0.5), $width, 1, 'float'), $mask);
        $f_low = $rt->component_wise('clamp', $rt->binary('/', $rt->binary('+', $_u_power, $rt->f(100), 1, 'float'), $rt->f(5), 1, 'float'), $rt->f(0), $rt->f(1));
        $f_high = $rt->component_wise('clamp', $rt->binary('/', $rt->binary('-', $rt->f(100), $_u_power, 1, 'float'), $rt->f(5), 1, 'float'), $rt->f(0), $rt->f(1));
        $mask = $rt->component_wise('mix', $rt->f(1), $mask, $f_low);
        $mask = $rt->binary('*', $mask, $f_high, 1, 'float');
        $blended = $applyBlendMode__vec4_vec4_int->($centerColor, $edgeColor, $_u_blendMode);
        $color = $rt->component_wise('mix', $centerColor, $blended, $mask);
        $color = $rt->assign_swizzle($color, 'a', $rt->component_wise('max', $rt->swizzle($edgeColor, 'a'), $rt->swizzle($centerColor, 'a')));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
