# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($getLuminosity__vec3, $computeBlurFactor__float, $applyFocusBlur__sampler2D_sampler2D_vec2, $main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_tex = $ctx->texture_binding('tex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_focalDistance = exists $U->{'focalDistance'} ? $U->{'focalDistance'} : $rt->f(0.0);
    my $_u_aperture = exists $U->{'aperture'} ? $U->{'aperture'} : $rt->f(0.0);
    my $_u_sampleBias = exists $U->{'sampleBias'} ? $U->{'sampleBias'} : $rt->f(0.0);
    my $_u_depthSource = exists $U->{'depthSource'} ? $U->{'depthSource'} : 0;
    $g->{fragColor} = $rt->construct(4, 0.0);
    $getLuminosity__vec3 = sub {
        my ($color) = @_;
        $color = $rt->copy($color, 'float');
        return $rt->dot($color, $rt->construct(3, $rt->f(0.21260000000000001), $rt->f(0.71519999999999995), $rt->f(0.0722)));
    };
    $computeBlurFactor__float = sub {
        my ($depth) = @_;
        my ($blur, $focalPlane);
        $focalPlane = $rt->binary('*', $_u_focalDistance, $rt->f(0.01), 1, 'float');
        $blur = $rt->binary('*', $rt->component_wise('abs', $rt->binary('-', $depth, $focalPlane, 1, 'float')), $_u_aperture, 1, 'float');
        return $rt->component_wise('clamp', $blur, $rt->f(0), $rt->f(1));
    };
    $applyFocusBlur__sampler2D_sampler2D_vec2 = sub {
        my ($sceneTex, $depthTex, $uv) = @_;
        $uv = $rt->copy($uv, 'float');
        my ($GOLDEN, $_for0_first, $blurRadius, $color, $depth, $depthSample, $i, $offset, $r, $theta);
        $depthSample = $rt->texture($depthTex, $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($depthTex)), 2, 'float'));
        $depth = $getLuminosity__vec3->($rt->swizzle($depthSample, 'rgb'));
        $blurRadius = $rt->binary('*', $computeBlurFactor__float->($depth), $_u_sampleBias, 1, 'float');
        $color = $rt->construct(4, $rt->f(0));
        $GOLDEN = $rt->f(2.3999630000000001);
        $i = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $i, $rt->i(64)))) {
                last;
            }
            $r = $rt->component_wise('sqrt', $rt->binary('/', $rt->construct(1, $i), $rt->f(64), 1, 'float'));
            $theta = $rt->binary('*', $rt->construct(1, $i), $GOLDEN, 1, 'float');
            $offset = $rt->binary('/', $rt->binary('*', $rt->binary('*', $rt->construct(2, $rt->component_wise('cos', $theta), $rt->component_wise('sin', $theta)), $r, 2, 'float'), $blurRadius, 2, 'float'), $_u_resolution, 2, 'float');
            @{$color} = map { $rt->f32($_) } @{($rt->binary('+', $color, $rt->texture($sceneTex, $rt->binary('/', $rt->binary('-', $rt->binary('*', $rt->binary('+', $uv, $offset, 2, 'float'), $_u_fullResolution, 2, 'float'), $_u_tileOffset, 2, 'float'), $rt->construct(2, $rt->texture_size($sceneTex)), 2, 'float')), 4, 'float'))};
        }
        return $rt->binary('/', $color, $rt->f(64), 4, 'float');
    };
    $main__void = sub {
        my ($color, $globalCoord, $uv);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $uv = $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float');
        $color = $rt->construct(4, 0.0);
        if ($rt->binary('==', $_u_depthSource, $rt->i(0))) {
            @{$color} = map { $rt->f32($_) } @{($applyFocusBlur__sampler2D_sampler2D_vec2->($_u_tex, $_u_inputTex, $uv))};
        } else {
            @{$color} = map { $rt->f32($_) } @{($applyFocusBlur__sampler2D_sampler2D_vec2->($_u_inputTex, $_u_tex, $uv))};
        }
        $color = $rt->assign_swizzle($color, 'a', $rt->component_wise('max', $rt->swizzle($rt->texture($_u_inputTex, $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($_u_inputTex)), 2, 'float')), 'a'), $rt->swizzle($rt->texture($_u_tex, $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $rt->construct(2, $rt->texture_size($_u_tex)), 2, 'float')), 'a')));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
