# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash_uint__uint, $hash__uint, $rand__float, $randomDirection__float, $wrap01__vec2, $sampleGrid__vec2, $neighborhood__vec2_float, $main__void);
    my $_retc;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_frame = exists $U->{'frame'} ? $U->{'frame'} : 0;
    my $_u_stride = exists $U->{'stride'} ? $U->{'stride'} : $rt->f(0.0);
    my $_u_inputWeight = exists $U->{'inputWeight'} ? $U->{'inputWeight'} : $rt->f(0.0);
    my $_u_attrition = exists $U->{'attrition'} ? $U->{'attrition'} : $rt->f(0.0);
    my $_u_stateSize = exists $U->{'stateSize'} ? $U->{'stateSize'} : 0;
    my $_u_resetState = exists $U->{'resetState'} ? $U->{'resetState'} : 0;
    my $_u_xyzTex = $ctx->texture_binding('xyzTex');
    my $_u_velTex = $ctx->texture_binding('velTex');
    my $_u_rgbaTex = $ctx->texture_binding('rgbaTex');
    my $_u_gridTex = $ctx->texture_binding('gridTex');
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    $g->{outXYZ} = $rt->construct(4, 0.0);
    $g->{outVel} = $rt->construct(4, 0.0);
    $g->{outRGBA} = $rt->construct(4, 0.0);
    $hash_uint__uint = sub {
        my ($seed) = @_;
        my ($state, $word);
        $state = $rt->binary('+', $rt->binary('*', $seed, $rt->i(747796405), 1, 'uint'), $rt->i(2891336453), 1, 'uint');
        $word = $rt->binary('*', $rt->binary('^', $rt->binary('>>', $state, $rt->binary('+', $rt->binary('>>', $state, $rt->i(28), 1, 'uint'), $rt->i(4), 1, 'uint'), 1, 'uint'), $state, 1, 'uint'), $rt->i(277803737), 1, 'uint');
        return $rt->binary('^', $rt->binary('>>', $word, $rt->i(22), 1, 'uint'), $word, 1, 'uint');
    };
    $hash__uint = sub {
        my ($seed) = @_;
        return $rt->binary('/', $rt->construct(1, $rt->hash_uint($seed)), $rt->f(4294967295), 1, 'float');
    };
    $rand__float = sub {
        my ($seed) = @_;
        my ($bits);
        $bits = $rt->float_bits_to_uint($seed);
        $bits = $rt->hash_uint($bits);
        $seed = $rt->binary('-', $rt->uint_bits_to_float($rt->binary('|', $bits, $rt->i(1065353216), 1, 'uint')), $rt->f(1), 1, 'float');
        $bits = $rt->hash_uint($rt->binary('+', $bits, $rt->i(1), 1, 'uint'));
        $seed = $rt->binary('-', $rt->uint_bits_to_float($rt->binary('|', $rt->binary('&', $bits, $rt->i(8388607), 1, 'uint'), $rt->i(1065353216), 1, 'uint')), $rt->f(1), 1, 'float');
        return ($seed, $seed);
        return (undef, $seed);
    };
    $randomDirection__float = sub {
        my ($seed) = @_;
        my ($theta);
        $theta = $rt->binary('*', do { ($_retc, $seed) = $rand__float->($seed); $_retc }, $rt->f(6.2831853071800001), 1, 'float');
        return ($rt->construct(2, $rt->component_wise('cos', $theta), $rt->component_wise('sin', $theta)), $seed);
        return (undef, $seed);
    };
    $wrap01__vec2 = sub {
        my ($v) = @_;
        $v = $rt->copy($v, 'float');
        return $rt->component_wise('fract', $rt->component_wise('max', $v, $rt->f(0)));
    };
    $sampleGrid__vec2 = sub {
        my ($uv) = @_;
        $uv = $rt->copy($uv, 'float');
        my ($coord, $dims);
        $dims = $rt->texture_size($_u_gridTex);
        $coord = $rt->construct(2, $rt->binary('*', $wrap01__vec2->($uv), $rt->construct(2, $dims), 2, 'float'), 'int');
        return $rt->swizzle($rt->texel_fetch($_u_gridTex, $coord, $rt->i(0)), 'a');
    };
    $neighborhood__vec2_float = sub {
        my ($uv, $radius) = @_;
        $uv = $rt->copy($uv, 'float');
        my ($accum, $gridDims, $texel);
        $gridDims = $rt->construct(2, $rt->texture_size($_u_gridTex));
        $texel = $rt->binary('/', $radius, $gridDims, 2, 'float');
        $accum = $rt->f(0);
        $accum = $rt->binary('+', $accum, $sampleGrid__vec2->($uv), 1, 'float');
        $accum = $rt->binary('+', $accum, $sampleGrid__vec2->($rt->binary('+', $uv, $rt->construct(2, $rt->swizzle($texel, 'x'), $rt->f(0)), 2, 'float')), 1, 'float');
        $accum = $rt->binary('+', $accum, $sampleGrid__vec2->($rt->binary('-', $uv, $rt->construct(2, $rt->swizzle($texel, 'x'), $rt->f(0)), 2, 'float')), 1, 'float');
        $accum = $rt->binary('+', $accum, $sampleGrid__vec2->($rt->binary('+', $uv, $rt->construct(2, $rt->f(0), $rt->swizzle($texel, 'y')), 2, 'float')), 1, 'float');
        $accum = $rt->binary('+', $accum, $sampleGrid__vec2->($rt->binary('-', $uv, $rt->construct(2, $rt->f(0), $rt->swizzle($texel, 'y')), 2, 'float')), 1, 'float');
        return $rt->binary('*', $accum, $rt->f(0.20000000000000001), 1, 'float');
    };
    $main__void = sub {
        my ($agentId, $agentRand, $alive, $attritionRate, $candidate, $coord, $frameSeed, $gridDims, $here, $inputCoord, $inputDims, $inputDir, $inputVal, $inputW, $local, $nearby, $needsRespawn, $pos, $proximity, $randomDir, $rgba, $seed, $stateDims, $stepDir, $stepSize, $stuck, $texel, $vel, $xyz);
        $coord = $rt->construct(2, $rt->swizzle($ctx->{frag_coord}, 'xy'), 'int');
        $stateDims = $rt->texture_size($_u_xyzTex);
        $xyz = $rt->texel_fetch($_u_xyzTex, $coord, $rt->i(0));
        $vel = $rt->texel_fetch($_u_velTex, $coord, $rt->i(0));
        $rgba = $rt->texel_fetch($_u_rgbaTex, $coord, $rt->i(0));
        $pos = $rt->swizzle($xyz, 'xy');
        $alive = $rt->swizzle($xyz, 'w');
        $seed = $rt->swizzle($vel, 'x');
        $agentRand = $rt->swizzle($vel, 'w');
        $agentId = $rt->construct(1, $rt->binary('+', $rt->swizzle($coord, 'x'), $rt->binary('*', $rt->swizzle($coord, 'y'), $rt->swizzle($stateDims, 'x'), 1, 'int'), 1, 'int'), 'uint');
        if ($rt->binary('<=', $seed, $rt->f(0))) {
            $seed = $rt->binary('+', $hash__uint->($agentId), $rt->f(0.001), 1, 'float');
        }
        $frameSeed = $rt->hash_uint($rt->binary('+', $rt->binary('*', $agentId, $rt->i(31), 1, 'uint'), $rt->float_bits_to_uint($seed), 1, 'uint'));
        $seed = $rt->binary('-', $rt->uint_bits_to_float($rt->binary('|', $rt->binary('&', $frameSeed, $rt->i(8388607), 1, 'uint'), $rt->i(1065353216), 1, 'uint')), $rt->f(1), 1, 'float');
        if ($rt->binary('<', $alive, $rt->f(0.5))) {
            @{$g->{outXYZ}} = map { $rt->f32($_) } @{($xyz)};
            @{$g->{outVel}} = map { $rt->f32($_) } @{($rt->construct(4, $seed, $rt->f(0), $rt->f(0), $agentRand))};
            @{$g->{outRGBA}} = map { $rt->f32($_) } @{($rgba)};
            return;
        }
        $gridDims = $rt->construct(2, $rt->texture_size($_u_gridTex));
        $texel = $rt->binary('/', $rt->f(1), $rt->component_wise('max', $rt->swizzle($gridDims, 'x'), $rt->swizzle($gridDims, 'y')), 1, 'float');
        $local = $neighborhood__vec2_float->($pos, $rt->f(2));
        $proximity = $rt->component_wise('smoothstep', $rt->f(0.014999999999999999), $rt->f(0.12), $local);
        $randomDir = do { ($_retc, $seed) = $randomDirection__float->($seed); $_retc };
        $inputW = $rt->binary('/', $_u_inputWeight, $rt->f(100), 1, 'float');
        $stepDir = $randomDir;
        $inputCoord = $rt->construct(2, 0.0, 'int');
        $inputDims = $rt->construct(2, 0.0, 'int');
        $inputDir = $rt->construct(2, 0.0);
        $inputVal = $rt->construct(4, 0.0);
        if ($rt->binary('>', $inputW, $rt->f(0))) {
            $inputDims = $rt->texture_size($_u_inputTex);
            $inputCoord = $rt->construct(2, $rt->binary('*', $wrap01__vec2->($pos), $rt->construct(2, $inputDims), 2, 'float'), 'int');
            $inputVal = $rt->texel_fetch($_u_inputTex, $inputCoord, $rt->i(0));
            $inputDir = $rt->binary('-', $rt->binary('*', $rt->swizzle($inputVal, 'xy'), $rt->f(2), 2, 'float'), $rt->f(1), 2, 'float');
            if ($rt->binary('>', $rt->length($inputDir), $rt->f(0.01))) {
                @{$inputDir} = map { $rt->f32($_) } @{($rt->normalize($inputDir))};
                @{$stepDir} = map { $rt->f32($_) } @{($rt->normalize($rt->component_wise('mix', $randomDir, $inputDir, $inputW)))};
            }
        }
        $stepSize = $rt->binary('*', $rt->binary('*', $rt->binary('/', $_u_stride, $rt->f(10), 1, 'float'), $texel, 1, 'float'), $rt->component_wise('mix', $rt->f(3), $rt->f(0.5), $proximity), 1, 'float');
        @{$stepDir} = map { $rt->f32($_) } @{($rt->binary('+', $stepDir, $rt->binary('*', do { ($_retc, $seed) = $randomDirection__float->($seed); $_retc }, $rt->f(0.29999999999999999), 2, 'float'), 2, 'float'))};
        @{$stepDir} = map { $rt->f32($_) } @{($rt->normalize($stepDir))};
        $candidate = $wrap01__vec2->($rt->binary('+', $pos, $rt->binary('*', $stepDir, $stepSize, 2, 'float'), 2, 'float'));
        $here = $sampleGrid__vec2->($candidate);
        $nearby = $neighborhood__vec2_float->($candidate, $rt->f(1));
        $stuck = (($rt->binary('>', $nearby, $rt->f(0.29999999999999999))) && ($rt->binary('<', $here, $rt->f(0.5))) ? 1 : 0);
        $needsRespawn = 0;
        $attritionRate = $rt->f(0.0);
        if ($rt->binary('>', $_u_attrition, $rt->f(0))) {
            $attritionRate = $rt->binary('*', $_u_attrition, $rt->f(0.01), 1, 'float');
            if ($rt->binary('<', do { ($_retc, $seed) = $rand__float->($seed); $_retc }, $attritionRate)) {
                $needsRespawn = 1;
            }
        }
        if ($stuck) {
            @{$g->{outXYZ}} = map { $rt->f32($_) } @{($rt->construct(4, $candidate, $rt->f(0), $rt->f(0)))};
            @{$g->{outVel}} = map { $rt->f32($_) } @{($rt->construct(4, $seed, $rt->f(1), $rt->f(0), $agentRand))};
            @{$g->{outRGBA}} = map { $rt->f32($_) } @{($rgba)};
        } else {
            if ($needsRespawn) {
                @{$g->{outXYZ}} = map { $rt->f32($_) } @{($rt->construct(4, $candidate, $rt->f(0), $rt->f(0)))};
                @{$g->{outVel}} = map { $rt->f32($_) } @{($rt->construct(4, $seed, $rt->f(0), $rt->f(0), $agentRand))};
                @{$g->{outRGBA}} = map { $rt->f32($_) } @{($rgba)};
            } else {
                @{$g->{outXYZ}} = map { $rt->f32($_) } @{($rt->construct(4, $candidate, $rt->f(0), $rt->f(1)))};
                @{$g->{outVel}} = map { $rt->f32($_) } @{($rt->construct(4, $seed, $rt->f(0), $rt->f(0), $agentRand))};
                @{$g->{outRGBA}} = map { $rt->f32($_) } @{($rgba)};
            }
        }
    };
    $main__void->();
    my $_c0 = $g->{outXYZ};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
    my $_c1 = $g->{outVel};
    $out->[4] = $rt->f32($_c1->[0]); $out->[5] = $rt->f32($_c1->[1]); $out->[6] = $rt->f32($_c1->[2]); $out->[7] = $rt->f32($_c1->[3]);
    my $_c2 = $g->{outRGBA};
    $out->[8] = $rt->f32($_c2->[0]); $out->[9] = $rt->f32($_c2->[1]); $out->[10] = $rt->f32($_c2->[2]); $out->[11] = $rt->f32($_c2->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['outXYZ', 'outVel', 'outRGBA'] };
