# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash_uint__uint, $hash__uint, $main__void);
    my $_retc;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_typeCount = exists $U->{'typeCount'} ? $U->{'typeCount'} : 0;
    my $_u_matrixSeed = exists $U->{'matrixSeed'} ? $U->{'matrixSeed'} : $rt->f(0.0);
    my $_u_symmetricForces = exists $U->{'symmetricForces'} ? $U->{'symmetricForces'} : 0;
    $g->{fragColor} = $rt->construct(4, 0.0);
    $hash_uint__uint = sub {
        my ($seed) = @_;
        my ($state, $word);
        $state = $rt->binary('+', $rt->binary('*', $seed, $rt->i(747796405), 1, 'uint'), $rt->i(2891336453), 1, 'uint');
        $word = $rt->binary('*', $rt->binary('^', $rt->binary('>>', $state, $rt->binary('+', $rt->binary('>>', $state, $rt->i(28), 1, 'uint'), $rt->i(4), 1, 'uint'), 1, 'uint'), $state, 1, 'uint'), $rt->i(277803737), 1, 'uint');
        return $rt->binary('^', $rt->binary('>>', $word, $rt->i(22), 1, 'uint'), $word, 1, 'uint');
    };
    $hash__uint = sub {
        my ($seed) = @_;
        return $rt->binary('/', $rt->construct(1, $rt->hash_uint($seed)), $rt->f(4294967295), 1, 'float');
    };
    $main__void = sub {
        my ($coord, $curveShape, $prefDist, $seed, $strength, $typeA, $typeB);
        $coord = $rt->construct(2, $rt->swizzle($ctx->{frag_coord}, 'xy'), 'int');
        $typeA = $rt->swizzle($coord, 'x');
        $typeB = $rt->swizzle($coord, 'y');
        if ((($rt->binary('>=', $typeA, $_u_typeCount)) || ($rt->binary('>=', $typeB, $_u_typeCount)) ? 1 : 0)) {
            @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->f(0)))};
            return;
        }
        $seed = $rt->binary('+', $rt->construct(1, $rt->binary('*', $_u_matrixSeed, $rt->f(1000), 1, 'float'), 'uint'), $rt->construct(1, $rt->binary('+', $rt->binary('*', $typeA, $rt->i(31), 1, 'int'), $rt->binary('*', $typeB, $rt->i(17), 1, 'int'), 1, 'int'), 'uint'), 1, 'uint');
        if ((($_u_symmetricForces) && ($rt->binary('<', $typeB, $typeA)) ? 1 : 0)) {
            $seed = $rt->binary('+', $rt->construct(1, $rt->binary('*', $_u_matrixSeed, $rt->f(1000), 1, 'float'), 'uint'), $rt->construct(1, $rt->binary('+', $rt->binary('*', $typeB, $rt->i(31), 1, 'int'), $rt->binary('*', $typeA, $rt->i(17), 1, 'int'), 1, 'int'), 'uint'), 1, 'uint');
        }
        $strength = $rt->f(0.0);
        if ($rt->binary('==', $typeA, $typeB)) {
            $strength = $rt->binary('-', $rt->unary('-', $rt->f(0.29999999999999999)), $rt->binary('*', $hash__uint->($seed), $rt->f(0.40000000000000002), 1, 'float'), 1, 'float');
        } else {
            $strength = $rt->binary('-', $rt->binary('*', $hash__uint->($seed), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float');
        }
        $prefDist = $rt->binary('+', $rt->f(0.29999999999999999), $rt->binary('*', $hash__uint->($rt->binary('+', $seed, $rt->i(1), 1, 'uint')), $rt->f(0.5), 1, 'float'), 1, 'float');
        $curveShape = $hash__uint->($rt->binary('+', $seed, $rt->i(2), 1, 'uint'));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $strength, $prefDist, $curveShape, $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
