# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash_uint__uint, $hash__uint, $hash2__uint, $typeColor__int_int, $getGridCell__vec2, $radialForce__float_float_float_float, $wrapPosition__vec2, $limitVec__vec2_float, $main__void);
    my $_retc;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_typeCount = exists $U->{'typeCount'} ? $U->{'typeCount'} : 0;
    my $_u_attractionScale = exists $U->{'attractionScale'} ? $U->{'attractionScale'} : $rt->f(0.0);
    my $_u_repulsionScale = exists $U->{'repulsionScale'} ? $U->{'repulsionScale'} : $rt->f(0.0);
    my $_u_minRadius = exists $U->{'minRadius'} ? $U->{'minRadius'} : $rt->f(0.0);
    my $_u_maxRadius = exists $U->{'maxRadius'} ? $U->{'maxRadius'} : $rt->f(0.0);
    my $_u_maxSpeed = exists $U->{'maxSpeed'} ? $U->{'maxSpeed'} : $rt->f(0.0);
    my $_u_friction = exists $U->{'friction'} ? $U->{'friction'} : $rt->f(0.0);
    my $_u_boundaryMode = exists $U->{'boundaryMode'} ? $U->{'boundaryMode'} : 0;
    my $_u_matrixSeed = exists $U->{'matrixSeed'} ? $U->{'matrixSeed'} : $rt->f(0.0);
    my $_u_symmetricForces = exists $U->{'symmetricForces'} ? $U->{'symmetricForces'} : 0;
    my $_u_useTypeColor = exists $U->{'useTypeColor'} ? $U->{'useTypeColor'} : 0;
    my $_u_xyzTex = $ctx->texture_binding('xyzTex');
    my $_u_velTex = $ctx->texture_binding('velTex');
    my $_u_rgbaTex = $ctx->texture_binding('rgbaTex');
    my $_u_dataTex = $ctx->texture_binding('dataTex');
    my $_u_forceMatrix = $ctx->texture_binding('forceMatrix');
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    $g->{outXYZ} = $rt->construct(4, 0.0);
    $g->{outVel} = $rt->construct(4, 0.0);
    $g->{outRGBA} = $rt->construct(4, 0.0);
    $g->{outData} = $rt->construct(4, 0.0);
    $g->{GRID_SIZE} = $rt->i(16);
    $hash_uint__uint = sub {
        my ($seed) = @_;
        my ($state, $word);
        $state = $rt->binary('+', $rt->binary('*', $seed, $rt->i(747796405), 1, 'uint'), $rt->i(2891336453), 1, 'uint');
        $word = $rt->binary('*', $rt->binary('^', $rt->binary('>>', $state, $rt->binary('+', $rt->binary('>>', $state, $rt->i(28), 1, 'uint'), $rt->i(4), 1, 'uint'), 1, 'uint'), $state, 1, 'uint'), $rt->i(277803737), 1, 'uint');
        return $rt->binary('^', $rt->binary('>>', $word, $rt->i(22), 1, 'uint'), $word, 1, 'uint');
    };
    $hash__uint = sub {
        my ($seed) = @_;
        return $rt->binary('/', $rt->construct(1, $rt->hash_uint($seed)), $rt->f(4294967295), 1, 'float');
    };
    $hash2__uint = sub {
        my ($seed) = @_;
        return $rt->construct(2, $hash__uint->($seed), $hash__uint->($rt->binary('+', $seed, $rt->i(1), 1, 'uint')));
    };
    $typeColor__int_int = sub {
        my ($typeId, $totalTypes) = @_;
        my ($c, $h, $hue, $rgb, $x);
        $hue = $rt->binary('/', $rt->construct(1, $typeId), $rt->construct(1, $totalTypes), 1, 'float');
        $h = $rt->binary('*', $hue, $rt->f(6), 1, 'float');
        $c = $rt->f(1);
        $x = $rt->binary('*', $c, $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->component_wise('mod', $h, $rt->f(2)), $rt->f(1), 1, 'float')), 1, 'float'), 1, 'float');
        $rgb = $rt->construct(3, 0.0);
        if ($rt->binary('<', $h, $rt->f(1))) {
            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $x, $rt->f(0)))};
        } else {
            if ($rt->binary('<', $h, $rt->f(2))) {
                @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $c, $rt->f(0)))};
            } else {
                if ($rt->binary('<', $h, $rt->f(3))) {
                    @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $c, $x))};
                } else {
                    if ($rt->binary('<', $h, $rt->f(4))) {
                        @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $x, $c))};
                    } else {
                        if ($rt->binary('<', $h, $rt->f(5))) {
                            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $x, $rt->f(0), $c))};
                        } else {
                            @{$rgb} = map { $rt->f32($_) } @{($rt->construct(3, $c, $rt->f(0), $x))};
                        }
                    }
                }
            }
        }
        return $rgb;
    };
    $getGridCell__vec2 = sub {
        my ($pos) = @_;
        $pos = $rt->copy($pos, 'float');
        my ($cellSize);
        $cellSize = $rt->binary('/', $rt->construct(2, $rt->f(1)), $rt->construct(1, $g->{GRID_SIZE}), 2, 'float');
        return $rt->construct(2, $rt->component_wise('clamp', $rt->binary('/', $pos, $cellSize, 2, 'float'), $rt->construct(2, $rt->f(0)), $rt->construct(2, $rt->construct(1, $rt->binary('-', $g->{GRID_SIZE}, $rt->i(1), 1, 'int')))), 'int');
    };
    $radialForce__float_float_float_float = sub {
        my ($dist, $strength, $prefDist, $curveShape) = @_;
        my ($force, $forceScale, $normDist, $shaped);
        $normDist = $rt->binary('/', $rt->binary('-', $dist, $_u_minRadius, 1, 'float'), $rt->binary('-', $_u_maxRadius, $_u_minRadius, 1, 'float'), 1, 'float');
        $forceScale = $rt->binary('*', $_u_maxSpeed, $rt->f(10), 1, 'float');
        if ($rt->binary('<', $normDist, $rt->f(0))) {
            return $rt->binary('*', $rt->binary('*', $rt->unary('-', $_u_repulsionScale), $rt->binary('-', $rt->f(1), $rt->binary('/', $dist, $_u_minRadius, 1, 'float'), 1, 'float'), 1, 'float'), $forceScale, 1, 'float');
        }
        if ($rt->binary('>', $normDist, $rt->f(1))) {
            return $rt->f(0);
        }
        $force = $rt->f(0.0);
        if ($rt->binary('<', $normDist, $prefDist)) {
            $force = $rt->binary('*', $strength, $rt->binary('/', $normDist, $prefDist, 1, 'float'), 1, 'float');
        } else {
            $force = $rt->binary('*', $strength, $rt->binary('-', $rt->f(1), $rt->binary('/', $rt->binary('-', $normDist, $prefDist, 1, 'float'), $rt->binary('-', $rt->f(1), $prefDist, 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float');
        }
        $shaped = $rt->binary('*', $rt->component_wise('sign', $force), $rt->component_wise('pow', $rt->component_wise('abs', $force), $rt->binary('-', $rt->f(1), $rt->binary('*', $curveShape, $rt->f(0.5), 1, 'float'), 1, 'float')), 1, 'float');
        if ($rt->binary('>', $shaped, $rt->f(0))) {
            return $rt->binary('*', $rt->binary('*', $shaped, $_u_attractionScale, 1, 'float'), $forceScale, 1, 'float');
        } else {
            return $rt->binary('*', $rt->binary('*', $shaped, $_u_repulsionScale, 1, 'float'), $forceScale, 1, 'float');
        }
    };
    $wrapPosition__vec2 = sub {
        my ($pos) = @_;
        $pos = $rt->copy($pos, 'float');
        return $rt->component_wise('mod', $rt->binary('+', $pos, $rt->f(1), 2, 'float'), $rt->f(1));
    };
    $limitVec__vec2_float = sub {
        my ($v, $maxLen) = @_;
        $v = $rt->copy($v, 'float');
        my ($len);
        $len = $rt->length($v);
        if ((($rt->binary('>', $len, $maxLen)) && ($rt->binary('>', $len, $rt->f(0))) ? 1 : 0)) {
            return $rt->binary('*', $v, $rt->binary('/', $maxLen, $len, 1, 'float'), 2, 'float');
        }
        return $v;
    };
    $main__void = sub {
        my ($_for0_first, $_for1_first, $_for2_first, $age, $alive, $angle, $cellSeed, $checkCell, $coord, $curveShape, $data, $diff, $dist, $dx, $dy, $forceDir, $forceMag, $forceParams, $initSeed, $mass, $myCell, $myType, $neighborCount, $otherAlive, $otherData, $otherPos, $otherType, $otherXyz, $particleId, $pos, $prefDist, $px, $py, $rgba, $s, $sampleIdx, $sampleSeed, $seed, $speed, $stateSize, $strength, $sx, $sy, $totalForce, $totalParticles, $typeId, $vel, $velocity, $vx, $vy, $xyz);
        $coord = $rt->construct(2, $rt->swizzle($ctx->{frag_coord}, 'xy'), 'int');
        $stateSize = $rt->texture_size($_u_xyzTex);
        $xyz = $rt->texel_fetch($_u_xyzTex, $coord, $rt->i(0));
        $vel = $rt->texel_fetch($_u_velTex, $coord, $rt->i(0));
        $rgba = $rt->texel_fetch($_u_rgbaTex, $coord, $rt->i(0));
        $data = $rt->texel_fetch($_u_dataTex, $coord, $rt->i(0));
        $px = $rt->swizzle($xyz, 'x');
        $py = $rt->swizzle($xyz, 'y');
        $alive = $rt->swizzle($xyz, 'w');
        $vx = $rt->swizzle($vel, 'x');
        $vy = $rt->swizzle($vel, 'y');
        $age = $rt->swizzle($vel, 'z');
        $seed = $rt->swizzle($vel, 'w');
        $typeId = $rt->swizzle($data, 'x');
        $mass = $rt->swizzle($data, 'y');
        $particleId = $rt->construct(1, $rt->binary('+', $rt->swizzle($coord, 'x'), $rt->binary('*', $rt->swizzle($coord, 'y'), $rt->swizzle($stateSize, 'x'), 1, 'int'), 1, 'int'), 'uint');
        $pos = $rt->construct(2, $px, $py);
        $velocity = $rt->construct(2, $vx, $vy);
        if ($rt->binary('<', $alive, $rt->f(0.5))) {
            @{$g->{outXYZ}} = map { $rt->f32($_) } @{($xyz)};
            @{$g->{outVel}} = map { $rt->f32($_) } @{($vel)};
            @{$g->{outRGBA}} = map { $rt->f32($_) } @{($rgba)};
            @{$g->{outData}} = map { $rt->f32($_) } @{($data)};
            return;
        }
        $initSeed = 0;
        if ((($rt->binary('==', $typeId, $rt->f(0))) && ($rt->binary('==', $mass, $rt->f(0))) ? 1 : 0)) {
            $initSeed = $rt->binary('+', $particleId, $rt->construct(1, $rt->binary('*', $_u_time, $rt->f(1000), 1, 'float'), 'uint'), 1, 'uint');
            $typeId = $rt->component_wise('floor', $rt->binary('*', $hash__uint->($rt->binary('+', $initSeed, $rt->i(4), 1, 'uint')), $rt->construct(1, $_u_typeCount), 1, 'float'));
            $mass = $rt->binary('+', $rt->f(0.80000000000000004), $rt->binary('*', $hash__uint->($rt->binary('+', $initSeed, $rt->i(5), 1, 'uint')), $rt->f(0.40000000000000002), 1, 'float'), 1, 'float');
            $angle = $rt->f(0.0);
            $speed = $rt->f(0.0);
            if ($rt->binary('==', $rt->length($velocity), $rt->f(0))) {
                $angle = $rt->binary('*', $hash__uint->($rt->binary('+', $initSeed, $rt->i(2), 1, 'uint')), $rt->f(6.2831853071800001), 1, 'float');
                $speed = $rt->binary('*', $rt->binary('*', $hash__uint->($rt->binary('+', $initSeed, $rt->i(3), 1, 'uint')), $_u_maxSpeed, 1, 'float'), $rt->f(0.29999999999999999), 1, 'float');
                @{$velocity} = map { $rt->f32($_) } @{($rt->binary('*', $rt->construct(2, $rt->component_wise('cos', $angle), $rt->component_wise('sin', $angle)), $speed, 2, 'float'))};
            }
        }
        $mass = $rt->component_wise('max', $mass, $rt->f(0.10000000000000001));
        $totalForce = $rt->construct(2, $rt->f(0));
        $neighborCount = $rt->i(0);
        $myType = $rt->construct(1, $typeId, 'int');
        $myCell = $getGridCell__vec2->($pos);
        $totalParticles = $rt->binary('*', $rt->swizzle($stateSize, 'x'), $rt->swizzle($stateSize, 'y'), 1, 'int');
        $dy = $rt->unary('-', $rt->i(1));
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $dy = $rt->binary('+', $dy, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<=', $dy, $rt->i(1)))) {
                last;
            }
            $dx = $rt->unary('-', $rt->i(1));
            $_for1_first = 1;
            for my $_for1 (0 .. 1048575) {
                if (!$_for1_first) {
                    $dx = $rt->binary('+', $dx, $rt->i(1), 1, 'int');
                }
                $_for1_first = 0;
                if (!($rt->binary('<=', $dx, $rt->i(1)))) {
                    last;
                }
                $checkCell = $rt->binary('+', $myCell, $rt->construct(2, $dx, $dy, 'int'), 2, 'int');
                @{$checkCell} = @{($rt->binary('%', $rt->binary('+', $checkCell, $g->{GRID_SIZE}, 2, 'int'), $g->{GRID_SIZE}, 2, 'int'))};
                $cellSeed = $rt->construct(1, $rt->binary('+', $rt->binary('*', $rt->swizzle($checkCell, 'y'), $g->{GRID_SIZE}, 1, 'int'), $rt->swizzle($checkCell, 'x'), 1, 'int'), 'uint');
                $s = $rt->i(0);
                $_for2_first = 1;
                for my $_for2 (0 .. 1048575) {
                    if (!$_for2_first) {
                        $s = $rt->binary('+', $s, $rt->i(1), 1, 'int');
                    }
                    $_for2_first = 0;
                    if (!($rt->binary('<', $s, $rt->i(12)))) {
                        last;
                    }
                    $sampleSeed = $rt->binary('+', $rt->binary('+', $rt->binary('*', $cellSeed, $rt->i(31), 1, 'uint'), $rt->construct(1, $s, 'uint'), 1, 'uint'), $rt->construct(1, $rt->binary('*', $_u_time, $rt->f(7), 1, 'float'), 'uint'), 1, 'uint');
                    $sampleIdx = $rt->construct(1, $rt->binary('%', $rt->hash_uint($sampleSeed), $rt->construct(1, $totalParticles, 'uint'), 1, 'uint'), 'int');
                    $sx = $rt->binary('%', $sampleIdx, $rt->swizzle($stateSize, 'x'), 1, 'int');
                    $sy = $rt->binary('/', $sampleIdx, $rt->swizzle($stateSize, 'x'), 1, 'int');
                    if ((($rt->binary('==', $sx, $rt->swizzle($coord, 'x'))) && ($rt->binary('==', $sy, $rt->swizzle($coord, 'y'))) ? 1 : 0)) {
                        next;
                    }
                    $otherXyz = $rt->texel_fetch($_u_xyzTex, $rt->construct(2, $sx, $sy, 'int'), $rt->i(0));
                    $otherData = $rt->texel_fetch($_u_dataTex, $rt->construct(2, $sx, $sy, 'int'), $rt->i(0));
                    $otherPos = $rt->swizzle($otherXyz, 'xy');
                    $otherAlive = $rt->swizzle($otherXyz, 'w');
                    $otherType = $rt->construct(1, $rt->swizzle($otherData, 'x'), 'int');
                    if ($rt->binary('<', $otherAlive, $rt->f(0.5))) {
                        next;
                    }
                    $diff = $rt->binary('-', $otherPos, $pos, 2, 'float');
                    if ($rt->binary('>', $rt->swizzle($diff, 'x'), $rt->f(0.5))) {
                        $diff = $rt->assign_swizzle($diff, 'x', $rt->binary('-', $rt->swizzle($diff, 'x'), $rt->f(1), 1, 'float'));
                    }
                    if ($rt->binary('<', $rt->swizzle($diff, 'x'), $rt->unary('-', $rt->f(0.5)))) {
                        $diff = $rt->assign_swizzle($diff, 'x', $rt->binary('+', $rt->swizzle($diff, 'x'), $rt->f(1), 1, 'float'));
                    }
                    if ($rt->binary('>', $rt->swizzle($diff, 'y'), $rt->f(0.5))) {
                        $diff = $rt->assign_swizzle($diff, 'y', $rt->binary('-', $rt->swizzle($diff, 'y'), $rt->f(1), 1, 'float'));
                    }
                    if ($rt->binary('<', $rt->swizzle($diff, 'y'), $rt->unary('-', $rt->f(0.5)))) {
                        $diff = $rt->assign_swizzle($diff, 'y', $rt->binary('+', $rt->swizzle($diff, 'y'), $rt->f(1), 1, 'float'));
                    }
                    $dist = $rt->length($diff);
                    if ((($rt->binary('<', $dist, $rt->f(0.0001))) || ($rt->binary('>', $dist, $_u_maxRadius)) ? 1 : 0)) {
                        next;
                    }
                    $forceParams = $rt->texel_fetch($_u_forceMatrix, $rt->construct(2, $myType, $otherType, 'int'), $rt->i(0));
                    $strength = $rt->swizzle($forceParams, 'x');
                    $prefDist = $rt->swizzle($forceParams, 'y');
                    $curveShape = $rt->swizzle($forceParams, 'z');
                    $forceMag = $radialForce__float_float_float_float->($dist, $strength, $prefDist, $curveShape);
                    $forceDir = $rt->binary('/', $diff, $dist, 2, 'float');
                    @{$totalForce} = map { $rt->f32($_) } @{($rt->binary('+', $totalForce, $rt->binary('*', $forceDir, $forceMag, 2, 'float'), 2, 'float'))};
                    $neighborCount = $rt->binary('+', $neighborCount, $rt->i(1), 1, 'int');
                }
            }
        }
        @{$totalForce} = map { $rt->f32($_) } @{($rt->binary('/', $totalForce, $mass, 2, 'float'))};
        @{$velocity} = map { $rt->f32($_) } @{($rt->binary('+', $velocity, $totalForce, 2, 'float'))};
        @{$velocity} = map { $rt->f32($_) } @{($rt->binary('*', $velocity, $rt->binary('-', $rt->f(1), $_u_friction, 1, 'float'), 2, 'float'))};
        @{$velocity} = map { $rt->f32($_) } @{($limitVec__vec2_float->($velocity, $_u_maxSpeed))};
        @{$pos} = map { $rt->f32($_) } @{($rt->binary('+', $pos, $velocity, 2, 'float'))};
        if ($rt->binary('==', $_u_boundaryMode, $rt->i(0))) {
            @{$pos} = map { $rt->f32($_) } @{($wrapPosition__vec2->($pos))};
        } else {
            if ($rt->binary('<', $rt->swizzle($pos, 'x'), $rt->f(0))) {
                $pos = $rt->assign_swizzle($pos, 'x', $rt->unary('-', $rt->swizzle($pos, 'x')));
                $velocity = $rt->assign_swizzle($velocity, 'x', $rt->unary('-', $rt->swizzle($velocity, 'x')));
            }
            if ($rt->binary('>', $rt->swizzle($pos, 'x'), $rt->f(1))) {
                $pos = $rt->assign_swizzle($pos, 'x', $rt->binary('-', $rt->f(2), $rt->swizzle($pos, 'x'), 1, 'float'));
                $velocity = $rt->assign_swizzle($velocity, 'x', $rt->unary('-', $rt->swizzle($velocity, 'x')));
            }
            if ($rt->binary('<', $rt->swizzle($pos, 'y'), $rt->f(0))) {
                $pos = $rt->assign_swizzle($pos, 'y', $rt->unary('-', $rt->swizzle($pos, 'y')));
                $velocity = $rt->assign_swizzle($velocity, 'y', $rt->unary('-', $rt->swizzle($velocity, 'y')));
            }
            if ($rt->binary('>', $rt->swizzle($pos, 'y'), $rt->f(1))) {
                $pos = $rt->assign_swizzle($pos, 'y', $rt->binary('-', $rt->f(2), $rt->swizzle($pos, 'y'), 1, 'float'));
                $velocity = $rt->assign_swizzle($velocity, 'y', $rt->unary('-', $rt->swizzle($velocity, 'y')));
            }
            @{$pos} = map { $rt->f32($_) } @{($rt->component_wise('clamp', $pos, $rt->construct(2, $rt->f(0.001)), $rt->construct(2, $rt->f(0.999))))};
        }
        $age = $rt->binary('+', $age, $rt->f(0.016), 1, 'float');
        @{$g->{outXYZ}} = map { $rt->f32($_) } @{($rt->construct(4, $pos, $rt->f(0), $rt->f(1)))};
        @{$g->{outVel}} = map { $rt->f32($_) } @{($rt->construct(4, $velocity, $age, $seed))};
        if ($_u_useTypeColor) {
            @{$g->{outRGBA}} = map { $rt->f32($_) } @{($rt->construct(4, $typeColor__int_int->($rt->construct(1, $typeId, 'int'), $_u_typeCount), $rt->f(1)))};
        } else {
            @{$g->{outRGBA}} = map { $rt->f32($_) } @{($rt->texture($_u_inputTex, $pos))};
        }
        @{$g->{outData}} = map { $rt->f32($_) } @{($rt->construct(4, $typeId, $mass, $rt->f(0), $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{outXYZ};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
    my $_c1 = $g->{outVel};
    $out->[4] = $rt->f32($_c1->[0]); $out->[5] = $rt->f32($_c1->[1]); $out->[6] = $rt->f32($_c1->[2]); $out->[7] = $rt->f32($_c1->[3]);
    my $_c2 = $g->{outRGBA};
    $out->[8] = $rt->f32($_c2->[0]); $out->[9] = $rt->f32($_c2->[1]); $out->[10] = $rt->f32($_c2->[2]); $out->[11] = $rt->f32($_c2->[3]);
    my $_c3 = $g->{outData};
    $out->[12] = $rt->f32($_c3->[0]); $out->[13] = $rt->f32($_c3->[1]); $out->[14] = $rt->f32($_c3->[2]); $out->[15] = $rt->f32($_c3->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['outXYZ', 'outVel', 'outRGBA', 'outData'] };
