# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash_uint__uint, $hash__uint, $lorenz__vec3, $rossler__vec3, $aizawa__vec3, $thomas__vec3, $halvorsen__vec3, $chen__vec3, $dadras__vec3, $stepAttractor__vec3_int_float, $main__void);
    my $_retc;
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_seed = exists $U->{'seed'} ? $U->{'seed'} : 0;
    my $_u_attractor = exists $U->{'attractor'} ? $U->{'attractor'} : 0;
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_xyzTex = $ctx->texture_binding('xyzTex');
    my $_u_velTex = $ctx->texture_binding('velTex');
    my $_u_rgbaTex = $ctx->texture_binding('rgbaTex');
    $g->{outXYZ} = $rt->construct(4, 0.0);
    $g->{outVel} = $rt->construct(4, 0.0);
    $g->{outRGBA} = $rt->construct(4, 0.0);
    $hash_uint__uint = sub {
        my ($seed) = @_;
        my ($state, $word);
        $state = $rt->binary('+', $rt->binary('*', $seed, $rt->i(747796405), 1, 'uint'), $rt->i(2891336453), 1, 'uint');
        $word = $rt->binary('*', $rt->binary('^', $rt->binary('>>', $state, $rt->binary('+', $rt->binary('>>', $state, $rt->i(28), 1, 'uint'), $rt->i(4), 1, 'uint'), 1, 'uint'), $state, 1, 'uint'), $rt->i(277803737), 1, 'uint');
        return $rt->binary('^', $rt->binary('>>', $word, $rt->i(22), 1, 'uint'), $word, 1, 'uint');
    };
    $hash__uint = sub {
        my ($seed) = @_;
        return $rt->binary('/', $rt->construct(1, $rt->hash_uint($seed)), $rt->f(4294967295), 1, 'float');
    };
    $lorenz__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($beta, $rho, $sigma);
        $sigma = $rt->f(10);
        $rho = $rt->f(28);
        $beta = $rt->binary('/', $rt->f(8), $rt->f(3), 1, 'float');
        return $rt->construct(3, $rt->binary('*', $sigma, $rt->binary('-', $rt->swizzle($p, 'y'), $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'), $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->binary('-', $rho, $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->swizzle($p, 'y'), 1, 'float'), $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'y'), 1, 'float'), $rt->binary('*', $beta, $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'));
    };
    $rossler__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($a, $b, $c);
        $a = $rt->f(0.20000000000000001);
        $b = $rt->f(0.20000000000000001);
        $c = $rt->f(5.7000000000000002);
        return $rt->construct(3, $rt->binary('-', $rt->unary('-', $rt->swizzle($p, 'y')), $rt->swizzle($p, 'z'), 1, 'float'), $rt->binary('+', $rt->swizzle($p, 'x'), $rt->binary('*', $a, $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('+', $b, $rt->binary('*', $rt->swizzle($p, 'z'), $rt->binary('-', $rt->swizzle($p, 'x'), $c, 1, 'float'), 1, 'float'), 1, 'float'));
    };
    $aizawa__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($a, $b, $c, $d, $e, $f);
        $a = $rt->f(0.94999999999999996);
        $b = $rt->f(0.69999999999999996);
        $c = $rt->f(0.59999999999999998);
        $d = $rt->f(3.5);
        $e = $rt->f(0.25);
        $f = $rt->f(0.10000000000000001);
        return $rt->construct(3, $rt->binary('-', $rt->binary('*', $rt->binary('-', $rt->swizzle($p, 'z'), $b, 1, 'float'), $rt->swizzle($p, 'x'), 1, 'float'), $rt->binary('*', $d, $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('*', $d, $rt->swizzle($p, 'x'), 1, 'float'), $rt->binary('*', $rt->binary('-', $rt->swizzle($p, 'z'), $b, 1, 'float'), $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->binary('-', $rt->binary('+', $c, $rt->binary('*', $a, $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->binary('/', $rt->binary('*', $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($p, 'z'), 1, 'float'), $rt->swizzle($p, 'z'), 1, 'float'), $rt->f(3), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'x'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->f(1), $rt->binary('*', $e, $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $rt->binary('*', $rt->binary('*', $f, $rt->swizzle($p, 'z'), 1, 'float'), $rt->swizzle($p, 'x'), 1, 'float'), $rt->swizzle($p, 'x'), 1, 'float'), $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'));
    };
    $thomas__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($b);
        $b = $rt->f(0.20818600000000001);
        return $rt->construct(3, $rt->binary('-', $rt->component_wise('sin', $rt->swizzle($p, 'y')), $rt->binary('*', $b, $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'), $rt->binary('-', $rt->component_wise('sin', $rt->swizzle($p, 'z')), $rt->binary('*', $b, $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('-', $rt->component_wise('sin', $rt->swizzle($p, 'x')), $rt->binary('*', $b, $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'));
    };
    $halvorsen__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($a);
        $a = $rt->f(1.8899999999999999);
        return $rt->construct(3, $rt->binary('-', $rt->binary('-', $rt->binary('-', $rt->binary('*', $rt->unary('-', $a), $rt->swizzle($p, 'x'), 1, 'float'), $rt->binary('*', $rt->f(4), $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(4), $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('-', $rt->binary('-', $rt->binary('-', $rt->binary('*', $rt->unary('-', $a), $rt->swizzle($p, 'y'), 1, 'float'), $rt->binary('*', $rt->f(4), $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(4), $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->binary('-', $rt->binary('-', $rt->binary('-', $rt->binary('*', $rt->unary('-', $a), $rt->swizzle($p, 'z'), 1, 'float'), $rt->binary('*', $rt->f(4), $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(4), $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'));
    };
    $chen__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($a, $b, $c);
        $a = $rt->f(40);
        $b = $rt->f(3);
        $c = $rt->f(28);
        return $rt->construct(3, $rt->binary('*', $a, $rt->binary('-', $rt->swizzle($p, 'y'), $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->binary('*', $rt->binary('-', $c, $a, 1, 'float'), $rt->swizzle($p, 'x'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->binary('*', $c, $rt->swizzle($p, 'y'), 1, 'float'), 1, 'float'), $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'y'), 1, 'float'), $rt->binary('*', $b, $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'));
    };
    $dadras__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($a, $b, $c, $d, $e);
        $a = $rt->f(3);
        $b = $rt->f(2.7000000000000002);
        $c = $rt->f(1.7);
        $d = $rt->f(2);
        $e = $rt->f(9);
        return $rt->construct(3, $rt->binary('+', $rt->binary('-', $rt->swizzle($p, 'y'), $rt->binary('*', $a, $rt->swizzle($p, 'x'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $b, $rt->swizzle($p, 'y'), 1, 'float'), $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->binary('*', $c, $rt->swizzle($p, 'y'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'), $rt->swizzle($p, 'z'), 1, 'float'), $rt->binary('-', $rt->binary('*', $rt->binary('*', $d, $rt->swizzle($p, 'x'), 1, 'float'), $rt->swizzle($p, 'y'), 1, 'float'), $rt->binary('*', $e, $rt->swizzle($p, 'z'), 1, 'float'), 1, 'float'));
    };
    $stepAttractor__vec3_int_float = sub {
        my ($p, $type, $dt) = @_;
        $p = $rt->copy($p, 'float');
        my ($dp);
        $dp = $rt->construct(3, 0.0);
        if ($rt->binary('==', $type, $rt->i(0))) {
            @{$dp} = map { $rt->f32($_) } @{($lorenz__vec3->($p))};
        } else {
            if ($rt->binary('==', $type, $rt->i(1))) {
                @{$dp} = map { $rt->f32($_) } @{($rossler__vec3->($p))};
            } else {
                if ($rt->binary('==', $type, $rt->i(2))) {
                    @{$dp} = map { $rt->f32($_) } @{($aizawa__vec3->($p))};
                } else {
                    if ($rt->binary('==', $type, $rt->i(3))) {
                        @{$dp} = map { $rt->f32($_) } @{($thomas__vec3->($p))};
                    } else {
                        if ($rt->binary('==', $type, $rt->i(4))) {
                            @{$dp} = map { $rt->f32($_) } @{($halvorsen__vec3->($p))};
                        } else {
                            if ($rt->binary('==', $type, $rt->i(5))) {
                                @{$dp} = map { $rt->f32($_) } @{($chen__vec3->($p))};
                            } else {
                                @{$dp} = map { $rt->f32($_) } @{($dadras__vec3->($p))};
                            }
                        }
                    }
                }
            }
        }
        return $rt->binary('+', $p, $rt->binary('*', $dp, $dt, 3, 'float'), 3, 'float');
    };
    $main__void = sub {
        my ($agentSeed, $col, $coord, $dt, $initSeed, $needs3DInit, $newPos, $pos, $respawnSeed, $stateSize, $texSize, $vel);
        $coord = $rt->construct(2, $rt->swizzle($ctx->{frag_coord}, 'xy'), 'int');
        $texSize = $rt->texture_size($_u_xyzTex);
        $stateSize = $rt->swizzle($texSize, 'x');
        $pos = $rt->texel_fetch($_u_xyzTex, $coord, $rt->i(0));
        $vel = $rt->texel_fetch($_u_velTex, $coord, $rt->i(0));
        $col = $rt->texel_fetch($_u_rgbaTex, $coord, $rt->i(0));
        $agentSeed = $rt->binary('+', $rt->construct(1, $rt->binary('+', $rt->swizzle($coord, 'x'), $rt->binary('*', $rt->swizzle($coord, 'y'), $stateSize, 1, 'int'), 1, 'int'), 'uint'), $rt->construct(1, $_u_seed, 'uint'), 1, 'uint');
        $needs3DInit = (((((((((($rt->binary('>=', $rt->swizzle($pos, 'w'), $rt->f(0.5))) && ($rt->binary('==', $rt->swizzle($pos, 'z'), $rt->f(0))) ? 1 : 0)) && ($rt->binary('>=', $rt->swizzle($pos, 'x'), $rt->f(0))) ? 1 : 0)) && ($rt->binary('<=', $rt->swizzle($pos, 'x'), $rt->f(1))) ? 1 : 0)) && ($rt->binary('>=', $rt->swizzle($pos, 'y'), $rt->f(0))) ? 1 : 0)) && ($rt->binary('<=', $rt->swizzle($pos, 'y'), $rt->f(1))) ? 1 : 0);
        $initSeed = 0;
        if ($needs3DInit) {
            $initSeed = $rt->binary('+', $agentSeed, $rt->construct(1, $rt->binary('*', $_u_time, $rt->f(1000), 1, 'float'), 'uint'), 1, 'uint');
            $pos = $rt->assign_swizzle($pos, 'x', $rt->binary('*', $rt->binary('-', $hash__uint->($initSeed), $rt->f(0.5), 1, 'float'), $rt->f(20), 1, 'float'));
            $pos = $rt->assign_swizzle($pos, 'y', $rt->binary('*', $rt->binary('-', $hash__uint->($rt->binary('+', $initSeed, $rt->i(1), 1, 'uint')), $rt->f(0.5), 1, 'float'), $rt->f(20), 1, 'float'));
            $pos = $rt->assign_swizzle($pos, 'z', $rt->binary('+', $rt->binary('*', $hash__uint->($rt->binary('+', $initSeed, $rt->i(2), 1, 'uint')), $rt->f(30), 1, 'float'), $rt->f(10), 1, 'float'));
            @{$g->{outXYZ}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->swizzle($pos, 'xyz'), $rt->f(1)))};
            @{$g->{outVel}} = map { $rt->f32($_) } @{($vel)};
            @{$g->{outRGBA}} = map { $rt->f32($_) } @{($col)};
            return;
        }
        if ($rt->binary('<', $rt->swizzle($pos, 'w'), $rt->f(0.5))) {
            @{$g->{outXYZ}} = map { $rt->f32($_) } @{($pos)};
            @{$g->{outVel}} = map { $rt->f32($_) } @{($vel)};
            @{$g->{outRGBA}} = map { $rt->f32($_) } @{($col)};
            return;
        }
        $dt = $rt->binary('*', $_u_speed, $rt->f(0.01), 1, 'float');
        $newPos = $stepAttractor__vec3_int_float->($rt->swizzle($pos, 'xyz'), $_u_attractor, $dt);
        $respawnSeed = 0;
        if ((($rt->component_wise('any', $rt->component_wise('isnan', $newPos))) || ($rt->binary('>', $rt->length($newPos), $rt->f(1000))) ? 1 : 0)) {
            $respawnSeed = $rt->binary('+', $agentSeed, $rt->construct(1, $rt->binary('*', $_u_time, $rt->f(1000), 1, 'float'), 'uint'), 1, 'uint');
            $newPos = $rt->assign_swizzle($newPos, 'x', $rt->binary('*', $rt->binary('-', $hash__uint->($respawnSeed), $rt->f(0.5), 1, 'float'), $rt->f(20), 1, 'float'));
            $newPos = $rt->assign_swizzle($newPos, 'y', $rt->binary('*', $rt->binary('-', $hash__uint->($rt->binary('+', $respawnSeed, $rt->i(1), 1, 'uint')), $rt->f(0.5), 1, 'float'), $rt->f(20), 1, 'float'));
            $newPos = $rt->assign_swizzle($newPos, 'z', $rt->binary('+', $rt->binary('*', $hash__uint->($rt->binary('+', $respawnSeed, $rt->i(2), 1, 'uint')), $rt->f(30), 1, 'float'), $rt->f(10), 1, 'float'));
        }
        @{$g->{outXYZ}} = map { $rt->f32($_) } @{($rt->construct(4, $newPos, $rt->f(1)))};
        @{$g->{outVel}} = map { $rt->f32($_) } @{($vel)};
        @{$g->{outRGBA}} = map { $rt->f32($_) } @{($col)};
    };
    $main__void->();
    my $_c0 = $g->{outXYZ};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
    my $_c1 = $g->{outVel};
    $out->[4] = $rt->f32($_c1->[0]); $out->[5] = $rt->f32($_c1->[1]); $out->[6] = $rt->f32($_c1->[2]); $out->[7] = $rt->f32($_c1->[3]);
    my $_c2 = $g->{outRGBA};
    $out->[8] = $rt->f32($_c2->[0]); $out->[9] = $rt->f32($_c2->[1]); $out->[10] = $rt->f32($_c2->[2]); $out->[11] = $rt->f32($_c2->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['outXYZ', 'outVel', 'outRGBA'] };
