# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_trailTex = $ctx->texture_binding('trailTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_intensity = exists $U->{'intensity'} ? $U->{'intensity'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($decay, $trailColor, $uv);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        $trailColor = $rt->texture($_u_trailTex, $uv);
        $decay = $rt->component_wise('clamp', $rt->binary('/', $_u_intensity, $rt->f(100), 1, 'float'), $rt->f(0), $rt->f(1));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->component_wise('clamp', $rt->binary('*', $trailColor, $decay, 4, 'float'), $rt->f(0), $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
