# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_trailTex = $ctx->texture_binding('trailTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_inputIntensity = exists $U->{'inputIntensity'} ? $U->{'inputIntensity'} : $rt->f(0.0);
    my $_u_matteOpacity = exists $U->{'matteOpacity'} ? $U->{'matteOpacity'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        my ($alpha, $inputColor, $matteAlpha, $rgb, $t, $trailColor, $trailPresence, $uv);
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_resolution, 2, 'float');
        $inputColor = $rt->texture($_u_inputTex, $uv);
        $trailColor = $rt->texture($_u_trailTex, $uv);
        $t = $rt->binary('/', $_u_inputIntensity, $rt->f(100), 1, 'float');
        $matteAlpha = $_u_matteOpacity;
        $trailPresence = $rt->component_wise('max', $rt->component_wise('max', $rt->swizzle($trailColor, 'r'), $rt->swizzle($trailColor, 'g')), $rt->swizzle($trailColor, 'b'));
        $rgb = $rt->binary('+', $rt->swizzle($trailColor, 'rgb'), $rt->binary('*', $rt->binary('*', $rt->swizzle($inputColor, 'rgb'), $t, 3, 'float'), $matteAlpha, 3, 'float'), 3, 'float');
        $alpha = $rt->component_wise('max', $trailPresence, $matteAlpha);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->component_wise('clamp', $rt->construct(4, $rgb, $alpha), $rt->f(0), $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
