# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($lighting__vec3_vec3_vec3, $inverseRotation__vec3, $forwardRotation__vec3, $renderPerspective__vec2, $main__void);
    my $_retc;
    my $_u_VIEW_MODE = exists $U->{'VIEW_MODE'} ? $U->{'VIEW_MODE'} : 0;
    my $_u_volumeCache = $ctx->texture_binding('volumeCache');
    my $_u_analyticalGeo = $ctx->texture_binding('analyticalGeo');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_volumeSize = exists $U->{'volumeSize'} ? $U->{'volumeSize'} : 0;
    my $_u_threshold = exists $U->{'threshold'} ? $U->{'threshold'} : $rt->f(0.0);
    my $_u_zoom = exists $U->{'zoom'} ? $U->{'zoom'} : $rt->f(0.0);
    my $_u_panX = exists $U->{'panX'} ? $U->{'panX'} : $rt->f(0.0);
    my $_u_panY = exists $U->{'panY'} ? $U->{'panY'} : $rt->f(0.0);
    my $_u_lightDirection = exists $U->{'lightDirection'} ? $U->{'lightDirection'} : $rt->construct(3, 0.0);
    my $_u_ambient = exists $U->{'ambient'} ? $U->{'ambient'} : $rt->f(0.0);
    my $_u_diffuseIntensity = exists $U->{'diffuseIntensity'} ? $U->{'diffuseIntensity'} : $rt->f(0.0);
    my $_u_specularIntensity = exists $U->{'specularIntensity'} ? $U->{'specularIntensity'} : $rt->f(0.0);
    my $_u_bgColor = exists $U->{'bgColor'} ? $U->{'bgColor'} : $rt->construct(3, 0.0);
    my $_u_bgAlpha = exists $U->{'bgAlpha'} ? $U->{'bgAlpha'} : $rt->f(0.0);
    my $_u_rotateX = exists $U->{'rotateX'} ? $U->{'rotateX'} : $rt->f(0.0);
    my $_u_rotateY = exists $U->{'rotateY'} ? $U->{'rotateY'} : $rt->f(0.0);
    my $_u_rotateZ = exists $U->{'rotateZ'} ? $U->{'rotateZ'} : $rt->f(0.0);
    my $_u_viewScale = exists $U->{'viewScale'} ? $U->{'viewScale'} : $rt->f(0.0);
    my $_u_posX = exists $U->{'posX'} ? $U->{'posX'} : $rt->f(0.0);
    my $_u_posY = exists $U->{'posY'} ? $U->{'posY'} : $rt->f(0.0);
    my $_u_posZ = exists $U->{'posZ'} ? $U->{'posZ'} : $rt->f(0.0);
    my $_u_fieldOfView = exists $U->{'fieldOfView'} ? $U->{'fieldOfView'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $g->{geoOut} = $rt->construct(4, 0.0);
    $lighting__vec3_vec3_vec3 = sub {
        my ($color, $normal, $viewDirection) = @_;
        $color = $rt->copy($color, 'float');
        $normal = $rt->copy($normal, 'float');
        $viewDirection = $rt->copy($viewDirection, 'float');
        my ($halfVector, $light, $specular);
        $light = $rt->construct(3, $rt->f(0), $rt->f(1), $rt->f(0));
        if ($rt->binary('>', $rt->dot($_u_lightDirection, $_u_lightDirection), $rt->f(9.9999999999999995e-07))) {
            @{$light} = map { $rt->f32($_) } @{($rt->normalize($_u_lightDirection))};
        }
        $halfVector = $rt->binary('+', $light, $viewDirection, 3, 'float');
        $specular = $rt->f(0);
        if ($rt->binary('>', $rt->dot($halfVector, $halfVector), $rt->f(9.9999999999999995e-07))) {
            $specular = $rt->binary('*', $rt->component_wise('pow', $rt->component_wise('max', $rt->dot($normal, $rt->normalize($halfVector)), $rt->f(0)), $rt->f(32)), $_u_specularIntensity, 1, 'float');
        }
        return $rt->binary('+', $rt->binary('*', $color, $rt->binary('+', $_u_ambient, $rt->binary('*', $rt->component_wise('max', $rt->dot($normal, $light), $rt->f(0)), $_u_diffuseIntensity, 1, 'float'), 1, 'float'), 3, 'float'), $specular, 3, 'float');
    };
    $inverseRotation__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($c, $s);
        $c = $rt->component_wise('cos', $rt->construct(3, $_u_rotateX, $_u_rotateY, $_u_rotateZ));
        $s = $rt->component_wise('sin', $rt->construct(3, $_u_rotateX, $_u_rotateY, $_u_rotateZ));
        @{$p} = map { $rt->f32($_) } @{($rt->construct(3, $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($c, 'z'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($s, 'z'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'x')), $rt->swizzle($s, 'z'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($c, 'z'), 1, 'float'), 1, 'float'), $rt->swizzle($p, 'z')))};
        @{$p} = map { $rt->f32($_) } @{($rt->construct(3, $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($c, 'y'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($s, 'y'), 1, 'float'), 1, 'float'), $rt->swizzle($p, 'y'), $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($s, 'y'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($c, 'y'), 1, 'float'), 1, 'float')))};
        return $rt->construct(3, $rt->swizzle($p, 'x'), $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($c, 'x'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($s, 'x'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'y')), $rt->swizzle($s, 'x'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($c, 'x'), 1, 'float'), 1, 'float'));
    };
    $forwardRotation__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($c, $s);
        $c = $rt->component_wise('cos', $rt->construct(3, $_u_rotateX, $_u_rotateY, $_u_rotateZ));
        $s = $rt->component_wise('sin', $rt->construct(3, $_u_rotateX, $_u_rotateY, $_u_rotateZ));
        @{$p} = map { $rt->f32($_) } @{($rt->construct(3, $rt->swizzle($p, 'x'), $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($c, 'x'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($s, 'x'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($s, 'x'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($c, 'x'), 1, 'float'), 1, 'float')))};
        @{$p} = map { $rt->f32($_) } @{($rt->construct(3, $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($c, 'y'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($s, 'y'), 1, 'float'), 1, 'float'), $rt->swizzle($p, 'y'), $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'x')), $rt->swizzle($s, 'y'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'z'), $rt->swizzle($c, 'y'), 1, 'float'), 1, 'float')))};
        return $rt->construct(3, $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($c, 'z'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($s, 'z'), 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->swizzle($s, 'z'), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $rt->swizzle($c, 'z'), 1, 'float'), 1, 'float'), $rt->swizzle($p, 'z'));
    };
    $renderPerspective__vec2 = sub {
        my ($uv) = @_;
        $uv = $rt->copy($uv, 'float');
        my ($_for0_first, $_for1_first, $_for2_first, $a, $atlas, $axis, $b, $boundary, $cameraRay, $cell, $crossed, $delta, $density, $direction, $distance, $enter, $farT, $focalLength, $framedUv, $leave, $nearT, $nextT, $normal, $origin, $size, $step, $stepDir, $viewDirection, $worldNormal);
        $size = $rt->construct(1, $_u_volumeSize);
        $focalLength = $rt->binary('/', $rt->f(1), $rt->component_wise('tan', $rt->binary('*', $rt->component_wise('clamp', $_u_fieldOfView, $rt->f(10), $rt->f(150)), $rt->f(0.0087266462600000001), 1, 'float')), 1, 'float');
        $origin = $rt->binary('*', $rt->binary('+', $rt->binary('/', $inverseRotation__vec3->($rt->construct(3, $rt->unary('-', $_u_posX), $rt->unary('-', $_u_posY), $rt->binary('-', $rt->f(80), $_u_posZ, 1, 'float'))), $rt->f(80), 3, 'float'), $rt->f(0.5), 3, 'float'), $size, 3, 'float');
        $framedUv = $rt->binary('/', $rt->binary('+', $uv, $rt->construct(2, $_u_panX, $_u_panY), 2, 'float'), $rt->component_wise('max', $_u_zoom, $rt->f(0.001)), 2, 'float');
        $cameraRay = $rt->construct(3, $rt->binary('/', $rt->binary('*', $framedUv, $rt->f(2), 2, 'float'), $rt->binary('*', $focalLength, $rt->component_wise('max', $_u_viewScale, $rt->f(0.001)), 1, 'float'), 2, 'float'), $rt->unary('-', $rt->f(1)));
        $direction = $rt->binary('*', $inverseRotation__vec3->($cameraRay), $rt->binary('/', $size, $rt->f(80), 1, 'float'), 3, 'float');
        $nearT = $rt->construct(3, $rt->unary('-', $rt->f(1e+30)));
        $farT = $rt->construct(3, $rt->f(1e+30));
        $delta = $rt->construct(3, $rt->f(1e+30));
        $stepDir = $rt->construct(3, $rt->i(0), 'int');
        $axis = $rt->i(0);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $axis = $rt->binary('+', $axis, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<', $axis, $rt->i(3)))) {
                last;
            }
            $a = $rt->f(0.0);
            $b = $rt->f(0.0);
            if ($rt->binary('<', $rt->component_wise('abs', $direction->[int($axis)]), $rt->f(1e-08))) {
                if ((($rt->binary('<', $origin->[int($axis)], $rt->f(0))) || ($rt->binary('>=', $origin->[int($axis)], $size)) ? 1 : 0)) {
                    return;
                }
            } else {
                $a = $rt->binary('/', $rt->unary('-', $origin->[int($axis)]), $direction->[int($axis)], 1, 'float');
                $b = $rt->binary('/', $rt->binary('-', $size, $origin->[int($axis)], 1, 'float'), $direction->[int($axis)], 1, 'float');
                $nearT->[int($axis)] = $rt->component_wise('min', $a, $b);
                $farT->[int($axis)] = $rt->component_wise('max', $a, $b);
                $delta->[int($axis)] = $rt->binary('/', $rt->f(1), $rt->component_wise('abs', $direction->[int($axis)]), 1, 'float');
                $stepDir->[int($axis)] = (($rt->binary('>', $direction->[int($axis)], $rt->f(0))) ? ($rt->i(1)) : ($rt->unary('-', $rt->i(1))));
            }
        }
        $enter = $rt->component_wise('max', $rt->component_wise('max', $rt->swizzle($nearT, 'x'), $rt->swizzle($nearT, 'y')), $rt->swizzle($nearT, 'z'));
        $leave = $rt->component_wise('min', $rt->component_wise('min', $rt->swizzle($farT, 'x'), $rt->swizzle($farT, 'y')), $rt->swizzle($farT, 'z'));
        $distance = $rt->component_wise('max', $enter, $rt->f(0.10000000000000001));
        if ($rt->binary('>=', $distance, $leave)) {
            return;
        }
        $cell = $rt->component_wise('clamp', $rt->construct(3, $rt->component_wise('floor', $rt->binary('+', $rt->binary('+', $origin, $rt->binary('*', $direction, $distance, 3, 'float'), 3, 'float'), $rt->binary('*', $rt->construct(3, $stepDir), $rt->f(0.0001), 3, 'float'), 3, 'float')), 'int'), $rt->construct(3, $rt->i(0), 'int'), $rt->construct(3, $rt->binary('-', $_u_volumeSize, $rt->i(1), 1, 'int'), 'int'));
        $nextT = $rt->construct(3, $rt->f(1e+30));
        $axis = $rt->i(0);
        $_for1_first = 1;
        for my $_for1 (0 .. 1048575) {
            if (!$_for1_first) {
                $axis = $rt->binary('+', $axis, $rt->i(1), 1, 'int');
            }
            $_for1_first = 0;
            if (!($rt->binary('<', $axis, $rt->i(3)))) {
                last;
            }
            $boundary = $rt->f(0.0);
            if ($rt->binary('!=', $stepDir->[int($axis)], $rt->i(0))) {
                $boundary = $rt->binary('+', $rt->construct(1, $cell->[int($axis)]), (($rt->binary('>', $stepDir->[int($axis)], $rt->i(0))) ? ($rt->f(1)) : ($rt->f(0))), 1, 'float');
                $nextT->[int($axis)] = $rt->binary('/', $rt->binary('-', $boundary, $origin->[int($axis)], 1, 'float'), $direction->[int($axis)], 1, 'float');
            }
        }
        $viewDirection = $rt->normalize($rt->unary('-', $cameraRay));
        $normal = $rt->normalize($rt->unary('-', $direction));
        if ($rt->binary('>=', $enter, $rt->f(0.10000000000000001))) {
            @{$normal} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0)))};
            if ((($rt->binary('>=', $rt->swizzle($nearT, 'y'), $rt->swizzle($nearT, 'x'))) && ($rt->binary('>=', $rt->swizzle($nearT, 'y'), $rt->swizzle($nearT, 'z'))) ? 1 : 0)) {
                $normal = $rt->assign_swizzle($normal, 'y', $rt->unary('-', $rt->construct(1, $rt->swizzle($stepDir, 'y'))));
            } else {
                if ($rt->binary('>=', $rt->swizzle($nearT, 'x'), $rt->swizzle($nearT, 'z'))) {
                    $normal = $rt->assign_swizzle($normal, 'x', $rt->unary('-', $rt->construct(1, $rt->swizzle($stepDir, 'x'))));
                } else {
                    $normal = $rt->assign_swizzle($normal, 'z', $rt->unary('-', $rt->construct(1, $rt->swizzle($stepDir, 'z'))));
                }
            }
        }
        $step = $rt->i(0);
        $_for2_first = 1;
        for my $_for2 (0 .. 1048575) {
            if (!$_for2_first) {
                $step = $rt->binary('+', $step, $rt->i(1), 1, 'int');
            }
            $_for2_first = 0;
            if (!($rt->binary('<', $step, $rt->binary('*', $_u_volumeSize, $rt->i(3), 1, 'int')))) {
                last;
            }
            if ((((($rt->component_wise('any', $rt->component_wise('lessThan', $cell, $rt->construct(3, $rt->i(0), 'int')))) || ($rt->component_wise('any', $rt->component_wise('greaterThanEqual', $cell, $rt->construct(3, $_u_volumeSize, 'int')))) ? 1 : 0)) || ($rt->binary('>=', $distance, $leave)) ? 1 : 0)) {
                last;
            }
            $atlas = $rt->construct(2, $rt->swizzle($cell, 'x'), $rt->binary('+', $rt->swizzle($cell, 'y'), $rt->binary('*', $rt->swizzle($cell, 'z'), $_u_volumeSize, 1, 'int'), 1, 'int'), 'int');
            $density = $rt->swizzle($rt->texel_fetch($_u_analyticalGeo, $atlas, $rt->i(0)), 'a');
            $worldNormal = $rt->construct(3, 0.0);
            if ((($rt->binary('>', $density, $rt->f(0))) && ($rt->binary('>=', $density, $_u_threshold)) ? 1 : 0)) {
                $worldNormal = $forwardRotation__vec3->($normal);
                @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $lighting__vec3_vec3_vec3->($rt->swizzle($rt->texel_fetch($_u_volumeCache, $atlas, $rt->i(0)), 'rgb'), $worldNormal, $viewDirection), $rt->f(1)))};
                @{$g->{geoOut}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->binary('+', $rt->binary('*', $worldNormal, $rt->f(0.5), 3, 'float'), $rt->f(0.5), 3, 'float'), $rt->component_wise('clamp', $rt->binary('/', $distance, $rt->f(320), 1, 'float'), $rt->f(0), $rt->f(1))))};
                return;
            }
            $distance = $rt->component_wise('min', $rt->component_wise('min', $rt->swizzle($nextT, 'x'), $rt->swizzle($nextT, 'y')), $rt->swizzle($nextT, 'z'));
            $crossed = $rt->component_wise('lessThanEqual', $nextT, $rt->construct(3, $distance));
            @{$normal} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0)))};
            if ($rt->swizzle($crossed, 'y')) {
                $normal = $rt->assign_swizzle($normal, 'y', $rt->unary('-', $rt->construct(1, $rt->swizzle($stepDir, 'y'))));
            } else {
                if ($rt->swizzle($crossed, 'x')) {
                    $normal = $rt->assign_swizzle($normal, 'x', $rt->unary('-', $rt->construct(1, $rt->swizzle($stepDir, 'x'))));
                } else {
                    $normal = $rt->assign_swizzle($normal, 'z', $rt->unary('-', $rt->construct(1, $rt->swizzle($stepDir, 'z'))));
                }
            }
            @{$cell} = @{($rt->binary('+', $cell, $rt->binary('*', $rt->construct(3, $crossed, 'int'), $stepDir, 3, 'int'), 3, 'int'))};
            @{$nextT} = map { $rt->f32($_) } @{($rt->binary('+', $nextT, $rt->binary('*', $rt->construct(3, $crossed), $delta, 3, 'float'), 3, 'float'))};
        }
    };
    $main__void = sub {
        my ($_for3_first, $aspect, $atlas, $cell, $color, $crossed, $density, $distance, $enter, $fullRes, $leave, $nearT, $nextT, $normal, $origin, $right, $size, $span, $step, $up, $uv);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->binary('*', $_u_bgColor, $_u_bgAlpha, 3, 'float'), $_u_bgAlpha))};
        @{$g->{geoOut}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->f(0.5), $rt->f(0.5), $rt->f(1), $rt->f(1)))};
        $fullRes = (($rt->binary('>', $rt->swizzle($_u_fullResolution, 'x'), $rt->f(0))) ? ($_u_fullResolution) : ($_u_resolution));
        $uv = $rt->binary('/', $rt->binary('-', $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float'), $rt->binary('*', $fullRes, $rt->f(0.5), 2, 'float'), 2, 'float'), $rt->swizzle($fullRes, 'y'), 2, 'float');
        $aspect = $rt->f(0.0);
        $cell = $rt->construct(3, 0.0, 'int');
        $distance = $rt->f(0.0);
        $enter = $rt->f(0.0);
        $leave = $rt->f(0.0);
        $nearT = $rt->construct(3, 0.0);
        $nextT = $rt->construct(3, 0.0);
        $normal = $rt->construct(3, 0.0);
        $origin = $rt->construct(3, 0.0);
        $right = $rt->construct(3, 0.0);
        $size = $rt->f(0.0);
        $span = $rt->f(0.0);
        $up = $rt->construct(3, 0.0);
        if ($rt->binary('==', $_u_VIEW_MODE, $rt->i(2))) {
            $renderPerspective__vec2->($uv);
        } else {
            $size = $rt->construct(1, $_u_volumeSize);
            $aspect = $rt->binary('/', $rt->swizzle($fullRes, 'x'), $rt->swizzle($fullRes, 'y'), 1, 'float');
            $span = $rt->binary('/', $rt->binary('*', $rt->binary('*', $rt->component_wise('max', $rt->f(1.6329931619), $rt->binary('/', $rt->f(1.4142135624000001), $aspect, 1, 'float')), $size, 1, 'float'), $rt->f(1.0800000000000001), 1, 'float'), $rt->component_wise('max', $_u_zoom, $rt->f(0.001)), 1, 'float');
            $right = $rt->construct(3, $rt->f(0.70710678120000003), $rt->f(0), $rt->unary('-', $rt->f(0.70710678120000003)));
            $up = $rt->construct(3, $rt->unary('-', $rt->f(0.4082482905)), $rt->f(0.81649658089999999), $rt->unary('-', $rt->f(0.4082482905)));
            $origin = $rt->binary('+', $rt->binary('+', $rt->construct(3, $rt->binary('*', $size, $rt->f(2.5), 1, 'float')), $rt->binary('*', $rt->binary('*', $right, $rt->binary('+', $rt->swizzle($uv, 'x'), $_u_panX, 1, 'float'), 3, 'float'), $span, 3, 'float'), 3, 'float'), $rt->binary('*', $rt->binary('*', $up, $rt->binary('+', $rt->swizzle($uv, 'y'), $_u_panY, 1, 'float'), 3, 'float'), $span, 3, 'float'), 3, 'float');
            $nearT = $rt->binary('-', $origin, $size, 3, 'float');
            $enter = $rt->component_wise('max', $rt->component_wise('max', $rt->swizzle($nearT, 'x'), $rt->swizzle($nearT, 'y')), $rt->swizzle($nearT, 'z'));
            $leave = $rt->component_wise('min', $rt->component_wise('min', $rt->swizzle($origin, 'x'), $rt->swizzle($origin, 'y')), $rt->swizzle($origin, 'z'));
            if ($rt->binary('>=', $enter, $leave)) {
                return;
            }
            $distance = $rt->component_wise('max', $enter, $rt->f(0));
            $cell = $rt->component_wise('clamp', $rt->construct(3, $rt->component_wise('floor', $rt->binary('-', $origin, $rt->binary('+', $distance, $rt->f(0.0001), 1, 'float'), 3, 'float')), 'int'), $rt->construct(3, $rt->i(0), 'int'), $rt->construct(3, $rt->binary('-', $_u_volumeSize, $rt->i(1), 1, 'int'), 'int'));
            $nextT = $rt->binary('-', $origin, $rt->construct(3, $cell), 3, 'float');
            $normal = $rt->construct(3, $rt->f(0), $rt->f(0), $rt->f(1));
            if ((($rt->binary('>=', $rt->swizzle($nearT, 'y'), $rt->swizzle($nearT, 'x'))) && ($rt->binary('>=', $rt->swizzle($nearT, 'y'), $rt->swizzle($nearT, 'z'))) ? 1 : 0)) {
                @{$normal} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $rt->f(1), $rt->f(0)))};
            } else {
                if ($rt->binary('>=', $rt->swizzle($nearT, 'x'), $rt->swizzle($nearT, 'z'))) {
                    @{$normal} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(1), $rt->f(0), $rt->f(0)))};
                }
            }
            $step = $rt->i(0);
            $_for3_first = 1;
            for my $_for3 (0 .. 1048575) {
                if (!$_for3_first) {
                    $step = $rt->binary('+', $step, $rt->i(1), 1, 'int');
                }
                $_for3_first = 0;
                if (!($rt->binary('<', $step, $rt->binary('*', $_u_volumeSize, $rt->i(3), 1, 'int')))) {
                    last;
                }
                if ((($rt->component_wise('any', $rt->component_wise('lessThan', $cell, $rt->construct(3, $rt->i(0), 'int')))) || ($rt->binary('>=', $distance, $leave)) ? 1 : 0)) {
                    last;
                }
                $atlas = $rt->construct(2, $rt->swizzle($cell, 'x'), $rt->binary('+', $rt->swizzle($cell, 'y'), $rt->binary('*', $rt->swizzle($cell, 'z'), $_u_volumeSize, 1, 'int'), 1, 'int'), 'int');
                $density = $rt->swizzle($rt->texel_fetch($_u_analyticalGeo, $atlas, $rt->i(0)), 'a');
                $color = $rt->construct(3, 0.0);
                if ((($rt->binary('>', $density, $rt->f(0))) && ($rt->binary('>=', $density, $_u_threshold)) ? 1 : 0)) {
                    $color = $rt->swizzle($rt->texel_fetch($_u_volumeCache, $atlas, $rt->i(0)), 'rgb');
                    @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $lighting__vec3_vec3_vec3->($color, $normal, $rt->construct(3, $rt->f(0.57735026919999999))), $rt->f(1)))};
                    @{$g->{geoOut}} = map { $rt->f32($_) } @{($rt->construct(4, $rt->binary('+', $rt->binary('*', $normal, $rt->f(0.5), 3, 'float'), $rt->f(0.5), 3, 'float'), $rt->component_wise('clamp', $rt->binary('/', $distance, $rt->binary('*', $size, $rt->f(4), 1, 'float'), 1, 'float'), $rt->f(0), $rt->f(1))))};
                    return;
                }
                $distance = $rt->component_wise('min', $rt->component_wise('min', $rt->swizzle($nextT, 'x'), $rt->swizzle($nextT, 'y')), $rt->swizzle($nextT, 'z'));
                $crossed = $rt->component_wise('lessThanEqual', $nextT, $rt->construct(3, $distance));
                if ($rt->swizzle($crossed, 'y')) {
                    @{$normal} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $rt->f(1), $rt->f(0)))};
                } else {
                    if ($rt->swizzle($crossed, 'x')) {
                        @{$normal} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(1), $rt->f(0), $rt->f(0)))};
                    } else {
                        @{$normal} = map { $rt->f32($_) } @{($rt->construct(3, $rt->f(0), $rt->f(0), $rt->f(1)))};
                    }
                }
                @{$cell} = @{($rt->binary('-', $cell, $rt->construct(3, $crossed, 'int'), 3, 'int'))};
                @{$nextT} = map { $rt->f32($_) } @{($rt->binary('+', $nextT, $rt->construct(3, $crossed), 3, 'float'))};
            }
        }
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
    my $_c1 = $g->{geoOut};
    $out->[4] = $rt->f32($_c1->[0]); $out->[5] = $rt->f32($_c1->[1]); $out->[6] = $rt->f32($_c1->[2]); $out->[7] = $rt->f32($_c1->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor', 'geoOut'] };
