# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($map__float_float_float_float_float, $lum__vec3, $random__vec2, $neighborsAvgCircle__vec2_vec2, $neighborsAvgRing__vec2_vec2, $getState__float_float_float, $main__void);
    my $_retc;
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_deltaTime = exists $U->{'deltaTime'} ? $U->{'deltaTime'} : $rt->f(0.0);
    my $_u_bufTex = $ctx->texture_binding('bufTex');
    my $_u_seedTex = $ctx->texture_binding('seedTex');
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_weight = exists $U->{'weight'} ? $U->{'weight'} : $rt->f(0.0);
    my $_u_seed = exists $U->{'seed'} ? $U->{'seed'} : 0;
    my $_u_resetState = exists $U->{'resetState'} ? $U->{'resetState'} : 0;
    my $_u_n1v1 = exists $U->{'n1v1'} ? $U->{'n1v1'} : $rt->f(0.0);
    my $_u_n1v2 = exists $U->{'n1v2'} ? $U->{'n1v2'} : $rt->f(0.0);
    my $_u_n1v3 = exists $U->{'n1v3'} ? $U->{'n1v3'} : $rt->f(0.0);
    my $_u_n1v4 = exists $U->{'n1v4'} ? $U->{'n1v4'} : $rt->f(0.0);
    my $_u_n2v1 = exists $U->{'n2v1'} ? $U->{'n2v1'} : $rt->f(0.0);
    my $_u_n2v2 = exists $U->{'n2v2'} ? $U->{'n2v2'} : $rt->f(0.0);
    my $_u_n1r1 = exists $U->{'n1r1'} ? $U->{'n1r1'} : $rt->f(0.0);
    my $_u_n1r2 = exists $U->{'n1r2'} ? $U->{'n1r2'} : $rt->f(0.0);
    my $_u_n1r3 = exists $U->{'n1r3'} ? $U->{'n1r3'} : $rt->f(0.0);
    my $_u_n1r4 = exists $U->{'n1r4'} ? $U->{'n1r4'} : $rt->f(0.0);
    my $_u_n2r1 = exists $U->{'n2r1'} ? $U->{'n2r1'} : $rt->f(0.0);
    my $_u_n2r2 = exists $U->{'n2r2'} ? $U->{'n2r2'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $map__float_float_float_float_float = sub {
        my ($value, $inMin, $inMax, $outMin, $outMax) = @_;
        return $rt->binary('+', $outMin, $rt->binary('/', $rt->binary('*', $rt->binary('-', $outMax, $outMin, 1, 'float'), $rt->binary('-', $value, $inMin, 1, 'float'), 1, 'float'), $rt->binary('-', $inMax, $inMin, 1, 'float'), 1, 'float'), 1, 'float');
    };
    $lum__vec3 = sub {
        my ($color) = @_;
        $color = $rt->copy($color, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->f(0.21260000000000001), $rt->swizzle($color, 'r'), 1, 'float'), $rt->binary('*', $rt->f(0.71519999999999995), $rt->swizzle($color, 'g'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(0.0722), $rt->swizzle($color, 'b'), 1, 'float'), 1, 'float');
    };
    $random__vec2 = sub {
        my ($st) = @_;
        $st = $rt->copy($st, 'float');
        return $rt->component_wise('fract', $rt->binary('*', $rt->component_wise('sin', $rt->dot($rt->swizzle($st, 'xy'), $rt->construct(2, $rt->f(12.989800000000001), $rt->f(78.233000000000004)))), $rt->f(43758.545312299997), 1, 'float'));
    };
    $neighborsAvgCircle__vec2_vec2 = sub {
        my ($uv, $texelSize) = @_;
        $uv = $rt->copy($uv, 'float');
        $texelSize = $rt->copy($texelSize, 'float');
        my ($_for0_first, $_for1_first, $avg, $n, $offset, $total, $x, $y);
        $avg = $rt->f(0.0);
        $total = $rt->f(0);
        $y = $rt->unary('-', $rt->i(3));
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $y = $rt->binary('+', $y, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<=', $y, $rt->i(3)))) {
                last;
            }
            $x = $rt->unary('-', $rt->i(3));
            $_for1_first = 1;
            for my $_for1 (0 .. 1048575) {
                if (!$_for1_first) {
                    $x = $rt->binary('+', $x, $rt->i(1), 1, 'int');
                }
                $_for1_first = 0;
                if (!($rt->binary('<=', $x, $rt->i(3)))) {
                    last;
                }
                if ((($rt->binary('==', $x, $rt->i(0))) && ($rt->binary('==', $y, $rt->i(0))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('==', $rt->component_wise('abs', $x), $rt->i(3))) && ($rt->binary('>', $rt->component_wise('abs', $y), $rt->i(1))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('==', $rt->component_wise('abs', $y), $rt->i(3))) && ($rt->binary('>', $rt->component_wise('abs', $x), $rt->i(1))) ? 1 : 0)) {
                    next;
                }
                $offset = $rt->binary('*', $rt->construct(2, $rt->construct(1, $x), $rt->construct(1, $y)), $texelSize, 2, 'float');
                $n = $rt->swizzle($rt->texture($_u_bufTex, $rt->binary('+', $uv, $offset, 2, 'float')), 'r');
                $total = $rt->binary('+', $total, $n, 1, 'float');
            }
        }
        $avg = $rt->binary('/', $total, $rt->f(36), 1, 'float');
        return $avg;
    };
    $neighborsAvgRing__vec2_vec2 = sub {
        my ($uv, $texelSize) = @_;
        $uv = $rt->copy($uv, 'float');
        $texelSize = $rt->copy($texelSize, 'float');
        my ($_for2_first, $_for3_first, $avg, $n, $offset, $total, $x, $y);
        $avg = $rt->f(0.0);
        $total = $rt->f(0);
        $y = $rt->unary('-', $rt->i(7));
        $_for2_first = 1;
        for my $_for2 (0 .. 1048575) {
            if (!$_for2_first) {
                $y = $rt->binary('+', $y, $rt->i(1), 1, 'int');
            }
            $_for2_first = 0;
            if (!($rt->binary('<=', $y, $rt->i(7)))) {
                last;
            }
            $x = $rt->unary('-', $rt->i(7));
            $_for3_first = 1;
            for my $_for3 (0 .. 1048575) {
                if (!$_for3_first) {
                    $x = $rt->binary('+', $x, $rt->i(1), 1, 'int');
                }
                $_for3_first = 0;
                if (!($rt->binary('<=', $x, $rt->i(7)))) {
                    last;
                }
                if ((($rt->binary('<=', $rt->component_wise('abs', $x), $rt->i(3))) && ($rt->binary('<=', $rt->component_wise('abs', $y), $rt->i(3))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('==', $rt->component_wise('abs', $x), $rt->i(4))) && ($rt->binary('<=', $rt->component_wise('abs', $y), $rt->i(2))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('==', $rt->component_wise('abs', $y), $rt->i(4))) && ($rt->binary('<=', $rt->component_wise('abs', $x), $rt->i(2))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('==', $rt->component_wise('abs', $x), $rt->i(7))) && ($rt->binary('>', $rt->component_wise('abs', $y), $rt->i(2))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('==', $rt->component_wise('abs', $x), $rt->i(6))) && ($rt->binary('>', $rt->component_wise('abs', $y), $rt->i(4))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('==', $rt->component_wise('abs', $x), $rt->i(5))) && ($rt->binary('>', $rt->component_wise('abs', $y), $rt->i(5))) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('>', $rt->component_wise('abs', $x), $rt->i(2))) && ($rt->binary('>', $rt->component_wise('abs', $y), $rt->i(6))) ? 1 : 0)) {
                    next;
                }
                $offset = $rt->binary('*', $rt->construct(2, $rt->construct(1, $x), $rt->construct(1, $y)), $texelSize, 2, 'float');
                $n = $rt->swizzle($rt->texture($_u_bufTex, $rt->binary('+', $uv, $offset, 2, 'float')), 'r');
                $total = $rt->binary('+', $total, $n, 1, 'float');
            }
        }
        $avg = $rt->binary('/', $total, $rt->f(108), 1, 'float');
        return $avg;
    };
    $getState__float_float_float = sub {
        my ($avg1, $avg2, $state) = @_;
        if ((($rt->binary('>=', $avg1, $rt->binary('*', $_u_n1v1, $rt->f(0.01), 1, 'float'))) && ($rt->binary('<=', $avg1, $rt->binary('+', $rt->binary('*', $_u_n1v1, $rt->f(0.01), 1, 'float'), $rt->binary('*', $_u_n1r1, $rt->f(0.01), 1, 'float'), 1, 'float'))) ? 1 : 0)) {
            $state = $rt->f(1);
        }
        if ((($rt->binary('>=', $avg1, $rt->binary('*', $_u_n1v2, $rt->f(0.01), 1, 'float'))) && ($rt->binary('<=', $avg1, $rt->binary('+', $rt->binary('*', $_u_n1v2, $rt->f(0.01), 1, 'float'), $rt->binary('*', $_u_n1r2, $rt->f(0.01), 1, 'float'), 1, 'float'))) ? 1 : 0)) {
            $state = $rt->f(0);
        }
        if ((($rt->binary('>=', $avg1, $rt->binary('*', $_u_n1v3, $rt->f(0.01), 1, 'float'))) && ($rt->binary('<=', $avg1, $rt->binary('+', $rt->binary('*', $_u_n1v3, $rt->f(0.01), 1, 'float'), $rt->binary('*', $_u_n1r3, $rt->f(0.01), 1, 'float'), 1, 'float'))) ? 1 : 0)) {
            $state = $rt->f(0);
        }
        if ((($rt->binary('>=', $avg2, $rt->binary('*', $_u_n2v1, $rt->f(0.01), 1, 'float'))) && ($rt->binary('<=', $avg2, $rt->binary('+', $rt->binary('*', $_u_n2v1, $rt->f(0.01), 1, 'float'), $rt->binary('*', $_u_n2r1, $rt->f(0.01), 1, 'float'), 1, 'float'))) ? 1 : 0)) {
            $state = $rt->f(0);
        }
        if ((($rt->binary('>=', $avg2, $rt->binary('*', $_u_n2v2, $rt->f(0.01), 1, 'float'))) && ($rt->binary('<=', $avg2, $rt->binary('+', $rt->binary('*', $_u_n2v2, $rt->f(0.01), 1, 'float'), $rt->binary('*', $_u_n2r2, $rt->f(0.01), 1, 'float'), 1, 'float'))) ? 1 : 0)) {
            $state = $rt->f(1);
        }
        if ((($rt->binary('>=', $avg1, $rt->binary('*', $_u_n1v4, $rt->f(0.01), 1, 'float'))) && ($rt->binary('<=', $avg1, $rt->binary('+', $rt->binary('*', $_u_n1v4, $rt->f(0.01), 1, 'float'), $rt->binary('*', $_u_n1r4, $rt->f(0.01), 1, 'float'), 1, 'float'))) ? 1 : 0)) {
            $state = $rt->f(0);
        }
        return $state;
    };
    $main__void = sub {
        my ($alive, $animSpeed, $bufState, $bufferIsEmpty, $currentState, $n1, $n2, $newState, $nextState, $prevFrame, $prevLum, $r, $state, $texSize, $texelSize, $uv);
        $texSize = $rt->construct(2, $rt->texture_size($_u_bufTex));
        $uv = $rt->binary('/', $rt->swizzle($ctx->{frag_coord}, 'xy'), $texSize, 2, 'float');
        $texelSize = $rt->binary('/', $rt->f(1), $texSize, 2, 'float');
        $state = $rt->swizzle($rt->texture($_u_bufTex, $uv), 'r');
        $bufState = $rt->texture($_u_bufTex, $uv);
        $bufferIsEmpty = (((((($rt->binary('==', $rt->swizzle($bufState, 'r'), $rt->f(0))) && ($rt->binary('==', $rt->swizzle($bufState, 'g'), $rt->f(0))) ? 1 : 0)) && ($rt->binary('==', $rt->swizzle($bufState, 'b'), $rt->f(0))) ? 1 : 0)) && ($rt->binary('==', $rt->swizzle($bufState, 'a'), $rt->f(0))) ? 1 : 0);
        $alive = $rt->f(0.0);
        $r = $rt->f(0.0);
        if ((($_u_resetState) || ($bufferIsEmpty) ? 1 : 0)) {
            $r = $random__vec2->($rt->binary('+', $uv, $rt->construct(2, $rt->construct(1, $_u_seed)), 2, 'float'));
            $alive = $rt->component_wise('step', $rt->f(0.5), $r);
            @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $alive, $alive, $alive, $rt->f(1)))};
            return;
        }
        $prevFrame = $rt->swizzle($rt->texture($_u_seedTex, $uv), 'rgb');
        $prevLum = $lum__vec3->($prevFrame);
        $newState = $state;
        $n1 = $neighborsAvgCircle__vec2_vec2->($uv, $texelSize);
        $n2 = $neighborsAvgRing__vec2_vec2->($uv, $texelSize);
        $newState = $getState__float_float_float->($n1, $n2, $state);
        if ($rt->binary('>', $_u_weight, $rt->f(0))) {
            $newState = $rt->component_wise('mix', $newState, $prevLum, $rt->binary('*', $_u_weight, $rt->f(0.01), 1, 'float'));
        }
        $animSpeed = $map__float_float_float_float_float->($_u_speed, $rt->f(1), $rt->f(100), $rt->f(0.10000000000000001), $rt->f(100));
        $currentState = $rt->construct(4, $state, $state, $state, $rt->f(1));
        $nextState = $rt->construct(4, $newState, $newState, $newState, $rt->f(1));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->component_wise('mix', $currentState, $nextState, $rt->component_wise('min', $rt->f(1), $rt->binary('*', $_u_deltaTime, $animSpeed, 1, 'float'))))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
