# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($main__void);
    my $_retc;
    my $_u_color = exists $U->{'color'} ? $U->{'color'} : $rt->construct(3, 0.0);
    my $_u_alpha = exists $U->{'alpha'} ? $U->{'alpha'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $main__void = sub {
        @{$g->{fragColor}} = @{($rt->construct(4, $rt->binary('*', $_u_color, $_u_alpha, 3, 'float'), $_u_alpha))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
