# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($rotate2D__vec2_float, $stripes__vec2_float, $checkerboard__vec2_float, $grid__vec2_float, $dots__vec2_float, $hexDist__vec2, $hexagons__vec2_float, $concentricRings__vec2_float_float, $radialLines__vec2_float_float, $triangularGrid__vec2_float, $spiralPattern__vec2_float_float, $heartSDF__vec2, $hearts__vec2_float, $waves__vec2_float, $zigzag__vec2_float, $main__void);
    my $_retc;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_aspect = exists $U->{'aspect'} ? $U->{'aspect'} : $rt->f(0.0);
    my $_u_patternType = exists $U->{'patternType'} ? $U->{'patternType'} : 0;
    my $_u_scale = exists $U->{'scale'} ? $U->{'scale'} : $rt->f(0.0);
    my $_u_thickness = exists $U->{'thickness'} ? $U->{'thickness'} : $rt->f(0.0);
    my $_u_smoothness = exists $U->{'smoothness'} ? $U->{'smoothness'} : $rt->f(0.0);
    my $_u_rotation = exists $U->{'rotation'} ? $U->{'rotation'} : $rt->f(0.0);
    my $_u_skew = exists $U->{'skew'} ? $U->{'skew'} : $rt->f(0.0);
    my $_u_animation = exists $U->{'animation'} ? $U->{'animation'} : 0;
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_fgColor = exists $U->{'fgColor'} ? $U->{'fgColor'} : $rt->construct(3, 0.0);
    my $_u_bgColor = exists $U->{'bgColor'} ? $U->{'bgColor'} : $rt->construct(3, 0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $rotate2D__vec2_float = sub {
        my ($p, $angle) = @_;
        $p = $rt->copy($p, 'float');
        my ($c, $s);
        $c = $rt->component_wise('cos', $angle);
        $s = $rt->component_wise('sin', $angle);
        return $rt->construct(2, $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'x'), $c, 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $s, 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $s, 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $c, 1, 'float'), 1, 'float'));
    };
    $stripes__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($edge1, $edge2, $stripe);
        $stripe = $rt->component_wise('fract', $rt->swizzle($p, 'x'));
        $edge1 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $stripe);
        $edge2 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $stripe);
        return $rt->binary('-', $edge1, $edge2, 1, 'float');
    };
    $checkerboard__vec2_float = sub {
        my ($p, $sm) = @_;
        $p = $rt->copy($p, 'float');
        my ($cell, $check, $d, $edge, $f);
        $f = $rt->component_wise('fract', $p);
        $d = $rt->component_wise('min', $rt->component_wise('min', $rt->swizzle($f, 'x'), $rt->binary('-', $rt->f(1), $rt->swizzle($f, 'x'), 1, 'float')), $rt->component_wise('min', $rt->swizzle($f, 'y'), $rt->binary('-', $rt->f(1), $rt->swizzle($f, 'y'), 1, 'float')));
        $cell = $rt->component_wise('floor', $p);
        $check = $rt->component_wise('mod', $rt->binary('+', $rt->swizzle($cell, 'x'), $rt->swizzle($cell, 'y'), 1, 'float'), $rt->f(2));
        $edge = $rt->component_wise('smoothstep', $rt->f(0), $rt->binary('*', $sm, $rt->f(0.5), 1, 'float'), $d);
        return $rt->component_wise('mix', $rt->binary('-', $rt->f(1), $check, 1, 'float'), $check, $edge);
    };
    $grid__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($f, $lineX, $lineY);
        $f = $rt->component_wise('fract', $p);
        $lineX = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($f, 'x'), $rt->f(0.5), 1, 'float')));
        $lineY = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($f, 'y'), $rt->f(0.5), 1, 'float')));
        return $rt->binary('-', $rt->f(1), $rt->component_wise('min', $lineX, $lineY), 1, 'float');
    };
    $dots__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($d, $f, $radius);
        $f = $rt->binary('-', $rt->component_wise('fract', $p), $rt->f(0.5), 2, 'float');
        $d = $rt->length($f);
        $radius = $rt->binary('*', $t, $rt->f(0.5), 1, 'float');
        return $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('-', $radius, $_u_smoothness, 1, 'float'), $rt->binary('+', $radius, $_u_smoothness, 1, 'float'), $d), 1, 'float');
    };
    $hexDist__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        @{$p} = map { $rt->f32($_) } @{($rt->component_wise('abs', $p))};
        return $rt->component_wise('max', $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->f(0.5), 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $rt->binary('/', $rt->f(1.7320508075688772), $rt->f(2), 1, 'float'), 1, 'float'), 1, 'float'), $rt->swizzle($p, 'x'));
    };
    $hexagons__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($_g, $a, $b, $d, $edge, $h, $s);
        $s = $rt->construct(2, $rt->f(1), $rt->f(1.7320508075688772));
        $h = $rt->binary('*', $s, $rt->f(0.5), 2, 'float');
        $a = $rt->binary('-', $rt->component_wise('mod', $p, $s), $h, 2, 'float');
        $b = $rt->binary('-', $rt->component_wise('mod', $rt->binary('+', $p, $h, 2, 'float'), $s), $h, 2, 'float');
        $_g = (($rt->binary('<', $rt->length($a), $rt->length($b))) ? ($a) : ($b));
        $d = $hexDist__vec2->($_g);
        $edge = $rt->binary('*', $rt->f(0.5), $t, 1, 'float');
        return $rt->component_wise('smoothstep', $rt->binary('+', $edge, $_u_smoothness, 1, 'float'), $rt->binary('-', $edge, $_u_smoothness, 1, 'float'), $d);
    };
    $concentricRings__vec2_float_float = sub {
        my ($p, $t, $timeOffset) = @_;
        $p = $rt->copy($p, 'float');
        my ($d, $edge1, $edge2);
        $d = $rt->component_wise('fract', $rt->binary('+', $rt->length($p), $timeOffset, 1, 'float'));
        $edge1 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $d);
        $edge2 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $d);
        return $rt->binary('-', $edge1, $edge2, 1, 'float');
    };
    $radialLines__vec2_float_float = sub {
        my ($p, $t, $timeOffset) = @_;
        $p = $rt->copy($p, 'float');
        my ($angle, $d, $edge1, $edge2, $lineCount);
        $lineCount = $rt->component_wise('floor', $_u_scale);
        $angle = $rt->binary('+', $rt->component_wise('atan', $rt->swizzle($p, 'y'), $rt->swizzle($p, 'x')), $rt->binary('*', $timeOffset, $rt->f(6.2831853071800001), 1, 'float'), 1, 'float');
        $d = $rt->component_wise('fract', $rt->binary('*', $rt->binary('/', $angle, $rt->f(6.2831853071800001), 1, 'float'), $lineCount, 1, 'float'));
        $edge1 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $d);
        $edge2 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $d);
        return $rt->binary('-', $edge1, $edge2, 1, 'float');
    };
    $triangularGrid__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($cell, $d, $edge, $f, $skewed);
        $skewed = $rt->construct(2, $rt->binary('-', $rt->swizzle($p, 'x'), $rt->binary('/', $rt->swizzle($p, 'y'), $rt->f(1.7320508075688772), 1, 'float'), 1, 'float'), $rt->binary('/', $rt->binary('*', $rt->swizzle($p, 'y'), $rt->f(2), 1, 'float'), $rt->f(1.7320508075688772), 1, 'float'));
        $cell = $rt->component_wise('floor', $skewed);
        $f = $rt->component_wise('fract', $skewed);
        $d = $rt->f(0.0);
        if ($rt->binary('<', $rt->binary('+', $rt->swizzle($f, 'x'), $rt->swizzle($f, 'y'), 1, 'float'), $rt->f(1))) {
            $d = $rt->component_wise('min', $rt->component_wise('min', $rt->swizzle($f, 'x'), $rt->swizzle($f, 'y')), $rt->binary('-', $rt->binary('-', $rt->f(1), $rt->swizzle($f, 'x'), 1, 'float'), $rt->swizzle($f, 'y'), 1, 'float'));
        } else {
            $d = $rt->component_wise('min', $rt->component_wise('min', $rt->binary('-', $rt->f(1), $rt->swizzle($f, 'x'), 1, 'float'), $rt->binary('-', $rt->f(1), $rt->swizzle($f, 'y'), 1, 'float')), $rt->binary('-', $rt->binary('+', $rt->swizzle($f, 'x'), $rt->swizzle($f, 'y'), 1, 'float'), $rt->f(1), 1, 'float'));
        }
        $edge = $rt->binary('*', $rt->binary('-', $rt->f(1), $t, 1, 'float'), $rt->f(0.40000000000000002), 1, 'float');
        return $rt->component_wise('smoothstep', $rt->binary('-', $edge, $_u_smoothness, 1, 'float'), $rt->binary('+', $edge, $_u_smoothness, 1, 'float'), $d);
    };
    $spiralPattern__vec2_float_float = sub {
        my ($p, $t, $timeOffset) = @_;
        $p = $rt->copy($p, 'float');
        my ($angle, $d, $dist, $edge1, $edge2);
        $dist = $rt->length($p);
        $angle = $rt->binary('+', $rt->component_wise('atan', $rt->swizzle($p, 'y'), $rt->swizzle($p, 'x')), $rt->binary('*', $timeOffset, $rt->f(6.2831853071800001), 1, 'float'), 1, 'float');
        $d = $rt->component_wise('fract', $rt->binary('+', $rt->binary('/', $angle, $rt->f(6.2831853071800001), 1, 'float'), $dist, 1, 'float'));
        $edge1 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $d);
        $edge2 = $rt->component_wise('smoothstep', $rt->binary('-', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $rt->binary('+', $rt->binary('+', $rt->f(0.5), $rt->binary('*', $t, $rt->f(0.5), 1, 'float'), 1, 'float'), $_u_smoothness, 1, 'float'), $d);
        return $rt->binary('-', $edge1, $edge2, 1, 'float');
    };
    $heartSDF__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        $p = $rt->assign_swizzle($p, 'x', $rt->component_wise('abs', $rt->swizzle($p, 'x')));
        if ($rt->binary('>', $rt->binary('+', $rt->swizzle($p, 'y'), $rt->swizzle($p, 'x'), 1, 'float'), $rt->f(1))) {
            return $rt->binary('-', $rt->component_wise('sqrt', $rt->dot($rt->binary('-', $p, $rt->construct(2, $rt->f(0.25), $rt->f(0.75)), 2, 'float'), $rt->binary('-', $p, $rt->construct(2, $rt->f(0.25), $rt->f(0.75)), 2, 'float'))), $rt->binary('/', $rt->component_wise('sqrt', $rt->f(2)), $rt->f(4), 1, 'float'), 1, 'float');
        }
        return $rt->binary('*', $rt->component_wise('sqrt', $rt->component_wise('min', $rt->dot($rt->binary('-', $p, $rt->construct(2, $rt->f(0), $rt->f(1)), 2, 'float'), $rt->binary('-', $p, $rt->construct(2, $rt->f(0), $rt->f(1)), 2, 'float')), $rt->dot($rt->binary('-', $p, $rt->binary('*', $rt->f(0.5), $rt->component_wise('max', $rt->binary('+', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'y'), 1, 'float'), $rt->f(0)), 1, 'float'), 2, 'float'), $rt->binary('-', $p, $rt->binary('*', $rt->f(0.5), $rt->component_wise('max', $rt->binary('+', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'y'), 1, 'float'), $rt->f(0)), 1, 'float'), 2, 'float')))), $rt->component_wise('sign', $rt->binary('-', $rt->swizzle($p, 'x'), $rt->swizzle($p, 'y'), 1, 'float')), 1, 'float');
    };
    $hearts__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($cell, $d, $radius, $sm);
        $cell = $rt->binary('-', $rt->component_wise('fract', $p), $rt->f(0.5), 2, 'float');
        $cell = $rt->assign_swizzle($cell, 'y', $rt->binary('+', $rt->swizzle($cell, 'y'), $rt->f(0.25), 1, 'float'));
        $d = $heartSDF__vec2->($rt->binary('*', $cell, $rt->f(2.3999999999999999), 2, 'float'));
        $radius = $rt->binary('-', $rt->f(0.14999999999999999), $rt->binary('*', $t, $rt->f(0.14999999999999999), 1, 'float'), 1, 'float');
        $sm = $rt->component_wise('min', $_u_smoothness, $rt->binary('+', $radius, $rt->f(0.14999999999999999), 1, 'float'));
        return $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('-', $rt->unary('-', $radius), $sm, 1, 'float'), $rt->binary('+', $rt->unary('-', $radius), $sm, 1, 'float'), $d), 1, 'float');
    };
    $waves__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($dist, $halfW, $sm, $y);
        $y = $rt->binary('-', $rt->component_wise('fract', $rt->swizzle($p, 'y')), $rt->f(0.5), 1, 'float');
        $y = $rt->binary('-', $y, $rt->binary('*', $rt->component_wise('cos', $rt->binary('*', $rt->swizzle($p, 'x'), $rt->f(6.2831853071800001), 1, 'float')), $rt->f(0.14999999999999999), 1, 'float'), 1, 'float');
        $dist = $rt->component_wise('abs', $y);
        $halfW = $rt->binary('*', $t, $rt->f(0.20000000000000001), 1, 'float');
        $sm = $rt->component_wise('min', $_u_smoothness, $rt->binary('+', $halfW, $rt->f(0.01), 1, 'float'));
        return $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('-', $halfW, $sm, 1, 'float'), $rt->binary('+', $halfW, $sm, 1, 'float'), $dist), 1, 'float');
    };
    $zigzag__vec2_float = sub {
        my ($p, $t) = @_;
        $p = $rt->copy($p, 'float');
        my ($dist, $f, $halfW, $lineY, $sm);
        $f = $rt->component_wise('fract', $p);
        $lineY = $rt->binary('-', $rt->f(1), $rt->binary('*', $rt->f(2), $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($f, 'x'), $rt->f(0.5), 1, 'float')), 1, 'float'), 1, 'float');
        $dist = $rt->component_wise('abs', $rt->binary('-', $rt->binary('-', $rt->swizzle($f, 'y'), $rt->binary('*', $lineY, $rt->f(0.5), 1, 'float'), 1, 'float'), $rt->f(0.25), 1, 'float'));
        $halfW = $rt->binary('*', $t, $rt->f(0.12), 1, 'float');
        $sm = $rt->component_wise('min', $_u_smoothness, $rt->component_wise('max', $rt->binary('-', $rt->f(0.23999999999999999), $halfW, 1, 'float'), $rt->f(0.0050000000000000001)));
        return $rt->binary('-', $rt->f(1), $rt->component_wise('smoothstep', $rt->binary('-', $halfW, $sm, 1, 'float'), $rt->binary('+', $halfW, $sm, 1, 'float'), $dist), 1, 'float');
    };
    $main__void = sub {
        my ($centered, $color, $globalCoord, $m, $p, $panPeriod, $rad, $st);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $st = $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float');
        @{$st} = map { $rt->f32($_) } @{($rt->binary('*', $rt->binary('-', $st, $rt->f(0.5), 2, 'float'), $rt->f(2), 2, 'float'))};
        $st = $rt->assign_swizzle($st, 'x', $rt->binary('*', $rt->swizzle($st, 'x'), $_u_aspect, 1, 'float'));
        $rad = $rt->binary('/', $rt->binary('*', $_u_rotation, $rt->f(3.1415926535900001), 1, 'float'), $rt->f(180), 1, 'float');
        @{$st} = map { $rt->f32($_) } @{($rotate2D__vec2_float->($st, $rad))};
        $centered = (((($rt->binary('==', $_u_patternType, $rt->i(1))) || ($rt->binary('==', $_u_patternType, $rt->i(5))) ? 1 : 0)) || ($rt->binary('==', $_u_patternType, $rt->i(6))) ? 1 : 0);
        if ((((($centered) ? 0 : 1)) && ($rt->binary('==', $_u_animation, $rt->i(2))) ? 1 : 0)) {
            @{$st} = map { $rt->f32($_) } @{($rotate2D__vec2_float->($st, $rt->binary('*', $rt->binary('*', $_u_time, $rt->f(6.2831853071800001), 1, 'float'), $rt->component_wise('floor', $_u_speed), 1, 'float')))};
        }
        $st = $rt->assign_swizzle($st, 'x', $rt->binary('+', $rt->swizzle($st, 'x'), $rt->binary('*', $rt->swizzle($st, 'y'), $_u_skew, 1, 'float'), 1, 'float'));
        $p = $rt->binary('*', $st, $rt->binary('-', $rt->f(21), $_u_scale, 1, 'float'), 2, 'float');
        $panPeriod = $rt->f(0.0);
        if ((((($centered) ? 0 : 1)) && ($rt->binary('==', $_u_animation, $rt->i(1))) ? 1 : 0)) {
            $panPeriod = (($rt->binary('==', $_u_patternType, $rt->i(0))) ? ($rt->f(2)) : ($rt->f(1)));
            $p = $rt->assign_swizzle($p, 'x', $rt->binary('+', $rt->swizzle($p, 'x'), $rt->binary('*', $rt->binary('*', $_u_time, $rt->unary('-', $rt->component_wise('floor', $_u_speed)), 1, 'float'), $panPeriod, 1, 'float'), 1, 'float'));
        }
        $m = $rt->f(0);
        if ($rt->binary('==', $_u_patternType, $rt->i(0))) {
            $m = $checkerboard__vec2_float->($p, $_u_smoothness);
        } else {
            if ($rt->binary('==', $_u_patternType, $rt->i(1))) {
                $m = $concentricRings__vec2_float_float->($p, $_u_thickness, $rt->binary('*', $rt->unary('-', $_u_time), $rt->component_wise('floor', $_u_speed), 1, 'float'));
            } else {
                if ($rt->binary('==', $_u_patternType, $rt->i(2))) {
                    $m = $dots__vec2_float->($p, $_u_thickness);
                } else {
                    if ($rt->binary('==', $_u_patternType, $rt->i(3))) {
                        $m = $grid__vec2_float->($p, $_u_thickness);
                    } else {
                        if ($rt->binary('==', $_u_patternType, $rt->i(4))) {
                            $m = $hexagons__vec2_float->($p, $_u_thickness);
                        } else {
                            if ($rt->binary('==', $_u_patternType, $rt->i(5))) {
                                $m = $radialLines__vec2_float_float->($p, $_u_thickness, $rt->binary('*', $_u_time, $rt->component_wise('floor', $_u_speed), 1, 'float'));
                            } else {
                                if ($rt->binary('==', $_u_patternType, $rt->i(6))) {
                                    $m = $spiralPattern__vec2_float_float->($p, $_u_thickness, $rt->binary('*', $rt->unary('-', $_u_time), $rt->component_wise('floor', $_u_speed), 1, 'float'));
                                } else {
                                    if ($rt->binary('==', $_u_patternType, $rt->i(7))) {
                                        $m = $stripes__vec2_float->($p, $_u_thickness);
                                    } else {
                                        if ($rt->binary('==', $_u_patternType, $rt->i(8))) {
                                            $m = $triangularGrid__vec2_float->($p, $_u_thickness);
                                        } else {
                                            if ($rt->binary('==', $_u_patternType, $rt->i(9))) {
                                                $m = $hearts__vec2_float->($p, $_u_thickness);
                                            } else {
                                                if ($rt->binary('==', $_u_patternType, $rt->i(10))) {
                                                    $m = $waves__vec2_float->($p, $_u_thickness);
                                                } else {
                                                    if ($rt->binary('==', $_u_patternType, $rt->i(11))) {
                                                        $m = $zigzag__vec2_float->($p, $_u_thickness);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        $color = $rt->component_wise('mix', $_u_bgColor, $_u_fgColor, $m);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $color, $rt->f(1)))};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
