# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($hash11__float, $hash22__vec2, $lum__vec3, $main__void);
    my $_retc;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_seed = exists $U->{'seed'} ? $U->{'seed'} : 0;
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_inputForce = exists $U->{'inputForce'} ? $U->{'inputForce'} : $rt->f(0.0);
    my $_u_inputDye = exists $U->{'inputDye'} ? $U->{'inputDye'} : $rt->f(0.0);
    my $_u_resetState = exists $U->{'resetState'} ? $U->{'resetState'} : 0;
    my $_u_bufTex = $ctx->texture_binding('bufTex');
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    $g->{fragColor} = $rt->construct(4, 0.0);
    $hash11__float = sub {
        my ($x) = @_;
        return $rt->component_wise('fract', $rt->binary('*', $rt->component_wise('sin', $rt->binary('*', $x, $rt->f(12.989800000000001), 1, 'float')), $rt->f(43758.545299999998), 1, 'float'));
    };
    $hash22__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        $p = $rt->assign_swizzle($p, 'x', $rt->dot($p, $rt->construct(2, $rt->f(127.09999999999999), $rt->f(311.69999999999999))));
        $p = $rt->assign_swizzle($p, 'y', $rt->dot($p, $rt->construct(2, $rt->f(269.5), $rt->f(183.30000000000001))));
        return $rt->component_wise('fract', $rt->binary('*', $rt->component_wise('sin', $p), $rt->f(43758.545299999998), 2, 'float'));
    };
    $lum__vec3 = sub {
        my ($c) = @_;
        $c = $rt->copy($c, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->f(0.21260000000000001), $rt->swizzle($c, 'r'), 1, 'float'), $rt->binary('*', $rt->f(0.71519999999999995), $rt->swizzle($c, 'g'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(0.0722), $rt->swizzle($c, 'b'), 1, 'float'), 1, 'float');
    };
    $main__void = sub {
        my ($_for0_first, $bufferEmpty, $c, $d, $dt, $dye, $falloff, $fragCoord, $grad, $i, $iDye, $iForce, $idf, $lc, $lr, $lu, $prev, $r2, $radius, $seedF, $sign, $tangent, $texSize, $texel, $uv, $vel);
        $texSize = $rt->texture_size($_u_bufTex);
        $fragCoord = $rt->swizzle($ctx->{frag_coord}, 'xy');
        $uv = $rt->binary('/', $fragCoord, $rt->construct(2, $texSize), 2, 'float');
        $prev = $rt->texture($_u_bufTex, $uv);
        $bufferEmpty = $rt->binary('==', $rt->swizzle($prev, 'a'), $rt->f(0));
        $dye = $rt->f(0.0);
        $seedF = $rt->f(0.0);
        $vel = $rt->construct(2, 0.0);
        if ((($_u_resetState) || ($bufferEmpty) ? 1 : 0)) {
            $vel = $rt->construct(2, $rt->f(0));
            $dye = $rt->f(0);
            $seedF = $rt->construct(1, $_u_seed);
            $i = $rt->i(0);
            $_for0_first = 1;
            for my $_for0 (0 .. 1048575) {
                if (!$_for0_first) {
                    $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
                }
                $_for0_first = 0;
                if (!($rt->binary('<', $i, $rt->i(9)))) {
                    last;
                }
                $idf = $rt->construct(1, $i);
                $c = $hash22__vec2->($rt->construct(2, $rt->binary('+', $rt->binary('*', $idf, $rt->f(7.3099999999999996), 1, 'float'), $rt->f(1), 1, 'float'), $rt->binary('+', $rt->binary('*', $seedF, $rt->f(13.699999999999999), 1, 'float'), $idf, 1, 'float')));
                $sign = (($rt->binary('>', $hash11__float->($rt->binary('+', $rt->binary('*', $idf, $rt->f(4.1699999999999999), 1, 'float'), $rt->binary('*', $seedF, $rt->f(5.9000000000000004), 1, 'float'), 1, 'float')), $rt->f(0.5))) ? ($rt->f(1)) : ($rt->unary('-', $rt->f(1))));
                $radius = $rt->binary('+', $rt->f(0.10000000000000001), $rt->binary('*', $rt->f(0.059999999999999998), $hash11__float->($rt->binary('+', $rt->binary('*', $idf, $rt->f(2.1099999999999999), 1, 'float'), $seedF, 1, 'float')), 1, 'float'), 1, 'float');
                $d = $rt->binary('-', $uv, $c, 2, 'float');
                $r2 = $rt->dot($d, $d);
                $falloff = $rt->component_wise('exp', $rt->binary('/', $rt->unary('-', $r2), $rt->binary('*', $rt->binary('*', $rt->f(2), $radius, 1, 'float'), $radius, 1, 'float'), 1, 'float'));
                $tangent = $rt->construct(2, $rt->unary('-', $rt->swizzle($d, 'y')), $rt->swizzle($d, 'x'));
                @{$vel} = map { $rt->f32($_) } @{($rt->binary('+', $vel, $rt->binary('*', $rt->binary('*', $rt->binary('*', $tangent, $sign, 2, 'float'), $falloff, 2, 'float'), $rt->f(12), 2, 'float'), 2, 'float'))};
                $dye = $rt->binary('+', $dye, $falloff, 1, 'float');
            }
            @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $vel, $rt->component_wise('clamp', $dye, $rt->f(0), $rt->f(1)), $rt->f(1)))};
            return;
        }
        $vel = $rt->swizzle($prev, 'rg');
        $dye = $rt->swizzle($prev, 'b');
        $dt = $rt->binary('*', $rt->component_wise('clamp', $_u_speed, $rt->f(0), $rt->f(200)), $rt->f(0.0001), 1, 'float');
        $iForce = $rt->binary('*', $rt->component_wise('clamp', $_u_inputForce, $rt->f(0), $rt->f(100)), $rt->f(0.01), 1, 'float');
        $iDye = $rt->binary('*', $rt->component_wise('clamp', $_u_inputDye, $rt->f(0), $rt->f(100)), $rt->f(0.01), 1, 'float');
        $grad = $rt->construct(2, 0.0);
        $lc = $rt->f(0.0);
        $lr = $rt->f(0.0);
        $lu = $rt->f(0.0);
        $texel = $rt->construct(2, 0.0);
        if ((($rt->binary('>', $iForce, $rt->f(0))) || ($rt->binary('>', $iDye, $rt->f(0))) ? 1 : 0)) {
            $texel = $rt->binary('/', $rt->f(1), $rt->construct(2, $texSize), 2, 'float');
            $lc = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $uv), 'rgb'));
            $lr = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->construct(2, $rt->swizzle($texel, 'x'), $rt->f(0)), 2, 'float')), 'rgb'));
            $lu = $lum__vec3->($rt->swizzle($rt->texture($_u_inputTex, $rt->binary('+', $uv, $rt->construct(2, $rt->f(0), $rt->swizzle($texel, 'y')), 2, 'float')), 'rgb'));
            $grad = $rt->construct(2, $rt->binary('-', $lr, $lc, 1, 'float'), $rt->binary('-', $lu, $lc, 1, 'float'));
            @{$vel} = map { $rt->f32($_) } @{($rt->binary('+', $vel, $rt->binary('*', $rt->binary('*', $grad, $iForce, 2, 'float'), $rt->f(50), 2, 'float'), 2, 'float'))};
            $dye = $rt->binary('+', $dye, $rt->binary('*', $rt->binary('*', $rt->binary('*', $lc, $iDye, 1, 'float'), $dt, 1, 'float'), $rt->f(60), 1, 'float'), 1, 'float');
        }
        $dye = $rt->component_wise('clamp', $dye, $rt->f(0), $rt->f(2));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $vel, $dye, $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
