# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($pcg__uvec3, $prng__vec3, $random__vec2, $map__float_float_float_float_float, $periodicFunction__float, $positiveModulo__int_int, $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2, $constantFromLattice__vec2_vec2_float_float, $constant__vec2_vec2_float_float, $cubic__float, $quadratic3__float_float_float_float, $latticeValue__vec2_vec2_float_float, $cubic3x3ValueNoise__vec2_vec2_float_float, $blendBicubic__float_float_float_float_float, $catmullRom3__float_float_float_float, $catmullRom4__float_float_float_float_float, $blendLinearOrCosine__float_float_float_int, $constantOffset__vec2_vec2_float_float_ivec2, $bicubicValue__vec2_vec2_float_float, $catmullRom3x3ValueNoise__vec2_vec2_float_float, $catmullRom4x4ValueNoise__vec2_vec2_float_float, $mod289__vec3, $mod289__vec2, $permute__vec3, $simplexValue__vec2_vec2_float_float, $sineNoise__vec2_vec2_float_float, $value__vec2_vec2_float_float, $circles__vec2_float, $rings__vec2_float, $diamonds__vec2_float, $shape__vec2_int_float, $offset__vec2_vec2, $generate_octave__vec2_vec2_float_float_float, $multires__vec2_vec2_int_float_float, $main__void);
    my $_retc;
    my $_u_LOOP_OFFSET = exists $U->{'LOOP_OFFSET'} ? $U->{'LOOP_OFFSET'} : 0;
    my $_u_NOISE_TYPE = exists $U->{'NOISE_TYPE'} ? $U->{'NOISE_TYPE'} : 0;
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_seed = exists $U->{'seed'} ? $U->{'seed'} : 0;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_scaleX = exists $U->{'scaleX'} ? $U->{'scaleX'} : $rt->f(0.0);
    my $_u_scaleY = exists $U->{'scaleY'} ? $U->{'scaleY'} : $rt->f(0.0);
    my $_u_octaves = exists $U->{'octaves'} ? $U->{'octaves'} : 0;
    my $_u_ridges = exists $U->{'ridges'} ? $U->{'ridges'} : 0;
    my $_u_loopScale = exists $U->{'loopScale'} ? $U->{'loopScale'} : $rt->f(0.0);
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_colorMode = exists $U->{'colorMode'} ? $U->{'colorMode'} : 0;
    my $_u_wrap = exists $U->{'wrap'} ? $U->{'wrap'} : 0;
    $g->{fragColor} = $rt->construct(4, 0.0);
    $g->{globalCoord} = $rt->construct(2, 0.0);
    $pcg__uvec3 = sub {
        my ($v) = @_;
        $v = $rt->copy($v, 'uint');
        @{$v} = @{($rt->binary('+', $rt->binary('*', $v, $rt->construct(1, $rt->i(1664525), 'uint'), 3, 'uint'), $rt->construct(1, $rt->i(1013904223), 'uint'), 3, 'uint'))};
        $v = $rt->assign_swizzle($v, 'x', $rt->binary('+', $rt->swizzle($v, 'x'), $rt->binary('*', $rt->swizzle($v, 'y'), $rt->swizzle($v, 'z'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'y', $rt->binary('+', $rt->swizzle($v, 'y'), $rt->binary('*', $rt->swizzle($v, 'z'), $rt->swizzle($v, 'x'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'z', $rt->binary('+', $rt->swizzle($v, 'z'), $rt->binary('*', $rt->swizzle($v, 'x'), $rt->swizzle($v, 'y'), 1, 'uint'), 1, 'uint'));
        @{$v} = @{($rt->binary('^', $v, $rt->binary('>>', $v, $rt->construct(1, $rt->i(16), 'uint'), 3, 'uint'), 3, 'uint'))};
        $v = $rt->assign_swizzle($v, 'x', $rt->binary('+', $rt->swizzle($v, 'x'), $rt->binary('*', $rt->swizzle($v, 'y'), $rt->swizzle($v, 'z'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'y', $rt->binary('+', $rt->swizzle($v, 'y'), $rt->binary('*', $rt->swizzle($v, 'z'), $rt->swizzle($v, 'x'), 1, 'uint'), 1, 'uint'));
        $v = $rt->assign_swizzle($v, 'z', $rt->binary('+', $rt->swizzle($v, 'z'), $rt->binary('*', $rt->swizzle($v, 'x'), $rt->swizzle($v, 'y'), 1, 'uint'), 1, 'uint'));
        return $v;
    };
    $prng__vec3 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        $p = $rt->assign_swizzle($p, 'x', (($rt->binary('>=', $rt->swizzle($p, 'x'), $rt->f(0))) ? ($rt->binary('*', $rt->swizzle($p, 'x'), $rt->f(2), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'x')), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float'))));
        $p = $rt->assign_swizzle($p, 'y', (($rt->binary('>=', $rt->swizzle($p, 'y'), $rt->f(0))) ? ($rt->binary('*', $rt->swizzle($p, 'y'), $rt->f(2), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'y')), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float'))));
        $p = $rt->assign_swizzle($p, 'z', (($rt->binary('>=', $rt->swizzle($p, 'z'), $rt->f(0))) ? ($rt->binary('*', $rt->swizzle($p, 'z'), $rt->f(2), 1, 'float')) : ($rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->swizzle($p, 'z')), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float'))));
        return $rt->binary('/', $rt->construct(3, $pcg__uvec3->($rt->construct(3, $p, 'uint'))), $rt->construct(1, $rt->construct(1, $rt->i(4294967295), 'uint')), 3, 'float');
    };
    $random__vec2 = sub {
        my ($st) = @_;
        $st = $rt->copy($st, 'float');
        return $rt->swizzle($prng__vec3->($rt->construct(3, $st, $rt->f(0))), 'x');
    };
    $map__float_float_float_float_float = sub {
        my ($value, $inMin, $inMax, $outMin, $outMax) = @_;
        return $rt->binary('+', $outMin, $rt->binary('/', $rt->binary('*', $rt->binary('-', $outMax, $outMin, 1, 'float'), $rt->binary('-', $value, $inMin, 1, 'float'), 1, 'float'), $rt->binary('-', $inMax, $inMin, 1, 'float'), 1, 'float'), 1, 'float');
    };
    $periodicFunction__float = sub {
        my ($p) = @_;
        return $map__float_float_float_float_float->($rt->component_wise('cos', $rt->binary('*', $p, $rt->f(6.2831853071800001), 1, 'float')), $rt->unary('-', $rt->f(1)), $rt->f(1), $rt->f(0), $rt->f(1));
    };
    $positiveModulo__int_int = sub {
        my ($value, $modulus) = @_;
        my ($r);
        if ($rt->binary('==', $modulus, $rt->i(0))) {
            return $rt->i(0);
        }
        $r = $rt->binary('%', $value, $modulus, 1, 'int');
        return (($rt->binary('<', $r, $rt->i(0))) ? ($rt->binary('+', $r, $modulus, 1, 'int')) : ($r));
    };
    $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2 = sub {
        my ($lattice, $freq, $s, $blend, $offset) = @_;
        $lattice = $rt->copy($lattice, 'float');
        $freq = $rt->copy($freq, 'float');
        $offset = $rt->copy($offset, 'int');
        my ($base, $baseFloor, $frac, $fracBits, $freqX, $freqY, $jitter, $noiseValue, $prngState, $sFrac, $seedBits, $seedInt, $state, $xBits, $xCombined, $xi, $yBits, $yi);
        $baseFloor = $rt->component_wise('floor', $lattice);
        $base = $rt->binary('+', $rt->construct(2, $baseFloor, 'int'), $offset, 2, 'int');
        $frac = $rt->binary('-', $lattice, $baseFloor, 2, 'float');
        $seedInt = $rt->construct(1, $rt->component_wise('floor', $s), 'int');
        $sFrac = $rt->component_wise('fract', $s);
        $xCombined = $rt->binary('+', $rt->swizzle($frac, 'x'), $sFrac, 1, 'float');
        $xi = $rt->binary('+', $rt->swizzle($base, 'x'), $rt->construct(1, $rt->component_wise('floor', $xCombined), 'int'), 1, 'int');
        $yi = $rt->swizzle($base, 'y');
        $freqX = 0;
        $freqY = 0;
        if ($_u_wrap) {
            $freqX = $rt->construct(1, $rt->binary('+', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'), 'int');
            $freqY = $rt->construct(1, $rt->binary('+', $rt->swizzle($freq, 'y'), $rt->f(0.5), 1, 'float'), 'int');
            if ($rt->binary('>', $freqX, $rt->i(0))) {
                $xi = $positiveModulo__int_int->($xi, $freqX);
            }
            if ($rt->binary('>', $freqY, $rt->i(0))) {
                $yi = $positiveModulo__int_int->($yi, $freqY);
            }
        }
        $xBits = $rt->construct(1, $xi, 'uint');
        $yBits = $rt->construct(1, $yi, 'uint');
        $seedBits = $rt->construct(1, $seedInt, 'uint');
        $fracBits = $rt->float_bits_to_uint($sFrac);
        $jitter = $rt->construct(3, $rt->binary('^', $rt->binary('*', $fracBits, $rt->i(374761393), 1, 'uint'), $rt->i(2654435769), 1, 'uint'), $rt->binary('^', $rt->binary('*', $fracBits, $rt->i(668265263), 1, 'uint'), $rt->i(2135587861), 1, 'uint'), $rt->binary('^', $rt->binary('*', $fracBits, $rt->i(2246822519), 1, 'uint'), $rt->i(2496678324), 1, 'uint'), 'uint');
        $state = $rt->binary('^', $rt->construct(3, $xBits, $yBits, $seedBits, 'uint'), $jitter, 3, 'uint');
        $prngState = $pcg__uvec3->($state);
        $noiseValue = $rt->binary('/', $rt->construct(1, $rt->swizzle($prngState, 'x')), $rt->construct(1, $rt->i(4294967295)), 1, 'float');
        return $periodicFunction__float->($rt->binary('-', $noiseValue, $blend, 1, 'float'));
    };
    $constantFromLattice__vec2_vec2_float_float = sub {
        my ($lattice, $freq, $s, $blend) = @_;
        $lattice = $rt->copy($lattice, 'float');
        $freq = $rt->copy($freq, 'float');
        return $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(0), 'int'));
    };
    $constant__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($lattice);
        $lattice = $rt->binary('*', $st, $freq, 2, 'float');
        return $constantFromLattice__vec2_vec2_float_float->($lattice, $freq, $s, $blend);
    };
    $cubic__float = sub {
        my ($t) = @_;
        return $rt->binary('*', $rt->binary('*', $t, $t, 1, 'float'), $rt->binary('-', $rt->f(3), $rt->binary('*', $rt->f(2), $t, 1, 'float'), 1, 'float'), 1, 'float');
    };
    $quadratic3__float_float_float_float = sub {
        my ($p0, $p1, $p2, $t) = @_;
        my ($t2);
        $t2 = $rt->binary('*', $t, $t, 1, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->binary('*', $rt->binary('*', $p0, $rt->f(0.5), 1, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 1, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $p1, $rt->f(0.5), 1, 'float'), $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->f(2)), $t2, 1, 'float'), $rt->binary('*', $rt->f(2), $t, 1, 'float'), 1, 'float'), $rt->f(1), 1, 'float'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $p2, $rt->f(0.5), 1, 'float'), $t2, 1, 'float'), 1, 'float');
    };
    $latticeValue__vec2_vec2_float_float = sub {
        my ($lattice, $freq, $s, $blend) = @_;
        $lattice = $rt->copy($lattice, 'float');
        $freq = $rt->copy($freq, 'float');
        return $constantFromLattice__vec2_vec2_float_float->($lattice, $freq, $s, $blend);
    };
    $cubic3x3ValueNoise__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($f, $lattice, $v00, $v01, $v02, $v10, $v11, $v12, $v20, $v21, $v22, $y0, $y1, $y2);
        $lattice = $rt->binary('*', $st, $freq, 2, 'float');
        $f = $rt->component_wise('fract', $lattice);
        $v00 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->unary('-', $rt->i(1)), 'int'));
        $v10 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->unary('-', $rt->i(1)), 'int'));
        $v20 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->unary('-', $rt->i(1)), 'int'));
        $v01 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(0), 'int'));
        $v11 = $constantFromLattice__vec2_vec2_float_float->($lattice, $freq, $s, $blend);
        $v21 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(0), 'int'));
        $v02 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(1), 'int'));
        $v12 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(1), 'int'));
        $v22 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(1), 'int'));
        $y0 = $quadratic3__float_float_float_float->($v00, $v10, $v20, $rt->swizzle($f, 'x'));
        $y1 = $quadratic3__float_float_float_float->($v01, $v11, $v21, $rt->swizzle($f, 'x'));
        $y2 = $quadratic3__float_float_float_float->($v02, $v12, $v22, $rt->swizzle($f, 'x'));
        return $quadratic3__float_float_float_float->($y0, $y1, $y2, $rt->swizzle($f, 'y'));
    };
    $blendBicubic__float_float_float_float_float = sub {
        my ($p0, $p1, $p2, $p3, $t) = @_;
        my ($b0, $b1, $b2, $b3, $t2, $t3);
        $t2 = $rt->binary('*', $t, $t, 1, 'float');
        $t3 = $rt->binary('*', $t2, $t, 1, 'float');
        $b0 = $rt->binary('/', $rt->binary('*', $rt->binary('*', $rt->binary('-', $rt->f(1), $t, 1, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 1, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 1, 'float'), $rt->f(6), 1, 'float');
        $b1 = $rt->binary('/', $rt->binary('+', $rt->binary('-', $rt->binary('*', $rt->f(3), $t3, 1, 'float'), $rt->binary('*', $rt->f(6), $t2, 1, 'float'), 1, 'float'), $rt->f(4), 1, 'float'), $rt->f(6), 1, 'float');
        $b2 = $rt->binary('/', $rt->binary('+', $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->f(3)), $t3, 1, 'float'), $rt->binary('*', $rt->f(3), $t2, 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(3), $t, 1, 'float'), 1, 'float'), $rt->f(1), 1, 'float'), $rt->f(6), 1, 'float');
        $b3 = $rt->binary('/', $t3, $rt->f(6), 1, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('+', $rt->binary('*', $p0, $b0, 1, 'float'), $rt->binary('*', $p1, $b1, 1, 'float'), 1, 'float'), $rt->binary('*', $p2, $b2, 1, 'float'), 1, 'float'), $rt->binary('*', $p3, $b3, 1, 'float'), 1, 'float');
    };
    $catmullRom3__float_float_float_float = sub {
        my ($p0, $p1, $p2, $t) = @_;
        my ($t2, $t3);
        $t2 = $rt->binary('*', $t, $t, 1, 'float');
        $t3 = $rt->binary('*', $t2, $t, 1, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('+', $p1, $rt->binary('*', $rt->binary('*', $rt->f(0.5), $t, 1, 'float'), $rt->binary('-', $p2, $p0, 1, 'float'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $rt->f(0.5), $t2, 1, 'float'), $rt->binary('-', $rt->binary('+', $rt->binary('-', $rt->binary('*', $rt->f(2), $p0, 1, 'float'), $rt->binary('*', $rt->f(5), $p1, 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(4), $p2, 1, 'float'), 1, 'float'), $p0, 1, 'float'), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $rt->f(0.5), $t3, 1, 'float'), $rt->binary('+', $rt->binary('-', $rt->binary('+', $rt->unary('-', $p0), $rt->binary('*', $rt->f(3), $p1, 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(3), $p2, 1, 'float'), 1, 'float'), $p0, 1, 'float'), 1, 'float'), 1, 'float');
    };
    $catmullRom4__float_float_float_float_float = sub {
        my ($p0, $p1, $p2, $p3, $t) = @_;
        return $rt->binary('+', $p1, $rt->binary('*', $rt->binary('*', $rt->f(0.5), $t, 1, 'float'), $rt->binary('+', $rt->binary('-', $p2, $p0, 1, 'float'), $rt->binary('*', $t, $rt->binary('+', $rt->binary('-', $rt->binary('+', $rt->binary('-', $rt->binary('*', $rt->f(2), $p0, 1, 'float'), $rt->binary('*', $rt->f(5), $p1, 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(4), $p2, 1, 'float'), 1, 'float'), $p3, 1, 'float'), $rt->binary('*', $t, $rt->binary('-', $rt->binary('+', $rt->binary('*', $rt->f(3), $rt->binary('-', $p1, $p2, 1, 'float'), 1, 'float'), $p3, 1, 'float'), $p0, 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float'), 1, 'float');
    };
    $blendLinearOrCosine__float_float_float_int = sub {
        my ($a, $b, $amount, $nType) = @_;
        if ($rt->binary('==', $nType, $rt->i(1))) {
            return $rt->component_wise('mix', $a, $b, $amount);
        }
        return $rt->component_wise('mix', $a, $b, $rt->component_wise('smoothstep', $rt->f(0), $rt->f(1), $amount));
    };
    $constantOffset__vec2_vec2_float_float_ivec2 = sub {
        my ($lattice, $freq, $s, $blend, $offset) = @_;
        $lattice = $rt->copy($lattice, 'float');
        $freq = $rt->copy($freq, 'float');
        $offset = $rt->copy($offset, 'int');
        return $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $offset);
    };
    $bicubicValue__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($frac, $lattice, $x0y0, $x0y1, $x0y2, $x0y3, $x1y0, $x1y1, $x1y2, $x1y3, $x2y0, $x2y1, $x2y2, $x2y3, $x3y0, $x3y1, $x3y2, $x3y3, $y0, $y1, $y2, $y3);
        $lattice = $rt->binary('*', $st, $freq, 2, 'float');
        $x0y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->unary('-', $rt->i(1)), 'int'));
        $x0y1 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(0), 'int'));
        $x0y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(1), 'int'));
        $x0y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(2), 'int'));
        $x1y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->unary('-', $rt->i(1)), 'int'));
        $x1y1 = $constantFromLattice__vec2_vec2_float_float->($lattice, $freq, $s, $blend);
        $x1y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(1), 'int'));
        $x1y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(2), 'int'));
        $x2y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->unary('-', $rt->i(1)), 'int'));
        $x2y1 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(0), 'int'));
        $x2y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(1), 'int'));
        $x2y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(2), 'int'));
        $x3y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->unary('-', $rt->i(1)), 'int'));
        $x3y1 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->i(0), 'int'));
        $x3y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->i(1), 'int'));
        $x3y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->i(2), 'int'));
        $frac = $rt->component_wise('fract', $lattice);
        $y0 = $blendBicubic__float_float_float_float_float->($x0y0, $x1y0, $x2y0, $x3y0, $rt->swizzle($frac, 'x'));
        $y1 = $blendBicubic__float_float_float_float_float->($x0y1, $x1y1, $x2y1, $x3y1, $rt->swizzle($frac, 'x'));
        $y2 = $blendBicubic__float_float_float_float_float->($x0y2, $x1y2, $x2y2, $x3y2, $rt->swizzle($frac, 'x'));
        $y3 = $blendBicubic__float_float_float_float_float->($x0y3, $x1y3, $x2y3, $x3y3, $rt->swizzle($frac, 'x'));
        return $blendBicubic__float_float_float_float_float->($y0, $y1, $y2, $y3, $rt->swizzle($frac, 'y'));
    };
    $catmullRom3x3ValueNoise__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($f, $lattice, $v00, $v01, $v02, $v10, $v11, $v12, $v20, $v21, $v22, $y0, $y1, $y2);
        $lattice = $rt->binary('*', $st, $freq, 2, 'float');
        $f = $rt->component_wise('fract', $lattice);
        $v00 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->unary('-', $rt->i(1)), 'int'));
        $v10 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->unary('-', $rt->i(1)), 'int'));
        $v20 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->unary('-', $rt->i(1)), 'int'));
        $v01 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(0), 'int'));
        $v11 = $constantFromLattice__vec2_vec2_float_float->($lattice, $freq, $s, $blend);
        $v21 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(0), 'int'));
        $v02 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(1), 'int'));
        $v12 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(1), 'int'));
        $v22 = $constantFromLatticeWithOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(1), 'int'));
        $y0 = $catmullRom3__float_float_float_float->($v00, $v10, $v20, $rt->swizzle($f, 'x'));
        $y1 = $catmullRom3__float_float_float_float->($v01, $v11, $v21, $rt->swizzle($f, 'x'));
        $y2 = $catmullRom3__float_float_float_float->($v02, $v12, $v22, $rt->swizzle($f, 'x'));
        return $catmullRom3__float_float_float_float->($y0, $y1, $y2, $rt->swizzle($f, 'y'));
    };
    $catmullRom4x4ValueNoise__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($frac, $lattice, $x0y0, $x0y1, $x0y2, $x0y3, $x1y0, $x1y1, $x1y2, $x1y3, $x2y0, $x2y1, $x2y2, $x2y3, $x3y0, $x3y1, $x3y2, $x3y3, $y0, $y1, $y2, $y3);
        $lattice = $rt->binary('*', $st, $freq, 2, 'float');
        $x0y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->unary('-', $rt->i(1)), 'int'));
        $x0y1 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(0), 'int'));
        $x0y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(1), 'int'));
        $x0y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->unary('-', $rt->i(1)), $rt->i(2), 'int'));
        $x1y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->unary('-', $rt->i(1)), 'int'));
        $x1y1 = $constantFromLattice__vec2_vec2_float_float->($lattice, $freq, $s, $blend);
        $x1y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(1), 'int'));
        $x1y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(2), 'int'));
        $x2y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->unary('-', $rt->i(1)), 'int'));
        $x2y1 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(0), 'int'));
        $x2y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(1), 'int'));
        $x2y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(2), 'int'));
        $x3y0 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->unary('-', $rt->i(1)), 'int'));
        $x3y1 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->i(0), 'int'));
        $x3y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->i(1), 'int'));
        $x3y3 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(2), $rt->i(2), 'int'));
        $frac = $rt->component_wise('fract', $lattice);
        $y0 = $catmullRom4__float_float_float_float_float->($x0y0, $x1y0, $x2y0, $x3y0, $rt->swizzle($frac, 'x'));
        $y1 = $catmullRom4__float_float_float_float_float->($x0y1, $x1y1, $x2y1, $x3y1, $rt->swizzle($frac, 'x'));
        $y2 = $catmullRom4__float_float_float_float_float->($x0y2, $x1y2, $x2y2, $x3y2, $rt->swizzle($frac, 'x'));
        $y3 = $catmullRom4__float_float_float_float_float->($x0y3, $x1y3, $x2y3, $x3y3, $rt->swizzle($frac, 'x'));
        return $catmullRom4__float_float_float_float_float->($y0, $y1, $y2, $y3, $rt->swizzle($frac, 'y'));
    };
    $mod289__vec3 = sub {
        my ($x) = @_;
        $x = $rt->copy($x, 'float');
        return $rt->binary('-', $x, $rt->binary('*', $rt->component_wise('floor', $rt->binary('*', $x, $rt->binary('/', $rt->f(1), $rt->f(289), 1, 'float'), 3, 'float')), $rt->f(289), 3, 'float'), 3, 'float');
    };
    $mod289__vec2 = sub {
        my ($x) = @_;
        $x = $rt->copy($x, 'float');
        return $rt->binary('-', $x, $rt->binary('*', $rt->component_wise('floor', $rt->binary('*', $x, $rt->binary('/', $rt->f(1), $rt->f(289), 1, 'float'), 2, 'float')), $rt->f(289), 2, 'float'), 2, 'float');
    };
    $permute__vec3 = sub {
        my ($x) = @_;
        $x = $rt->copy($x, 'float');
        return $mod289__vec3->($rt->binary('*', $rt->binary('+', $rt->binary('*', $x, $rt->f(34), 3, 'float'), $rt->f(1), 3, 'float'), $x, 3, 'float'));
    };
    $simplexValue__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($C, $_g, $a0, $h, $i, $i1, $m, $ox, $p, $uv, $v, $x, $x0, $x12);
        $C = $rt->construct(4, $rt->f(0.211324865405187), $rt->f(0.36602540378443899), $rt->unary('-', $rt->f(0.57735026918962595)), $rt->f(0.024390243902439001));
        $uv = $rt->binary('*', $st, $freq, 2, 'float');
        $uv = $rt->assign_swizzle($uv, 'x', $rt->binary('+', $rt->swizzle($uv, 'x'), $s, 1, 'float'));
        $i = $rt->component_wise('floor', $rt->binary('+', $uv, $rt->dot($uv, $rt->swizzle($C, 'yy')), 2, 'float'));
        $x0 = $rt->binary('+', $rt->binary('-', $uv, $i, 2, 'float'), $rt->dot($i, $rt->swizzle($C, 'xx')), 2, 'float');
        $i1 = (($rt->binary('>', $rt->swizzle($x0, 'x'), $rt->swizzle($x0, 'y'))) ? ($rt->construct(2, $rt->f(1), $rt->f(0))) : ($rt->construct(2, $rt->f(0), $rt->f(1))));
        $x12 = $rt->binary('+', $rt->swizzle($x0, 'xyxy'), $rt->swizzle($C, 'xxzz'), 4, 'float');
        $x12 = $rt->assign_swizzle($x12, 'xy', $rt->binary('-', $rt->swizzle($x12, 'xy'), $i1, 2, 'float'));
        @{$i} = map { $rt->f32($_) } @{($mod289__vec2->($i))};
        $p = $permute__vec3->($rt->binary('+', $rt->binary('+', $permute__vec3->($rt->binary('+', $rt->swizzle($i, 'y'), $rt->construct(3, $rt->f(0), $rt->swizzle($i1, 'y'), $rt->f(1)), 3, 'float')), $rt->swizzle($i, 'x'), 3, 'float'), $rt->construct(3, $rt->f(0), $rt->swizzle($i1, 'x'), $rt->f(1)), 3, 'float'));
        $m = $rt->component_wise('max', $rt->binary('-', $rt->f(0.5), $rt->construct(3, $rt->dot($x0, $x0), $rt->dot($rt->swizzle($x12, 'xy'), $rt->swizzle($x12, 'xy')), $rt->dot($rt->swizzle($x12, 'zw'), $rt->swizzle($x12, 'zw'))), 3, 'float'), $rt->f(0));
        @{$m} = map { $rt->f32($_) } @{($rt->binary('*', $m, $m, 3, 'float'))};
        @{$m} = map { $rt->f32($_) } @{($rt->binary('*', $m, $m, 3, 'float'))};
        $x = $rt->binary('-', $rt->binary('*', $rt->f(2), $rt->component_wise('fract', $rt->binary('*', $p, $rt->swizzle($C, 'www'), 3, 'float')), 3, 'float'), $rt->f(1), 3, 'float');
        $h = $rt->binary('-', $rt->component_wise('abs', $x), $rt->f(0.5), 3, 'float');
        $ox = $rt->component_wise('floor', $rt->binary('+', $x, $rt->f(0.5), 3, 'float'));
        $a0 = $rt->binary('-', $x, $ox, 3, 'float');
        @{$m} = map { $rt->f32($_) } @{($rt->binary('*', $m, $rt->binary('-', $rt->f(1.79284291400159), $rt->binary('*', $rt->f(0.85373472095313996), $rt->binary('+', $rt->binary('*', $a0, $a0, 3, 'float'), $rt->binary('*', $h, $h, 3, 'float'), 3, 'float'), 3, 'float'), 3, 'float'), 3, 'float'))};
        $_g = $rt->construct(3, 0.0);
        $_g = $rt->assign_swizzle($_g, 'x', $rt->binary('+', $rt->binary('*', $rt->swizzle($a0, 'x'), $rt->swizzle($x0, 'x'), 1, 'float'), $rt->binary('*', $rt->swizzle($h, 'x'), $rt->swizzle($x0, 'y'), 1, 'float'), 1, 'float'));
        $_g = $rt->assign_swizzle($_g, 'yz', $rt->binary('+', $rt->binary('*', $rt->swizzle($a0, 'yz'), $rt->swizzle($x12, 'xz'), 2, 'float'), $rt->binary('*', $rt->swizzle($h, 'yz'), $rt->swizzle($x12, 'yw'), 2, 'float'), 2, 'float'));
        $v = $rt->binary('*', $rt->f(130), $rt->dot($m, $_g), 1, 'float');
        return $periodicFunction__float->($rt->binary('-', $map__float_float_float_float_float->($v, $rt->unary('-', $rt->f(1)), $rt->f(1), $rt->f(0), $rt->f(1)), $blend, 1, 'float'));
    };
    $sineNoise__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($a, $b, $c, $r1, $r2, $x, $y);
        @{$st} = map { $rt->f32($_) } @{($rt->binary('*', $st, $freq, 2, 'float'))};
        $st = $rt->assign_swizzle($st, 'x', $rt->binary('+', $rt->swizzle($st, 'x'), $s, 1, 'float'));
        $a = $blend;
        $b = $blend;
        $c = $rt->binary('-', $rt->f(1), $blend, 1, 'float');
        $r1 = $rt->binary('+', $rt->binary('*', $prng__vec3->($rt->construct(3, $s)), $rt->f(0.75), 3, 'float'), $rt->f(0.125), 3, 'float');
        $r2 = $rt->binary('+', $rt->binary('*', $prng__vec3->($rt->construct(3, $rt->binary('+', $s, $rt->f(10), 1, 'float'))), $rt->f(0.75), 3, 'float'), $rt->f(0.125), 3, 'float');
        $x = $rt->component_wise('sin', $rt->binary('+', $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->swizzle($r1, 'x'), $rt->swizzle($st, 'y'), 1, 'float'), $rt->component_wise('sin', $rt->binary('+', $rt->binary('*', $rt->swizzle($r1, 'y'), $rt->swizzle($st, 'x'), 1, 'float'), $a, 1, 'float')), 1, 'float'), $rt->component_wise('sin', $rt->binary('+', $rt->binary('*', $rt->swizzle($r1, 'z'), $rt->swizzle($st, 'x'), 1, 'float'), $b, 1, 'float')), 1, 'float'), $c, 1, 'float'));
        $y = $rt->component_wise('sin', $rt->binary('+', $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->swizzle($r2, 'x'), $rt->swizzle($st, 'x'), 1, 'float'), $rt->component_wise('sin', $rt->binary('+', $rt->binary('*', $rt->swizzle($r2, 'y'), $rt->swizzle($st, 'y'), 1, 'float'), $b, 1, 'float')), 1, 'float'), $rt->component_wise('sin', $rt->binary('+', $rt->binary('*', $rt->swizzle($r2, 'z'), $rt->swizzle($st, 'y'), 1, 'float'), $c, 1, 'float')), 1, 'float'), $a, 1, 'float'));
        return $rt->binary('+', $rt->binary('*', $rt->binary('+', $x, $y, 1, 'float'), $rt->f(0.5), 1, 'float'), $rt->f(0.5), 1, 'float');
    };
    $value__vec2_vec2_float_float = sub {
        my ($st, $freq, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($a, $b, $frac, $lattice, $x1y1, $x1y2, $x2y1, $x2y2);
        $a = $rt->f(0.0);
        $b = $rt->f(0.0);
        $frac = $rt->construct(2, 0.0);
        $lattice = $rt->construct(2, 0.0);
        $x1y1 = $rt->f(0.0);
        $x1y2 = $rt->f(0.0);
        $x2y1 = $rt->f(0.0);
        $x2y2 = $rt->f(0.0);
        if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(3))) {
            return $catmullRom3x3ValueNoise__vec2_vec2_float_float->($st, $freq, $s, $blend);
        } else {
            if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(4))) {
                return $catmullRom4x4ValueNoise__vec2_vec2_float_float->($st, $freq, $s, $blend);
            } else {
                if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(5))) {
                    return $cubic3x3ValueNoise__vec2_vec2_float_float->($st, $freq, $s, $blend);
                } else {
                    if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(6))) {
                        return $bicubicValue__vec2_vec2_float_float->($st, $freq, $s, $blend);
                    } else {
                        if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(10))) {
                            return $simplexValue__vec2_vec2_float_float->($st, $freq, $s, $blend);
                        } else {
                            if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(11))) {
                                return $sineNoise__vec2_vec2_float_float->($st, $freq, $s, $blend);
                            } else {
                                if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(0))) {
                                    return $constantFromLattice__vec2_vec2_float_float->($rt->binary('*', $st, $freq, 2, 'float'), $freq, $s, $blend);
                                } else {
                                    $lattice = $rt->binary('*', $st, $freq, 2, 'float');
                                    $x1y1 = $constantFromLattice__vec2_vec2_float_float->($lattice, $freq, $s, $blend);
                                    $x2y1 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(0), 'int'));
                                    $x1y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(0), $rt->i(1), 'int'));
                                    $x2y2 = $constantOffset__vec2_vec2_float_float_ivec2->($lattice, $freq, $s, $blend, $rt->construct(2, $rt->i(1), $rt->i(1), 'int'));
                                    $frac = $rt->component_wise('fract', $lattice);
                                    $a = $blendLinearOrCosine__float_float_float_int->($x1y1, $x2y1, $rt->swizzle($frac, 'x'), $_u_NOISE_TYPE);
                                    $b = $blendLinearOrCosine__float_float_float_int->($x1y2, $x2y2, $rt->swizzle($frac, 'x'), $_u_NOISE_TYPE);
                                    return $blendLinearOrCosine__float_float_float_int->($a, $b, $rt->swizzle($frac, 'y'), $_u_NOISE_TYPE);
                                }
                            }
                        }
                    }
                }
            }
        }
    };
    $circles__vec2_float = sub {
        my ($st, $freq) = @_;
        $st = $rt->copy($st, 'float');
        my ($dist);
        $dist = $rt->length($rt->binary('-', $st, $rt->construct(2, $rt->binary('/', $rt->binary('*', $rt->f(0.5), $rt->swizzle($_u_fullResolution, 'x'), 1, 'float'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float'), $rt->f(0.5)), 2, 'float'));
        return $rt->binary('*', $dist, $freq, 1, 'float');
    };
    $rings__vec2_float = sub {
        my ($st, $freq) = @_;
        $st = $rt->copy($st, 'float');
        my ($dist);
        $dist = $rt->length($rt->binary('-', $st, $rt->construct(2, $rt->binary('/', $rt->binary('*', $rt->f(0.5), $rt->swizzle($_u_fullResolution, 'x'), 1, 'float'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float'), $rt->f(0.5)), 2, 'float'));
        return $rt->component_wise('cos', $rt->binary('*', $rt->binary('*', $dist, $rt->f(3.1415926535900001), 1, 'float'), $freq, 1, 'float'));
    };
    $diamonds__vec2_float = sub {
        my ($st, $freq) = @_;
        $st = $rt->copy($st, 'float');
        @{$st} = map { $rt->f32($_) } @{($rt->binary('/', $g->{globalCoord}, $rt->swizzle($_u_fullResolution, 'y'), 2, 'float'))};
        @{$st} = map { $rt->f32($_) } @{($rt->binary('-', $st, $rt->construct(2, $rt->binary('/', $rt->binary('*', $rt->f(0.5), $rt->swizzle($_u_fullResolution, 'x'), 1, 'float'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float'), $rt->f(0.5)), 2, 'float'))};
        @{$st} = map { $rt->f32($_) } @{($rt->binary('*', $st, $freq, 2, 'float'))};
        return $rt->binary('+', $rt->component_wise('cos', $rt->binary('*', $rt->swizzle($st, 'x'), $rt->f(3.1415926535900001), 1, 'float')), $rt->component_wise('cos', $rt->binary('*', $rt->swizzle($st, 'y'), $rt->f(3.1415926535900001), 1, 'float')), 1, 'float');
    };
    $shape__vec2_int_float = sub {
        my ($st, $sides, $blend) = @_;
        $st = $rt->copy($st, 'float');
        my ($a, $r);
        @{$st} = map { $rt->f32($_) } @{($rt->binary('-', $rt->binary('*', $st, $rt->f(2), 2, 'float'), $rt->construct(2, $rt->binary('/', $rt->swizzle($_u_fullResolution, 'x'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float'), $rt->f(1)), 2, 'float'))};
        $a = $rt->binary('+', $rt->component_wise('atan', $rt->swizzle($st, 'x'), $rt->swizzle($st, 'y')), $rt->f(3.1415926535900001), 1, 'float');
        $r = $rt->binary('/', $rt->f(6.2831853071800001), $rt->construct(1, $sides), 1, 'float');
        return $rt->binary('*', $rt->binary('*', $rt->component_wise('cos', $rt->binary('-', $rt->binary('*', $rt->component_wise('floor', $rt->binary('+', $rt->f(0.5), $rt->binary('/', $a, $r, 1, 'float'), 1, 'float')), $r, 1, 'float'), $a, 1, 'float')), $rt->length($st), 1, 'float'), $blend, 1, 'float');
    };
    $offset__vec2_vec2 = sub {
        my ($st, $freq) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(10))) {
            return $circles__vec2_float->($st, $rt->swizzle($freq, 'x'));
        } else {
            if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(20))) {
                return $shape__vec2_int_float->($st, $rt->i(3), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
            } else {
                if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(30))) {
                    return $rt->binary('*', $rt->binary('*', $rt->binary('+', $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($st, 'x'), $rt->binary('/', $rt->binary('*', $rt->f(0.5), $rt->swizzle($_u_fullResolution, 'x'), 1, 'float'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float'), 1, 'float')), $rt->component_wise('abs', $rt->binary('-', $rt->swizzle($st, 'y'), $rt->f(0.5), 1, 'float')), 1, 'float'), $rt->swizzle($freq, 'x'), 1, 'float'), $rt->f(0.5), 1, 'float');
                } else {
                    if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(40))) {
                        return $shape__vec2_int_float->($st, $rt->i(4), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                    } else {
                        if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(50))) {
                            return $shape__vec2_int_float->($st, $rt->i(5), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                        } else {
                            if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(60))) {
                                return $shape__vec2_int_float->($st, $rt->i(6), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                            } else {
                                if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(70))) {
                                    return $shape__vec2_int_float->($st, $rt->i(7), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                                } else {
                                    if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(80))) {
                                        return $shape__vec2_int_float->($st, $rt->i(8), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                                    } else {
                                        if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(90))) {
                                            return $shape__vec2_int_float->($st, $rt->i(9), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                                        } else {
                                            if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(100))) {
                                                return $shape__vec2_int_float->($st, $rt->i(10), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                                            } else {
                                                if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(110))) {
                                                    return $shape__vec2_int_float->($st, $rt->i(11), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                                                } else {
                                                    if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(120))) {
                                                        return $shape__vec2_int_float->($st, $rt->i(12), $rt->binary('*', $rt->swizzle($freq, 'x'), $rt->f(0.5), 1, 'float'));
                                                    } else {
                                                        if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(200))) {
                                                            return $rt->binary('*', $rt->binary('*', $rt->swizzle($st, 'x'), $rt->swizzle($freq, 'x'), 1, 'float'), $rt->f(0.5), 1, 'float');
                                                        } else {
                                                            if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(210))) {
                                                                return $rt->binary('*', $rt->binary('*', $rt->swizzle($st, 'y'), $rt->swizzle($freq, 'x'), 1, 'float'), $rt->f(0.5), 1, 'float');
                                                            } else {
                                                                if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(300))) {
                                                                    @{$st} = map { $rt->f32($_) } @{($rt->binary('-', $st, $rt->construct(2, $rt->binary('*', $rt->binary('/', $rt->swizzle($_u_fullResolution, 'x'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float'), $rt->f(0.5), 1, 'float'), $rt->f(0.5)), 2, 'float'))};
                                                                    return $value__vec2_vec2_float_float->($st, $freq, $rt->binary('+', $rt->construct(1, $_u_seed), $rt->f(50), 1, 'float'), $rt->f(0));
                                                                } else {
                                                                    if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(400))) {
                                                                        return $rt->binary('-', $rt->f(1), $rings__vec2_float->($st, $rt->swizzle($freq, 'x')), 1, 'float');
                                                                    } else {
                                                                        if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(410))) {
                                                                            return $rt->binary('-', $rt->f(1), $diamonds__vec2_float->($st, $rt->swizzle($freq, 'x')), 1, 'float');
                                                                        } else {
                                                                            return $rt->f(0);
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    };
    $generate_octave__vec2_vec2_float_float_float = sub {
        my ($st, $freq, $s, $blend, $layer) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($color);
        $color = $rt->construct(3, $rt->f(0));
        $color = $rt->assign_swizzle($color, 'r', $value__vec2_vec2_float_float->($st, $freq, $s, $blend));
        $color = $rt->assign_swizzle($color, 'g', $value__vec2_vec2_float_float->($st, $freq, $rt->binary('+', $s, $rt->f(10), 1, 'float'), $blend));
        $color = $rt->assign_swizzle($color, 'b', $value__vec2_vec2_float_float->($st, $freq, $rt->binary('+', $s, $rt->f(20), 1, 'float'), $blend));
        return $color;
    };
    $multires__vec2_vec2_int_float_float = sub {
        my ($st, $freq, $oct, $s, $blend) = @_;
        $st = $rt->copy($st, 'float');
        $freq = $rt->copy($freq, 'float');
        my ($_for0_first, $baseFreq, $color, $i, $layer, $multiplicand, $multiplier);
        $color = $rt->construct(3, $rt->f(0));
        $multiplicand = $rt->f(0);
        $i = $rt->i(1);
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<=', $i, $oct))) {
                last;
            }
            $multiplier = $rt->component_wise('pow', $rt->f(2), $rt->construct(1, $i));
            $baseFreq = $rt->binary('*', $rt->binary('*', $freq, $rt->f(0.5), 2, 'float'), $multiplier, 2, 'float');
            $multiplicand = $rt->binary('+', $multiplicand, $rt->binary('/', $rt->f(1), $multiplier, 1, 'float'), 1, 'float');
            $layer = $generate_octave__vec2_vec2_float_float_float->($st, $baseFreq, $rt->binary('+', $s, $rt->binary('*', $rt->f(10), $rt->construct(1, $i), 1, 'float'), 1, 'float'), $blend, $rt->construct(1, $i));
            $color = $rt->assign_swizzle($color, 'rgb', $rt->binary('+', $rt->swizzle($color, 'rgb'), $rt->binary('/', $layer, $multiplier, 3, 'float'), 3, 'float'));
        }
        $color = $rt->assign_swizzle($color, 'rgb', $rt->binary('/', $rt->swizzle($color, 'rgb'), $multiplicand, 3, 'float'));
        if ($rt->binary('==', $_u_colorMode, $rt->i(0))) {
            if ($_u_ridges) {
                $color = $rt->assign_swizzle($color, 'b', $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->binary('*', $rt->swizzle($color, 'b'), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float')), 1, 'float'));
            }
            return $rt->construct(3, $rt->swizzle($color, 'b'));
        } else {
            if ($_u_ridges) {
                $color = $rt->assign_swizzle($color, 'r', $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->binary('*', $rt->swizzle($color, 'r'), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float')), 1, 'float'));
                $color = $rt->assign_swizzle($color, 'g', $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->binary('*', $rt->swizzle($color, 'g'), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float')), 1, 'float'));
                $color = $rt->assign_swizzle($color, 'b', $rt->binary('-', $rt->f(1), $rt->component_wise('abs', $rt->binary('-', $rt->binary('*', $rt->swizzle($color, 'b'), $rt->f(2), 1, 'float'), $rt->f(1), 1, 'float')), 1, 'float'));
            }
            return $color;
        }
    };
    $main__void = sub {
        my ($base, $blend, $centered, $color, $freq, $lf, $nominalFreq, $st, $t);
        @{$g->{globalCoord}} = map { $rt->f32($_) } @{($rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float'))};
        $color = $rt->construct(4, $rt->f(0), $rt->f(0), $rt->f(0), $rt->f(1));
        $st = $rt->binary('/', $g->{globalCoord}, $rt->swizzle($_u_fullResolution, 'y'), 2, 'float');
        $centered = $rt->binary('-', $st, $rt->construct(2, $rt->binary('*', $rt->binary('/', $rt->swizzle($_u_fullResolution, 'x'), $rt->swizzle($_u_fullResolution, 'y'), 1, 'float'), $rt->f(0.5), 1, 'float'), $rt->f(0.5)), 2, 'float');
        $freq = $rt->construct(2, $rt->f(1));
        $lf = $rt->construct(2, $rt->f(1));
        if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(11))) {
            $freq = $rt->assign_swizzle($freq, 'x', $map__float_float_float_float_float->($_u_scaleX, $rt->f(1), $rt->f(100), $rt->f(40), $rt->f(1)));
            $freq = $rt->assign_swizzle($freq, 'y', $map__float_float_float_float_float->($_u_scaleY, $rt->f(1), $rt->f(100), $rt->f(40), $rt->f(1)));
            @{$lf} = map { $rt->f32($_) } @{($rt->construct(2, $map__float_float_float_float_float->($_u_loopScale, $rt->f(1), $rt->f(100), $rt->f(10), $rt->f(1))))};
        } else {
            if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(10))) {
                $freq = $rt->assign_swizzle($freq, 'x', $map__float_float_float_float_float->($_u_scaleX, $rt->f(1), $rt->f(100), $rt->f(6), $rt->f(0.5)));
                $freq = $rt->assign_swizzle($freq, 'y', $map__float_float_float_float_float->($_u_scaleY, $rt->f(1), $rt->f(100), $rt->f(6), $rt->f(0.5)));
                @{$lf} = map { $rt->f32($_) } @{($rt->construct(2, $map__float_float_float_float_float->($_u_loopScale, $rt->f(1), $rt->f(100), $rt->f(6), $rt->f(0.5))))};
            } else {
                $freq = $rt->assign_swizzle($freq, 'x', $map__float_float_float_float_float->($_u_scaleX, $rt->f(1), $rt->f(100), $rt->f(20), $rt->f(3)));
                $freq = $rt->assign_swizzle($freq, 'y', $map__float_float_float_float_float->($_u_scaleY, $rt->f(1), $rt->f(100), $rt->f(20), $rt->f(3)));
                @{$lf} = map { $rt->f32($_) } @{($rt->construct(2, $map__float_float_float_float_float->($_u_loopScale, $rt->f(1), $rt->f(100), $rt->f(12), $rt->f(3))))};
            }
        }
        if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(300))) {
            $base = $rt->f(0.0);
            if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(11))) {
                $base = $map__float_float_float_float_float->($rt->f(75), $rt->f(1), $rt->f(100), $rt->f(40), $rt->f(1));
            } else {
                if ($rt->binary('==', $_u_NOISE_TYPE, $rt->i(10))) {
                    $base = $map__float_float_float_float_float->($rt->f(75), $rt->f(1), $rt->f(100), $rt->f(6), $rt->f(0.5));
                } else {
                    $base = $map__float_float_float_float_float->($rt->f(75), $rt->f(1), $rt->f(100), $rt->f(20), $rt->f(3));
                }
            }
            $nominalFreq = $rt->construct(2, $base);
            @{$lf} = map { $rt->f32($_) } @{($rt->binary('*', $lf, $rt->binary('/', $freq, $nominalFreq, 2, 'float'), 2, 'float'))};
        }
        if ((($rt->binary('!=', $_u_NOISE_TYPE, $rt->i(4))) && ($rt->binary('!=', $_u_NOISE_TYPE, $rt->i(10))) ? 1 : 0)) {
            if ($_u_wrap) {
                @{$freq} = map { $rt->f32($_) } @{($rt->component_wise('floor', $freq))};
                if ($rt->binary('==', $_u_LOOP_OFFSET, $rt->i(300))) {
                    @{$lf} = map { $rt->f32($_) } @{($rt->component_wise('floor', $lf))};
                }
            }
        }
        $t = $rt->f(1);
        if ($rt->binary('<', $_u_speed, $rt->f(0))) {
            $t = $rt->binary('+', $_u_time, $offset__vec2_vec2->($st, $lf), 1, 'float');
        } else {
            $t = $rt->binary('-', $_u_time, $offset__vec2_vec2->($st, $lf), 1, 'float');
        }
        $blend = $rt->binary('*', $rt->binary('*', $periodicFunction__float->($t), $rt->component_wise('abs', $_u_speed), 1, 'float'), $rt->f(0.01), 1, 'float');
        $color = $rt->assign_swizzle($color, 'rgb', $multires__vec2_vec2_int_float_float->($centered, $freq, $_u_octaves, $rt->construct(1, $_u_seed), $blend));
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($color)};
    };
    $main__void->();
    my $_c = $g->{fragColor};
    $out->[0] = $rt->f32($_c->[0]); $out->[1] = $rt->f32($_c->[1]); $out->[2] = $rt->f32($_c->[2]); $out->[3] = $rt->f32($_c->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0 };
