# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($quadratic3__vec4_vec4_vec4_float, $quadratic__sampler2D_vec2_vec2, $bicubic4__vec4_vec4_vec4_vec4_float, $bicubic__sampler2D_vec2_vec2, $catmullRom3__vec4_vec4_vec4_float, $catmullRom4__vec4_vec4_vec4_vec4_float, $catmullRom3x3__sampler2D_vec2_vec2, $catmullRom4x4__sampler2D_vec2_vec2, $cosineMix__float_float_float, $main__void);
    my $_retc;
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_seed = exists $U->{'seed'} ? $U->{'seed'} : 0;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_fbTex = $ctx->texture_binding('fbTex');
    my $_u_inputTex = $ctx->texture_binding('inputTex');
    my $_u_smoothing = exists $U->{'smoothing'} ? $U->{'smoothing'} : 0;
    my $_u_inputIntensity = exists $U->{'inputIntensity'} ? $U->{'inputIntensity'} : $rt->f(0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $quadratic3__vec4_vec4_vec4_float = sub {
        my ($p0, $p1, $p2, $t) = @_;
        $p0 = $rt->copy($p0, 'float');
        $p1 = $rt->copy($p1, 'float');
        $p2 = $rt->copy($p2, 'float');
        my ($t2);
        $t2 = $rt->binary('*', $t, $t, 1, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->binary('*', $rt->binary('*', $p0, $rt->f(0.5), 4, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 4, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 4, 'float'), $rt->binary('*', $rt->binary('*', $p1, $rt->f(0.5), 4, 'float'), $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->f(2)), $t2, 1, 'float'), $rt->binary('*', $rt->f(2), $t, 1, 'float'), 1, 'float'), $rt->f(1), 1, 'float'), 4, 'float'), 4, 'float'), $rt->binary('*', $rt->binary('*', $p2, $rt->f(0.5), 4, 'float'), $t2, 4, 'float'), 4, 'float');
    };
    $quadratic__sampler2D_vec2_vec2 = sub {
        my ($tex, $uv, $texelSize) = @_;
        $uv = $rt->copy($uv, 'float');
        $texelSize = $rt->copy($texelSize, 'float');
        my ($baseCoord, $f, $texCoord, $v00, $v01, $v02, $v10, $v11, $v12, $v20, $v21, $v22, $y0, $y1, $y2);
        @{$uv} = map { $rt->f32($_) } @{($rt->binary('+', $uv, $texelSize, 2, 'float'))};
        $texCoord = $rt->binary('/', $uv, $texelSize, 2, 'float');
        $baseCoord = $rt->component_wise('floor', $rt->binary('-', $texCoord, $rt->f(0.5), 2, 'float'));
        $f = $rt->component_wise('fract', $rt->binary('-', $texCoord, $rt->f(0.5), 2, 'float'));
        $v00 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float'));
        $v10 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float'));
        $v20 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float'));
        $v01 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v11 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v21 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v02 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v12 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v22 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float'));
        $y0 = $quadratic3__vec4_vec4_vec4_float->($v00, $v10, $v20, $rt->swizzle($f, 'x'));
        $y1 = $quadratic3__vec4_vec4_vec4_float->($v01, $v11, $v21, $rt->swizzle($f, 'x'));
        $y2 = $quadratic3__vec4_vec4_vec4_float->($v02, $v12, $v22, $rt->swizzle($f, 'x'));
        return $quadratic3__vec4_vec4_vec4_float->($y0, $y1, $y2, $rt->swizzle($f, 'y'));
    };
    $bicubic4__vec4_vec4_vec4_vec4_float = sub {
        my ($p0, $p1, $p2, $p3, $t) = @_;
        $p0 = $rt->copy($p0, 'float');
        $p1 = $rt->copy($p1, 'float');
        $p2 = $rt->copy($p2, 'float');
        $p3 = $rt->copy($p3, 'float');
        my ($b0, $b1, $b2, $b3, $t2, $t3);
        $t2 = $rt->binary('*', $t, $t, 1, 'float');
        $t3 = $rt->binary('*', $t2, $t, 1, 'float');
        $b0 = $rt->binary('/', $rt->binary('*', $rt->binary('*', $rt->binary('-', $rt->f(1), $t, 1, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 1, 'float'), $rt->binary('-', $rt->f(1), $t, 1, 'float'), 1, 'float'), $rt->f(6), 1, 'float');
        $b1 = $rt->binary('/', $rt->binary('+', $rt->binary('-', $rt->binary('*', $rt->f(3), $t3, 1, 'float'), $rt->binary('*', $rt->f(6), $t2, 1, 'float'), 1, 'float'), $rt->f(4), 1, 'float'), $rt->f(6), 1, 'float');
        $b2 = $rt->binary('/', $rt->binary('+', $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->f(3)), $t3, 1, 'float'), $rt->binary('*', $rt->f(3), $t2, 1, 'float'), 1, 'float'), $rt->binary('*', $rt->f(3), $t, 1, 'float'), 1, 'float'), $rt->f(1), 1, 'float'), $rt->f(6), 1, 'float');
        $b3 = $rt->binary('/', $t3, $rt->f(6), 1, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('+', $rt->binary('*', $p0, $b0, 4, 'float'), $rt->binary('*', $p1, $b1, 4, 'float'), 4, 'float'), $rt->binary('*', $p2, $b2, 4, 'float'), 4, 'float'), $rt->binary('*', $p3, $b3, 4, 'float'), 4, 'float');
    };
    $bicubic__sampler2D_vec2_vec2 = sub {
        my ($tex, $uv, $texelSize) = @_;
        $uv = $rt->copy($uv, 'float');
        $texelSize = $rt->copy($texelSize, 'float');
        my ($baseCoord, $f, $row0, $row1, $row2, $row3, $texCoord);
        @{$uv} = map { $rt->f32($_) } @{($rt->binary('+', $uv, $texelSize, 2, 'float'))};
        $texCoord = $rt->binary('/', $uv, $texelSize, 2, 'float');
        $baseCoord = $rt->component_wise('floor', $rt->binary('-', $texCoord, $rt->f(1), 2, 'float'));
        $f = $rt->component_wise('fract', $rt->binary('-', $texCoord, $rt->f(1), 2, 'float'));
        $row0 = $bicubic4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        $row1 = $bicubic4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        $row2 = $bicubic4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        $row3 = $bicubic4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        return $bicubic4__vec4_vec4_vec4_vec4_float->($row0, $row1, $row2, $row3, $rt->swizzle($f, 'y'));
    };
    $catmullRom3__vec4_vec4_vec4_float = sub {
        my ($p0, $p1, $p2, $t) = @_;
        $p0 = $rt->copy($p0, 'float');
        $p1 = $rt->copy($p1, 'float');
        $p2 = $rt->copy($p2, 'float');
        my ($m, $t2, $t3);
        $t2 = $rt->binary('*', $t, $t, 1, 'float');
        $t3 = $rt->binary('*', $t2, $t, 1, 'float');
        $m = $rt->binary('*', $rt->f(0.5), $rt->binary('-', $p2, $p0, 4, 'float'), 4, 'float');
        return $rt->binary('+', $rt->binary('+', $rt->binary('+', $rt->binary('*', $rt->binary('+', $rt->binary('-', $rt->binary('*', $rt->f(2), $t3, 1, 'float'), $rt->binary('*', $rt->f(3), $t2, 1, 'float'), 1, 'float'), $rt->f(1), 1, 'float'), $p1, 4, 'float'), $rt->binary('*', $rt->binary('+', $rt->binary('-', $t3, $rt->binary('*', $rt->f(2), $t2, 1, 'float'), 1, 'float'), $t, 1, 'float'), $m, 4, 'float'), 4, 'float'), $rt->binary('*', $rt->binary('+', $rt->binary('*', $rt->unary('-', $rt->f(2)), $t3, 1, 'float'), $rt->binary('*', $rt->f(3), $t2, 1, 'float'), 1, 'float'), $p2, 4, 'float'), 4, 'float'), $rt->binary('*', $rt->binary('-', $t3, $t2, 1, 'float'), $m, 4, 'float'), 4, 'float');
    };
    $catmullRom4__vec4_vec4_vec4_vec4_float = sub {
        my ($p0, $p1, $p2, $p3, $t) = @_;
        $p0 = $rt->copy($p0, 'float');
        $p1 = $rt->copy($p1, 'float');
        $p2 = $rt->copy($p2, 'float');
        $p3 = $rt->copy($p3, 'float');
        return $rt->binary('+', $p1, $rt->binary('*', $rt->binary('*', $rt->f(0.5), $t, 1, 'float'), $rt->binary('+', $rt->binary('-', $p2, $p0, 4, 'float'), $rt->binary('*', $t, $rt->binary('+', $rt->binary('-', $rt->binary('+', $rt->binary('-', $rt->binary('*', $rt->f(2), $p0, 4, 'float'), $rt->binary('*', $rt->f(5), $p1, 4, 'float'), 4, 'float'), $rt->binary('*', $rt->f(4), $p2, 4, 'float'), 4, 'float'), $p3, 4, 'float'), $rt->binary('*', $t, $rt->binary('-', $rt->binary('+', $rt->binary('*', $rt->f(3), $rt->binary('-', $p1, $p2, 4, 'float'), 4, 'float'), $p3, 4, 'float'), $p0, 4, 'float'), 4, 'float'), 4, 'float'), 4, 'float'), 4, 'float'), 4, 'float'), 4, 'float');
    };
    $catmullRom3x3__sampler2D_vec2_vec2 = sub {
        my ($tex, $uv, $texelSize) = @_;
        $uv = $rt->copy($uv, 'float');
        $texelSize = $rt->copy($texelSize, 'float');
        my ($baseCoord, $f, $texCoord, $v00, $v01, $v02, $v10, $v11, $v12, $v20, $v21, $v22, $y0, $y1, $y2);
        @{$uv} = map { $rt->f32($_) } @{($rt->binary('+', $uv, $texelSize, 2, 'float'))};
        $texCoord = $rt->binary('/', $uv, $texelSize, 2, 'float');
        $baseCoord = $rt->component_wise('floor', $rt->binary('-', $texCoord, $rt->f(1), 2, 'float'));
        $f = $rt->component_wise('fract', $rt->binary('-', $texCoord, $rt->f(1), 2, 'float'));
        $v00 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float'));
        $v10 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float'));
        $v20 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float'));
        $v01 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v11 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v21 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v02 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v12 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float'));
        $v22 = $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float'));
        $y0 = $catmullRom3__vec4_vec4_vec4_float->($v00, $v10, $v20, $rt->swizzle($f, 'x'));
        $y1 = $catmullRom3__vec4_vec4_vec4_float->($v01, $v11, $v21, $rt->swizzle($f, 'x'));
        $y2 = $catmullRom3__vec4_vec4_vec4_float->($v02, $v12, $v22, $rt->swizzle($f, 'x'));
        return $catmullRom3__vec4_vec4_vec4_float->($y0, $y1, $y2, $rt->swizzle($f, 'y'));
    };
    $catmullRom4x4__sampler2D_vec2_vec2 = sub {
        my ($tex, $uv, $texelSize) = @_;
        $uv = $rt->copy($uv, 'float');
        $texelSize = $rt->copy($texelSize, 'float');
        my ($baseCoord, $f, $row0, $row1, $row2, $row3, $texCoord);
        @{$uv} = map { $rt->f32($_) } @{($rt->binary('+', $uv, $texelSize, 2, 'float'))};
        $texCoord = $rt->binary('/', $uv, $texelSize, 2, 'float');
        $baseCoord = $rt->component_wise('floor', $rt->binary('-', $texCoord, $rt->f(1), 2, 'float'));
        $f = $rt->component_wise('fract', $rt->binary('-', $texCoord, $rt->f(1), 2, 'float'));
        $row0 = $catmullRom4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->unary('-', $rt->f(0.5))), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        $row1 = $catmullRom4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->f(0.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        $row2 = $catmullRom4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->f(1.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        $row3 = $catmullRom4__vec4_vec4_vec4_vec4_float->($rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->unary('-', $rt->f(0.5)), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(0.5), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(1.5), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->texture($tex, $rt->binary('*', $rt->binary('+', $baseCoord, $rt->construct(2, $rt->f(2.5), $rt->f(2.5)), 2, 'float'), $texelSize, 2, 'float')), $rt->swizzle($f, 'x'));
        return $catmullRom4__vec4_vec4_vec4_vec4_float->($row0, $row1, $row2, $row3, $rt->swizzle($f, 'y'));
    };
    $cosineMix__float_float_float = sub {
        my ($a, $b, $t) = @_;
        my ($amount);
        $amount = $rt->binary('*', $rt->binary('-', $rt->f(1), $rt->component_wise('cos', $rt->binary('*', $t, $rt->f(3.1415926535900001), 1, 'float')), 1, 'float'), $rt->f(0.5), 1, 'float');
        return $rt->component_wise('mix', $a, $b, $amount);
    };
    $main__void = sub {
        my ($base, $baseIdx, $blend, $globalCoord, $inputColor, $inputUv, $intensity, $maxIdx, $minIdx, $next, $nextIdx, $rdColor, $scaling, $smoothWeights, $state, $texSize, $texSizeI, $texelPos, $texelSize, $uv, $v0, $v00, $v01, $v1, $v10, $v11, $weights);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $state = $rt->f(0);
        $base = $rt->construct(2, 0.0);
        $baseIdx = $rt->construct(2, 0.0, 'int');
        $maxIdx = $rt->construct(2, 0.0, 'int');
        $minIdx = $rt->construct(2, 0.0, 'int');
        $next = $rt->construct(2, 0.0);
        $nextIdx = $rt->construct(2, 0.0, 'int');
        $scaling = $rt->construct(2, 0.0);
        $smoothWeights = $rt->construct(2, 0.0);
        $texSize = $rt->construct(2, 0.0);
        $texSizeI = $rt->construct(2, 0.0, 'int');
        $texelPos = $rt->construct(2, 0.0);
        $texelSize = $rt->construct(2, 0.0);
        $uv = $rt->construct(2, 0.0);
        $v0 = $rt->f(0.0);
        $v00 = $rt->f(0.0);
        $v01 = $rt->f(0.0);
        $v1 = $rt->f(0.0);
        $v10 = $rt->f(0.0);
        $v11 = $rt->f(0.0);
        $weights = $rt->construct(2, 0.0);
        if ($rt->binary('==', $_u_smoothing, $rt->i(0))) {
            $state = $rt->swizzle($rt->texture($_u_fbTex, $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float')), 'g');
        } else {
            if ($rt->binary('==', $_u_smoothing, $rt->i(2))) {
                $texSize = $rt->construct(2, $rt->texture_size($_u_fbTex));
                $texelPos = $rt->binary('-', $rt->binary('/', $rt->binary('*', $globalCoord, $texSize, 2, 'float'), $_u_fullResolution, 2, 'float'), $rt->construct(2, $rt->f(0.5)), 2, 'float');
                $base = $rt->component_wise('floor', $texelPos);
                $weights = $rt->component_wise('fract', $texelPos);
                $next = $rt->binary('+', $base, $rt->construct(2, $rt->f(1)), 2, 'float');
                $texSizeI = $rt->texture_size($_u_fbTex);
                $minIdx = $rt->construct(2, $rt->i(0), 'int');
                $maxIdx = $rt->binary('-', $texSizeI, $rt->construct(2, $rt->i(1), 'int'), 2, 'int');
                $baseIdx = $rt->component_wise('clamp', $rt->construct(2, $base, 'int'), $minIdx, $maxIdx);
                $nextIdx = $rt->component_wise('clamp', $rt->construct(2, $next, 'int'), $minIdx, $maxIdx);
                $v00 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $baseIdx, $rt->i(0)), 'g');
                $v10 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $rt->construct(2, $rt->swizzle($nextIdx, 'x'), $rt->swizzle($baseIdx, 'y'), 'int'), $rt->i(0)), 'g');
                $v01 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $rt->construct(2, $rt->swizzle($baseIdx, 'x'), $rt->swizzle($nextIdx, 'y'), 'int'), $rt->i(0)), 'g');
                $v11 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $nextIdx, $rt->i(0)), 'g');
                $smoothWeights = $rt->component_wise('smoothstep', $rt->f(0), $rt->f(1), $weights);
                $v0 = $rt->component_wise('mix', $v00, $v10, $rt->swizzle($smoothWeights, 'x'));
                $v1 = $rt->component_wise('mix', $v01, $v11, $rt->swizzle($smoothWeights, 'x'));
                $state = $rt->component_wise('mix', $v0, $v1, $rt->swizzle($smoothWeights, 'y'));
            } else {
                if ($rt->binary('==', $_u_smoothing, $rt->i(3))) {
                    $texSize = $rt->construct(2, $rt->texture_size($_u_fbTex));
                    $texelSize = $rt->binary('/', $rt->f(1), $texSize, 2, 'float');
                    $scaling = $rt->binary('/', $_u_fullResolution, $texSize, 2, 'float');
                    $uv = $rt->binary('/', $rt->binary('-', $globalCoord, $rt->binary('*', $scaling, $rt->f(0.5), 2, 'float'), 2, 'float'), $_u_fullResolution, 2, 'float');
                    $state = $rt->swizzle($catmullRom3x3__sampler2D_vec2_vec2->($_u_fbTex, $uv, $texelSize), 'g');
                } else {
                    if ($rt->binary('==', $_u_smoothing, $rt->i(4))) {
                        $texSize = $rt->construct(2, $rt->texture_size($_u_fbTex));
                        $texelSize = $rt->binary('/', $rt->f(1), $texSize, 2, 'float');
                        $scaling = $rt->binary('/', $_u_fullResolution, $texSize, 2, 'float');
                        $uv = $rt->binary('/', $rt->binary('-', $globalCoord, $rt->binary('*', $scaling, $rt->f(0.5), 2, 'float'), 2, 'float'), $_u_fullResolution, 2, 'float');
                        $state = $rt->swizzle($catmullRom4x4__sampler2D_vec2_vec2->($_u_fbTex, $uv, $texelSize), 'g');
                    } else {
                        if ($rt->binary('==', $_u_smoothing, $rt->i(5))) {
                            $texSize = $rt->construct(2, $rt->texture_size($_u_fbTex));
                            $texelSize = $rt->binary('/', $rt->f(1), $texSize, 2, 'float');
                            $scaling = $rt->binary('/', $_u_fullResolution, $texSize, 2, 'float');
                            $uv = $rt->binary('/', $rt->binary('-', $globalCoord, $rt->binary('*', $scaling, $rt->f(0.5), 2, 'float'), 2, 'float'), $_u_fullResolution, 2, 'float');
                            $state = $rt->swizzle($quadratic__sampler2D_vec2_vec2->($_u_fbTex, $uv, $texelSize), 'g');
                        } else {
                            if ($rt->binary('==', $_u_smoothing, $rt->i(6))) {
                                $texSize = $rt->construct(2, $rt->texture_size($_u_fbTex));
                                $texelSize = $rt->binary('/', $rt->f(1), $texSize, 2, 'float');
                                $scaling = $rt->binary('/', $_u_fullResolution, $texSize, 2, 'float');
                                $uv = $rt->binary('/', $rt->binary('-', $globalCoord, $rt->binary('*', $scaling, $rt->f(0.5), 2, 'float'), 2, 'float'), $_u_fullResolution, 2, 'float');
                                $state = $rt->swizzle($bicubic__sampler2D_vec2_vec2->($_u_fbTex, $uv, $texelSize), 'g');
                            } else {
                                $texSize = $rt->construct(2, $rt->texture_size($_u_fbTex));
                                $texelPos = $rt->binary('-', $rt->binary('/', $rt->binary('*', $globalCoord, $texSize, 2, 'float'), $_u_fullResolution, 2, 'float'), $rt->construct(2, $rt->f(0.5)), 2, 'float');
                                $base = $rt->component_wise('floor', $texelPos);
                                $weights = $rt->component_wise('fract', $texelPos);
                                $next = $rt->binary('+', $base, $rt->construct(2, $rt->f(1)), 2, 'float');
                                $texSizeI = $rt->texture_size($_u_fbTex);
                                $minIdx = $rt->construct(2, $rt->i(0), 'int');
                                $maxIdx = $rt->binary('-', $texSizeI, $rt->construct(2, $rt->i(1), 'int'), 2, 'int');
                                $baseIdx = $rt->component_wise('clamp', $rt->construct(2, $base, 'int'), $minIdx, $maxIdx);
                                $nextIdx = $rt->component_wise('clamp', $rt->construct(2, $next, 'int'), $minIdx, $maxIdx);
                                $v00 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $baseIdx, $rt->i(0)), 'g');
                                $v10 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $rt->construct(2, $rt->swizzle($nextIdx, 'x'), $rt->swizzle($baseIdx, 'y'), 'int'), $rt->i(0)), 'g');
                                $v01 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $rt->construct(2, $rt->swizzle($baseIdx, 'x'), $rt->swizzle($nextIdx, 'y'), 'int'), $rt->i(0)), 'g');
                                $v11 = $rt->swizzle($rt->texel_fetch($_u_fbTex, $nextIdx, $rt->i(0)), 'g');
                                if ($rt->binary('==', $_u_smoothing, $rt->i(1))) {
                                    $v0 = $rt->component_wise('mix', $v00, $v10, $rt->swizzle($weights, 'x'));
                                    $v1 = $rt->component_wise('mix', $v01, $v11, $rt->swizzle($weights, 'x'));
                                    $state = $rt->component_wise('mix', $v0, $v1, $rt->swizzle($weights, 'y'));
                                } else {
                                    $v0 = $cosineMix__float_float_float->($v00, $v10, $rt->swizzle($weights, 'x'));
                                    $v1 = $cosineMix__float_float_float->($v01, $v11, $rt->swizzle($weights, 'x'));
                                    $state = $cosineMix__float_float_float->($v0, $v1, $rt->swizzle($weights, 'y'));
                                }
                            }
                        }
                    }
                }
            }
        }
        $intensity = $rt->component_wise('clamp', $state, $rt->f(0), $rt->f(1));
        $rdColor = $rt->construct(3, $intensity);
        $blend = $rt->binary('*', $_u_inputIntensity, $rt->f(0.01), 1, 'float');
        $inputColor = $rt->construct(3, 0.0);
        $inputUv = $rt->construct(2, 0.0);
        if ($rt->binary('>', $blend, $rt->f(0))) {
            $inputUv = $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float');
            $inputColor = $rt->swizzle($rt->texture($_u_inputTex, $inputUv), 'rgb');
            @{$rdColor} = map { $rt->f32($_) } @{($rt->component_wise('mix', $rdColor, $inputColor, $blend))};
        }
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $rdColor, $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
