# Generated by Math::Fractal::Noisemaker::Transpiler - do not edit.
use strict;
use warnings;
no warnings qw(uninitialized);
my $run_pixel = sub {
    my ($ctx, $out) = @_;
    my $rt = $ctx->rt;
    my $U = $ctx->uniforms;
    my $g = {};
    my ($rotate2D__vec2_float, $lineSegmentSDF__vec2_vec2_vec2, $outlineEdge__float_float, $ripplePulse__float, $unfoldVis__float, $flowerMask__vec2_int_float, $fruitMask__vec2_bool, $vesicaMask__vec2, $triquetraMask__vec2, $borromeanMask__vec2, $starPolygonMask__vec2_int, $main__void);
    my $_retc;
    my $_u_resolution = exists $U->{'resolution'} ? $U->{'resolution'} : $rt->construct(2, 0.0);
    my $_u_tileOffset = exists $U->{'tileOffset'} ? $U->{'tileOffset'} : $rt->construct(2, 0.0);
    my $_u_fullResolution = exists $U->{'fullResolution'} ? $U->{'fullResolution'} : $rt->construct(2, 0.0);
    my $_u_aspect = exists $U->{'aspect'} ? $U->{'aspect'} : $rt->f(0.0);
    my $_u_scale = exists $U->{'scale'} ? $U->{'scale'} : $rt->f(0.0);
    my $_u_rotation = exists $U->{'rotation'} ? $U->{'rotation'} : $rt->f(0.0);
    my $_u_thickness = exists $U->{'thickness'} ? $U->{'thickness'} : $rt->f(0.0);
    my $_u_smoothness = exists $U->{'smoothness'} ? $U->{'smoothness'} : $rt->f(0.0);
    my $_u_geometry = exists $U->{'geometry'} ? $U->{'geometry'} : 0;
    my $_u_rings = exists $U->{'rings'} ? $U->{'rings'} : 0;
    my $_u_starPoints = exists $U->{'starPoints'} ? $U->{'starPoints'} : 0;
    my $_u_animation = exists $U->{'animation'} ? $U->{'animation'} : 0;
    my $_u_speed = exists $U->{'speed'} ? $U->{'speed'} : $rt->f(0.0);
    my $_u_pulseDepth = exists $U->{'pulseDepth'} ? $U->{'pulseDepth'} : $rt->f(0.0);
    my $_u_time = exists $U->{'time'} ? $U->{'time'} : $rt->f(0.0);
    my $_u_fgColor = exists $U->{'fgColor'} ? $U->{'fgColor'} : $rt->construct(3, 0.0);
    my $_u_bgColor = exists $U->{'bgColor'} ? $U->{'bgColor'} : $rt->construct(3, 0.0);
    $g->{fragColor} = $rt->construct(4, 0.0);
    $rotate2D__vec2_float = sub {
        my ($p, $angle) = @_;
        $p = $rt->copy($p, 'float');
        my ($c, $s);
        $c = $rt->component_wise('cos', $angle);
        $s = $rt->component_wise('sin', $angle);
        return $rt->construct(2, $rt->binary('-', $rt->binary('*', $rt->swizzle($p, 'x'), $c, 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $s, 1, 'float'), 1, 'float'), $rt->binary('+', $rt->binary('*', $rt->swizzle($p, 'x'), $s, 1, 'float'), $rt->binary('*', $rt->swizzle($p, 'y'), $c, 1, 'float'), 1, 'float'));
    };
    $lineSegmentSDF__vec2_vec2_vec2 = sub {
        my ($p, $a, $b) = @_;
        $p = $rt->copy($p, 'float');
        $a = $rt->copy($a, 'float');
        $b = $rt->copy($b, 'float');
        my ($ba, $h, $pa);
        $pa = $rt->binary('-', $p, $a, 2, 'float');
        $ba = $rt->binary('-', $b, $a, 2, 'float');
        $h = $rt->component_wise('clamp', $rt->binary('/', $rt->dot($pa, $ba), $rt->dot($ba, $ba), 1, 'float'), $rt->f(0), $rt->f(1));
        return $rt->length($rt->binary('-', $pa, $rt->binary('*', $ba, $h, 2, 'float'), 2, 'float'));
    };
    $outlineEdge__float_float = sub {
        my ($d, $w) = @_;
        return $rt->component_wise('smoothstep', $rt->binary('+', $w, $_u_smoothness, 1, 'float'), $rt->binary('-', $w, $_u_smoothness, 1, 'float'), $rt->component_wise('abs', $d));
    };
    $ripplePulse__float = sub {
        my ($phase) = @_;
        return $rt->binary('+', $rt->f(1), $rt->binary('*', $_u_pulseDepth, $rt->component_wise('sin', $rt->binary('-', $rt->binary('*', $rt->binary('*', $_u_time, $rt->f(6.2831853071800001), 1, 'float'), $rt->component_wise('floor', $_u_speed), 1, 'float'), $phase, 1, 'float')), 1, 'float'), 1, 'float');
    };
    $unfoldVis__float = sub {
        my ($t_e) = @_;
        return $rt->component_wise('max', $rt->f(0), $rt->component_wise('sin', $rt->binary('*', $rt->binary('*', $rt->binary('-', $_u_time, $rt->binary('*', $t_e, $rt->f(0.5), 1, 'float'), 1, 'float'), $rt->f(6.2831853071800001), 1, 'float'), $rt->component_wise('floor', $_u_speed), 1, 'float')));
    };
    $flowerMask__vec2_int_float = sub {
        my ($p, $ringsN, $figureScale) = @_;
        $p = $rt->copy($p, 'float');
        my ($_for0_first, $_for1_first, $center, $circleR, $circleRadius, $d, $hexDist, $lineWidth, $m, $q, $r, $t_e, $vis);
        $lineWidth = $rt->binary('+', $rt->f(0.040000000000000001), $rt->binary('*', $_u_thickness, $rt->f(0.12), 1, 'float'), 1, 'float');
        $circleRadius = $rt->f(1);
        @{$p} = map { $rt->f32($_) } @{($rt->binary('*', $p, $figureScale, 2, 'float'))};
        $m = $rt->f(0);
        $q = $rt->unary('-', $rt->i(6));
        $_for0_first = 1;
        for my $_for0 (0 .. 1048575) {
            if (!$_for0_first) {
                $q = $rt->binary('+', $q, $rt->i(1), 1, 'int');
            }
            $_for0_first = 0;
            if (!($rt->binary('<=', $q, $rt->i(6)))) {
                last;
            }
            if ((($rt->binary('<', $q, $rt->unary('-', $ringsN))) || ($rt->binary('>', $q, $ringsN)) ? 1 : 0)) {
                next;
            }
            $r = $rt->unary('-', $rt->i(6));
            $_for1_first = 1;
            for my $_for1 (0 .. 1048575) {
                if (!$_for1_first) {
                    $r = $rt->binary('+', $r, $rt->i(1), 1, 'int');
                }
                $_for1_first = 0;
                if (!($rt->binary('<=', $r, $rt->i(6)))) {
                    last;
                }
                if ((($rt->binary('<', $r, $rt->unary('-', $ringsN))) || ($rt->binary('>', $r, $ringsN)) ? 1 : 0)) {
                    next;
                }
                if ((($rt->binary('<', $rt->binary('+', $q, $r, 1, 'int'), $rt->unary('-', $ringsN))) || ($rt->binary('>', $rt->binary('+', $q, $r, 1, 'int'), $ringsN)) ? 1 : 0)) {
                    next;
                }
                $center = $rt->construct(2, $rt->binary('+', $rt->construct(1, $q), $rt->binary('*', $rt->construct(1, $r), $rt->f(0.5), 1, 'float'), 1, 'float'), $rt->binary('*', $rt->binary('*', $rt->construct(1, $r), $rt->f(1.7320508075688772), 1, 'float'), $rt->f(0.5), 1, 'float'));
                $hexDist = $rt->component_wise('max', $rt->component_wise('max', $rt->component_wise('abs', $rt->construct(1, $q)), $rt->component_wise('abs', $rt->construct(1, $r))), $rt->component_wise('abs', $rt->construct(1, $rt->binary('+', $q, $r, 1, 'int'))));
                $circleR = $circleRadius;
                if ($rt->binary('==', $_u_animation, $rt->i(4))) {
                    $circleR = $rt->binary('*', $circleR, $ripplePulse__float->($rt->binary('*', $hexDist, $rt->f(1.3999999999999999), 1, 'float')), 1, 'float');
                }
                $d = $rt->binary('-', $rt->length($rt->binary('-', $p, $center, 2, 'float')), $circleR, 1, 'float');
                $vis = $rt->f(1);
                $t_e = $rt->f(0.0);
                if ($rt->binary('==', $_u_animation, $rt->i(5))) {
                    $t_e = $rt->binary('/', $hexDist, $rt->component_wise('max', $rt->construct(1, $ringsN), $rt->f(1)), 1, 'float');
                    $vis = $unfoldVis__float->($t_e);
                }
                $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($d, $lineWidth), $vis, 1, 'float'));
            }
        }
        return $m;
    };
    $fruitMask__vec2_bool = sub {
        my ($p, $drawLines) = @_;
        $p = $rt->copy($p, 'float');
        my ($_for2_first, $_for3_first, $_for4_first, $_for5_first, $_for6_first, $angle, $centers, $circleR, $circleUnfoldRange, $d, $dL, $distFromOrigin, $i, $j, $k, $lineVis, $lineWidth, $m, $maxCircleDist, $t_e, $vis);
        $lineWidth = $rt->binary('+', $rt->f(0.040000000000000001), $rt->binary('*', $_u_thickness, $rt->f(0.12), 1, 'float'), 1, 'float');
        @{$p} = map { $rt->f32($_) } @{($rt->binary('*', $p, $rt->f(0.5), 2, 'float'))};
        $centers = $rt->new_array($rt->i(13), 2);
        $centers->[int($rt->i(0))] = $rt->construct(2, $rt->f(0), $rt->f(0));
        $k = $rt->i(0);
        $_for2_first = 1;
        for my $_for2 (0 .. 1048575) {
            if (!$_for2_first) {
                $k = $rt->binary('+', $k, $rt->i(1), 1, 'int');
            }
            $_for2_first = 0;
            if (!($rt->binary('<', $k, $rt->i(6)))) {
                last;
            }
            $angle = $rt->binary('/', $rt->binary('*', $rt->construct(1, $k), $rt->f(3.1415926535900001), 1, 'float'), $rt->f(3), 1, 'float');
            $centers->[int($rt->binary('+', $rt->i(1), $k, 1, 'int'))] = $rt->binary('*', $rt->f(2), $rt->construct(2, $rt->component_wise('cos', $angle), $rt->component_wise('sin', $angle)), 2, 'float');
        }
        $k = $rt->i(0);
        $_for3_first = 1;
        for my $_for3 (0 .. 1048575) {
            if (!$_for3_first) {
                $k = $rt->binary('+', $k, $rt->i(1), 1, 'int');
            }
            $_for3_first = 0;
            if (!($rt->binary('<', $k, $rt->i(6)))) {
                last;
            }
            $angle = $rt->binary('+', $rt->binary('/', $rt->binary('*', $rt->construct(1, $k), $rt->f(3.1415926535900001), 1, 'float'), $rt->f(3), 1, 'float'), $rt->binary('/', $rt->f(3.1415926535900001), $rt->f(6), 1, 'float'), 1, 'float');
            $centers->[int($rt->binary('+', $rt->i(7), $k, 1, 'int'))] = $rt->binary('*', $rt->binary('*', $rt->f(2), $rt->f(1.7320508075688772), 1, 'float'), $rt->construct(2, $rt->component_wise('cos', $angle), $rt->component_wise('sin', $angle)), 2, 'float');
        }
        $maxCircleDist = $rt->binary('*', $rt->f(2), $rt->f(1.7320508075688772), 1, 'float');
        $circleUnfoldRange = (($drawLines) ? ($rt->f(0.59999999999999998)) : ($rt->f(1)));
        $m = $rt->f(0);
        $i = $rt->i(0);
        $_for4_first = 1;
        for my $_for4 (0 .. 1048575) {
            if (!$_for4_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for4_first = 0;
            if (!($rt->binary('<', $i, $rt->i(13)))) {
                last;
            }
            $distFromOrigin = $rt->length($centers->[int($i)]);
            $circleR = $rt->f(1);
            if ($rt->binary('==', $_u_animation, $rt->i(4))) {
                $circleR = $rt->binary('*', $circleR, $ripplePulse__float->($rt->binary('*', $distFromOrigin, $rt->f(0.80000000000000004), 1, 'float')), 1, 'float');
            }
            $d = $rt->binary('-', $rt->length($rt->binary('-', $p, $centers->[int($i)], 2, 'float')), $circleR, 1, 'float');
            $vis = $rt->f(1);
            $t_e = $rt->f(0.0);
            if ($rt->binary('==', $_u_animation, $rt->i(5))) {
                $t_e = $rt->binary('*', $rt->binary('/', $distFromOrigin, $maxCircleDist, 1, 'float'), $circleUnfoldRange, 1, 'float');
                $vis = $unfoldVis__float->($t_e);
            }
            $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($d, $lineWidth), $vis, 1, 'float'));
        }
        $lineVis = $rt->f(0.0);
        if ($drawLines) {
            $lineVis = $rt->f(1);
            if ($rt->binary('==', $_u_animation, $rt->i(5))) {
                $lineVis = $unfoldVis__float->($rt->f(0.65000000000000002));
            }
            $i = $rt->i(0);
            $_for5_first = 1;
            for my $_for5 (0 .. 1048575) {
                if (!$_for5_first) {
                    $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
                }
                $_for5_first = 0;
                if (!($rt->binary('<', $i, $rt->i(13)))) {
                    last;
                }
                $j = $rt->i(0);
                $_for6_first = 1;
                for my $_for6 (0 .. 1048575) {
                    if (!$_for6_first) {
                        $j = $rt->binary('+', $j, $rt->i(1), 1, 'int');
                    }
                    $_for6_first = 0;
                    if (!($rt->binary('<', $j, $rt->i(13)))) {
                        last;
                    }
                    if ($rt->binary('<=', $j, $i)) {
                        next;
                    }
                    $dL = $lineSegmentSDF__vec2_vec2_vec2->($p, $centers->[int($i)], $centers->[int($j)]);
                    $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($dL, $rt->binary('*', $lineWidth, $rt->f(0.5), 1, 'float')), $lineVis, 1, 'float'));
                }
            }
        }
        return $m;
    };
    $vesicaMask__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($dA, $dB, $lineWidth, $m, $r, $rA, $rB, $sep, $visA, $visB);
        $lineWidth = $rt->binary('+', $rt->f(0.040000000000000001), $rt->binary('*', $_u_thickness, $rt->f(0.12), 1, 'float'), 1, 'float');
        @{$p} = map { $rt->f32($_) } @{($rt->binary('*', $p, $rt->f(0.25), 2, 'float'))};
        $r = $rt->f(1.5);
        $sep = $rt->binary('*', $r, $rt->f(0.5), 1, 'float');
        $rA = $r;
        $rB = $r;
        if ($rt->binary('==', $_u_animation, $rt->i(4))) {
            $rA = $rt->binary('*', $rA, $ripplePulse__float->($rt->f(0)), 1, 'float');
            $rB = $rt->binary('*', $rB, $ripplePulse__float->($rt->f(3.1415926535900001)), 1, 'float');
        }
        $visA = $rt->f(1);
        $visB = $rt->f(1);
        if ($rt->binary('==', $_u_animation, $rt->i(5))) {
            $visA = $unfoldVis__float->($rt->f(0));
            $visB = $unfoldVis__float->($rt->f(0.5));
        }
        $dA = $rt->binary('-', $rt->length($rt->binary('-', $p, $rt->construct(2, $rt->unary('-', $sep), $rt->f(0)), 2, 'float')), $rA, 1, 'float');
        $dB = $rt->binary('-', $rt->length($rt->binary('-', $p, $rt->construct(2, $sep, $rt->f(0)), 2, 'float')), $rB, 1, 'float');
        $m = $rt->f(0);
        $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($dA, $lineWidth), $visA, 1, 'float'));
        $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($dB, $lineWidth), $visB, 1, 'float'));
        return $m;
    };
    $triquetraMask__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($C0, $C1, $C2, $d0, $d1, $d2, $dist, $lineWidth, $m, $r, $r0, $r1, $r2, $v01, $v02, $v12);
        $lineWidth = $rt->binary('+', $rt->f(0.040000000000000001), $rt->binary('*', $_u_thickness, $rt->f(0.12), 1, 'float'), 1, 'float');
        @{$p} = map { $rt->f32($_) } @{($rt->binary('*', $p, $rt->f(0.29999999999999999), 2, 'float'))};
        $r = $rt->f(2.25);
        $dist = $rt->binary('/', $r, $rt->f(1.7320508075688772), 1, 'float');
        $C0 = $rt->binary('*', $dist, $rt->construct(2, $rt->component_wise('cos', $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float')), $rt->component_wise('sin', $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'))), 2, 'float');
        $C1 = $rt->binary('*', $dist, $rt->construct(2, $rt->component_wise('cos', $rt->binary('+', $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'), $rt->binary('/', $rt->f(6.2831853071800001), $rt->f(3), 1, 'float'), 1, 'float')), $rt->component_wise('sin', $rt->binary('+', $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'), $rt->binary('/', $rt->f(6.2831853071800001), $rt->f(3), 1, 'float'), 1, 'float'))), 2, 'float');
        $C2 = $rt->binary('*', $dist, $rt->construct(2, $rt->component_wise('cos', $rt->binary('+', $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'), $rt->binary('/', $rt->binary('*', $rt->f(2), $rt->f(6.2831853071800001), 1, 'float'), $rt->f(3), 1, 'float'), 1, 'float')), $rt->component_wise('sin', $rt->binary('+', $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'), $rt->binary('/', $rt->binary('*', $rt->f(2), $rt->f(6.2831853071800001), 1, 'float'), $rt->f(3), 1, 'float'), 1, 'float'))), 2, 'float');
        $r0 = $r;
        $r1 = $r;
        $r2 = $r;
        if ($rt->binary('==', $_u_animation, $rt->i(4))) {
            $r0 = $rt->binary('*', $r0, $ripplePulse__float->($rt->f(0)), 1, 'float');
            $r1 = $rt->binary('*', $r1, $ripplePulse__float->($rt->binary('/', $rt->f(6.2831853071800001), $rt->f(3), 1, 'float')), 1, 'float');
            $r2 = $rt->binary('*', $r2, $ripplePulse__float->($rt->binary('/', $rt->binary('*', $rt->f(2), $rt->f(6.2831853071800001), 1, 'float'), $rt->f(3), 1, 'float')), 1, 'float');
        }
        $d0 = $rt->binary('-', $rt->length($rt->binary('-', $p, $C0, 2, 'float')), $r0, 1, 'float');
        $d1 = $rt->binary('-', $rt->length($rt->binary('-', $p, $C1, 2, 'float')), $r1, 1, 'float');
        $d2 = $rt->binary('-', $rt->length($rt->binary('-', $p, $C2, 2, 'float')), $r2, 1, 'float');
        $v01 = $rt->f(1);
        $v02 = $rt->f(1);
        $v12 = $rt->f(1);
        if ($rt->binary('==', $_u_animation, $rt->i(5))) {
            $v01 = $unfoldVis__float->($rt->f(0));
            $v02 = $unfoldVis__float->($rt->f(0.33000000000000002));
            $v12 = $unfoldVis__float->($rt->f(0.66000000000000003));
        }
        $m = $rt->f(0);
        $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($rt->component_wise('max', $d0, $d1), $lineWidth), $v01, 1, 'float'));
        $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($rt->component_wise('max', $d0, $d2), $lineWidth), $v02, 1, 'float'));
        $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($rt->component_wise('max', $d1, $d2), $lineWidth), $v12, 1, 'float'));
        return $m;
    };
    $borromeanMask__vec2 = sub {
        my ($p) = @_;
        $p = $rt->copy($p, 'float');
        my ($_for7_first, $angle, $c, $circleR, $d, $dist, $i, $lineWidth, $m, $r, $vis);
        $lineWidth = $rt->binary('+', $rt->f(0.040000000000000001), $rt->binary('*', $_u_thickness, $rt->f(0.12), 1, 'float'), 1, 'float');
        @{$p} = map { $rt->f32($_) } @{($rt->binary('*', $p, $rt->f(0.32000000000000001), 2, 'float'))};
        $r = $rt->f(1.5);
        $dist = $rt->f(1.3999999999999999);
        $m = $rt->f(0);
        $i = $rt->i(0);
        $_for7_first = 1;
        for my $_for7 (0 .. 1048575) {
            if (!$_for7_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for7_first = 0;
            if (!($rt->binary('<', $i, $rt->i(3)))) {
                last;
            }
            $angle = $rt->binary('+', $rt->binary('/', $rt->binary('*', $rt->construct(1, $i), $rt->f(6.2831853071800001), 1, 'float'), $rt->f(3), 1, 'float'), $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'), 1, 'float');
            $c = $rt->binary('*', $dist, $rt->construct(2, $rt->component_wise('cos', $angle), $rt->component_wise('sin', $angle)), 2, 'float');
            $circleR = $r;
            if ($rt->binary('==', $_u_animation, $rt->i(4))) {
                $circleR = $rt->binary('*', $circleR, $ripplePulse__float->($rt->binary('/', $rt->binary('*', $rt->construct(1, $i), $rt->f(6.2831853071800001), 1, 'float'), $rt->f(3), 1, 'float')), 1, 'float');
            }
            $d = $rt->binary('-', $rt->length($rt->binary('-', $p, $c, 2, 'float')), $circleR, 1, 'float');
            $vis = $rt->f(1);
            if ($rt->binary('==', $_u_animation, $rt->i(5))) {
                $vis = $unfoldVis__float->($rt->binary('/', $rt->construct(1, $i), $rt->f(3), 1, 'float'));
            }
            $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($d, $lineWidth), $vis, 1, 'float'));
        }
        return $m;
    };
    $starPolygonMask__vec2_int = sub {
        my ($p, $n) = @_;
        $p = $rt->copy($p, 'float');
        my ($_for8_first, $a, $angle1, $angle2, $b, $dL, $i, $j, $lineWidth, $m, $radius, $vis);
        $lineWidth = $rt->binary('+', $rt->f(0.040000000000000001), $rt->binary('*', $_u_thickness, $rt->f(0.12), 1, 'float'), 1, 'float');
        @{$p} = map { $rt->f32($_) } @{($rt->binary('*', $p, $rt->f(0.32000000000000001), 2, 'float'))};
        $radius = $rt->f(2.7999999999999998);
        if ($rt->binary('==', $_u_animation, $rt->i(4))) {
            $radius = $rt->binary('*', $radius, $ripplePulse__float->($rt->f(0)), 1, 'float');
        }
        $m = $rt->f(0);
        $i = $rt->i(0);
        $_for8_first = 1;
        for my $_for8 (0 .. 1048575) {
            if (!$_for8_first) {
                $i = $rt->binary('+', $i, $rt->i(1), 1, 'int');
            }
            $_for8_first = 0;
            if (!($rt->binary('<', $i, $rt->i(12)))) {
                last;
            }
            if ($rt->binary('>=', $i, $n)) {
                last;
            }
            $j = $rt->binary('-', $rt->binary('+', $i, $rt->i(2), 1, 'int'), $rt->binary('*', $rt->binary('/', $rt->binary('+', $i, $rt->i(2), 1, 'int'), $n, 1, 'int'), $n, 1, 'int'), 1, 'int');
            $angle1 = $rt->binary('+', $rt->binary('/', $rt->binary('*', $rt->construct(1, $i), $rt->f(6.2831853071800001), 1, 'float'), $rt->construct(1, $n), 1, 'float'), $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'), 1, 'float');
            $angle2 = $rt->binary('+', $rt->binary('/', $rt->binary('*', $rt->construct(1, $j), $rt->f(6.2831853071800001), 1, 'float'), $rt->construct(1, $n), 1, 'float'), $rt->binary('*', $rt->f(3.1415926535900001), $rt->f(0.5), 1, 'float'), 1, 'float');
            $a = $rt->binary('*', $radius, $rt->construct(2, $rt->component_wise('cos', $angle1), $rt->component_wise('sin', $angle1)), 2, 'float');
            $b = $rt->binary('*', $radius, $rt->construct(2, $rt->component_wise('cos', $angle2), $rt->component_wise('sin', $angle2)), 2, 'float');
            $dL = $lineSegmentSDF__vec2_vec2_vec2->($p, $a, $b);
            $vis = $rt->f(1);
            if ($rt->binary('==', $_u_animation, $rt->i(5))) {
                $vis = $unfoldVis__float->($rt->binary('/', $rt->construct(1, $i), $rt->construct(1, $n), 1, 'float'));
            }
            $m = $rt->component_wise('max', $m, $rt->binary('*', $outlineEdge__float_float->($dL, $lineWidth), $vis, 1, 'float'));
        }
        return $m;
    };
    $main__void = sub {
        my ($color, $globalCoord, $m, $p, $rad, $scaleFactor, $st);
        $globalCoord = $rt->binary('+', $rt->swizzle($ctx->{frag_coord}, 'xy'), $_u_tileOffset, 2, 'float');
        $st = $rt->binary('/', $globalCoord, $_u_fullResolution, 2, 'float');
        @{$st} = map { $rt->f32($_) } @{($rt->binary('*', $rt->binary('-', $st, $rt->f(0.5), 2, 'float'), $rt->f(2), 2, 'float'))};
        $st = $rt->assign_swizzle($st, 'x', $rt->binary('*', $rt->swizzle($st, 'x'), $_u_aspect, 1, 'float'));
        $rad = $rt->binary('/', $rt->binary('*', $_u_rotation, $rt->f(3.1415926535900001), 1, 'float'), $rt->f(180), 1, 'float');
        @{$st} = map { $rt->f32($_) } @{($rotate2D__vec2_float->($st, $rad))};
        if ($rt->binary('==', $_u_animation, $rt->i(1))) {
            @{$st} = map { $rt->f32($_) } @{($rotate2D__vec2_float->($st, $rt->binary('*', $rt->binary('*', $_u_time, $rt->f(6.2831853071800001), 1, 'float'), $rt->component_wise('floor', $_u_speed), 1, 'float')))};
        }
        $scaleFactor = $rt->binary('-', $rt->f(21), $_u_scale, 1, 'float');
        if ($rt->binary('==', $_u_animation, $rt->i(2))) {
            $scaleFactor = $rt->binary('*', $scaleFactor, $rt->binary('+', $rt->f(1), $rt->binary('*', $_u_pulseDepth, $rt->component_wise('sin', $rt->binary('*', $rt->binary('*', $_u_time, $rt->f(6.2831853071800001), 1, 'float'), $rt->component_wise('floor', $_u_speed), 1, 'float')), 1, 'float'), 1, 'float'), 1, 'float');
        }
        $p = $rt->binary('*', $st, $scaleFactor, 2, 'float');
        $m = $rt->f(0);
        if ($rt->binary('==', $_u_geometry, $rt->i(0))) {
            $m = $flowerMask__vec2_int_float->($p, $_u_rings, $rt->f(0.45000000000000001));
        } else {
            if ($rt->binary('==', $_u_geometry, $rt->i(4))) {
                $m = $flowerMask__vec2_int_float->($p, $rt->i(1), $rt->f(0.23000000000000001));
            } else {
                if ($rt->binary('==', $_u_geometry, $rt->i(1))) {
                    $m = $fruitMask__vec2_bool->($p, 0);
                } else {
                    if ($rt->binary('==', $_u_geometry, $rt->i(3))) {
                        $m = $fruitMask__vec2_bool->($p, 1);
                    } else {
                        if ($rt->binary('==', $_u_geometry, $rt->i(5))) {
                            $m = $vesicaMask__vec2->($p);
                        } else {
                            if ($rt->binary('==', $_u_geometry, $rt->i(6))) {
                                $m = $borromeanMask__vec2->($p);
                            } else {
                                if ($rt->binary('==', $_u_geometry, $rt->i(8))) {
                                    $m = $triquetraMask__vec2->($p);
                                } else {
                                    if ($rt->binary('==', $_u_geometry, $rt->i(7))) {
                                        $m = $starPolygonMask__vec2_int->($p, $_u_starPoints);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        $m = $rt->component_wise('clamp', $m, $rt->f(0), $rt->f(1));
        $color = $rt->component_wise('mix', $_u_bgColor, $_u_fgColor, $m);
        @{$g->{fragColor}} = map { $rt->f32($_) } @{($rt->construct(4, $color, $rt->f(1)))};
    };
    $main__void->();
    my $_c0 = $g->{fragColor};
    $out->[0] = $rt->f32($_c0->[0]); $out->[1] = $rt->f32($_c0->[1]); $out->[2] = $rt->f32($_c0->[2]); $out->[3] = $rt->f32($_c0->[3]);
};
{ kernel => $run_pixel, uses_derivatives => 0, output_names => ['fragColor'] };
